### ISSUE TITLE
How to enable SSH compression ?

### ISSUE THREAD

**Issue by dgarros** [ncclient/ncclient#114]
Hi 

Is there a way to enable SSH compression when using Ncclient ? I looked at the doc but haven't been able to find something useful 

i tried to enable it by default on ssh_config but it's not making a difference
If I start a netconf session manually from CLI, I can confirm that Compression is working correctly.

Thanks
Damien

**Comment by leopoul** [comment]
ssh compression is now supported via the compression statement in ssh config: https://github.com/ncclient/ncclient/pull/124

**Comment by dgarros** [comment]
Oh great thanks !


--
Damien GARROS
dgarros@gmail.com
