### ISSUE TITLE
Verbose mode for outgoing NETCONF requests?

### ISSUE THREAD

**Issue by hellt** [ncclient/ncclient#115]
Hello *. First of all thanks to contributors for such a great tool.
I am trying to add more sophisticated support for Nokia (ALU) routers coz I have them all but I am wondering if it is possible to enable some kind of **verbose** mode to see what NETCONF request has been compiled right after its sending on the wire?

**Comment by mkbt** [comment]
There are loggers around in the code base built from a base of 'ncclient'.

Try adding something like this the beginning of the code using ncclient:


```
logger = logging.getLogger('ncclient')
logger.setLevel(logging.DEBUG)

ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

ch.setFormatter(formatter)

logger.addHandler(ch)

```

--Mark

**Comment by leopoul** [comment]
Thnx Mark,

Alternatively, one could add:

```
import logging

logging.basicConfig(
       level=logging.DEBUG,
   )
```
