### ISSUE TITLE
info level log should include rpc command

### ISSUE THREAD

**Issue by vnitinv** [ncclient/ncclient#146]
When debug is set to info, We just get below message when a rpc is called
Requesting 'ExecuteRpc'

If possible can it also include the rpc being called, say for example
Requesting 'ExecuteRpc' <open-connection>

https://github.com/ncclient/ncclient/blob/d8fdaef699bd4c2d457f2bbc7ced988aa82bb786/ncclient/operations/rpc.py#L314

**Comment by leopoul** [comment]
You mean the actual XML that is to be sent out?

**Comment by vnitinv** [comment]
Yes @leopoul 
I meant
```
Requesting 'ExecuteRpc: <close-session/>
```

**Comment by iwanb** [comment]
The XML used to be logged in older releases (I was using 0.6.2), but now it's just object references:
```
DEBUG - [host None session 0x7f137ba75278] <SSHSession(session, initial daemon)> created: client_capabilities=<dict_keyiterator object at 0x7f137b9c3048> [session=<SSHSession(session, initial daemon)>] - ncclient.transport.session line 57
```

**Comment by einarnn** [comment]
@iwanb, we found that the XML was being logged in too many places, but it is still possible to get the XML out via logging. Please try enabling debug/info logging on `ncclient.transport.ssh`.

Cheers,

Einar
