### ISSUE TITLE
Build problem in C locale

### ISSUE THREAD

**Issue by 0-wiz-0** [ncclient/ncclient#160]
When building ncclient with python-3.x in a C locale (i.e. not UTF-8), it fails with:
````
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    long_description = file.read()
  File "/usr/pkg/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 4335: ordinal not in range(128)
````
The problem is that one of the contributors listed in `README.rst` is using UTF-8 characters.

**Comment by hggh** [comment]
@vnitinv Could you please release a new version on pypi? - so the fix is available via pypi?

**Comment by leopoul** [comment]
Will do that today

**Comment by jwwilcox** [comment]
@leopoul any chance #162 could be merged for that release as well?

**Comment by leopoul** [comment]
Merged, I'm preparing the pypi release

Thanks for the contribution!

**Comment by leopoul** [comment]
New version 0.5.3 is on PyPi

Thanks,
Leo
