### ISSUE TITLE
aise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.') in Cisco ios

### ISSUE THREAD

**Issue by prince07** [ncclient/ncclient#173]
Hi, 

My name is aashiq I try to connect my site office switch cisco 4500 with netconf and ncclient  with python2.7.1 and I got TimeoutExpired Error. how to solve this . 

**Cisco device is** =  Catalyst 4500 L3 Switch Software (cat4500e-IPBASEK9-M), Version 15.0(2)SG5, RELEASE SOFTWARE (fc1)

**Programming language** = python 2.7.1

**Ncclient version** = 0.5.3

**Netconf in cisco switch** = {
netconf max-sessions 16
netconf lock-time 300
netconf ssh
   }

**Python code** = {

```
def main():

    with manager.connect(host=host,port=22,username=username,password=password,
                         hostkey_verify=False,allow_agent=False,look_for_keys=False) as cnn:
     for cap in cnn.server_capabilities:
         print cap
    print "out"
    

if __name__ == '__main__':
    sys.exit(main())

```

}
**The error output is (debug)**= {

                                C:\Python27\python.exe D:/ADEC_py_Work/netconf/test.py
urn:ietf:params:netconf:capability:url:1.0
urn:cisco:params:netconf:capability:pi-data-model:1.0
urn:ietf:params:netconf:base:1.0
urn:ietf:params:netconf:capability:startup:1.0
urn:cisco:params:netconf:capability:notification:1.0
urn:ietf:params:netconf:capability:writeable-running:1.0
Traceback (most recent call last):
  File "D:/ADEC_py_Work/netconf/test.py", line 19, in <module>
    sys.exit(main())
  File "D:/ADEC_py_Work/netconf/test.py", line 14, in main
    print cap
  File "C:\Python27\lib\site-packages\ncclient\manager.py", line 214, in __exit__
    self.close_session()
  File "C:\Python27\lib\site-packages\ncclient\manager.py", line 162, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "C:\Python27\lib\site-packages\ncclient\manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "C:\Python27\lib\site-packages\ncclient\operations\session.py", line 28, in request
    return self._request(new_ele("close-session"))
  File "C:\Python27\lib\site-packages\ncclient\operations\rpc.py", line 343, in _request
    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.

                                         }

Please help me to clear this error. 

Thanks

**Comment by einarnn** [comment]
Hi,

Port should probably be 830, not 22.

Cheers,

Einar

**Comment by prince07** [comment]
is showing error ncclient.transport.errors.SSHError: Could not open socket to 10.94.94.1:830 , But my cisco config is ```
netconf max-sessions 16
netconf lock-time 300
netconf ssh

```

**Comment by prince07** [comment]
I can see that there is connection happen with port no. 22.
the switch sh netconf session output is . 

```
#sh netconf session
Netconf Sessions: 1 open, maximum is 16
Remote connection via SSH by user(00000) from xx.xxx.xx.xxx:32719, delete
Tx 730 bytes (2 msg), Rx 1391 bytes (2 msg, 0 segmented)
Established at 08:24:15.372 UAE Sun Jan 29 2017
Last operation at 08:24:15.480 UAE Sun Jan 29 2017
Last successful operation at 08:24:15.480 UAE Sun Jan 29 2017
Session id:558515236
Connection waiting for close
```
and after the 

> ncclient.transport.errors.TransportError: Not connected to NETCONF server

error message the netconf session output is 

```
#sh netconf session
Netconf Sessions: 0 open, maximum is 16
```

**Comment by einarnn** [comment]
Can you try just doing:

ssh user@device -s netconf

...with appropriate values for user and device? This should let you see if there is any basic ssh issue.

Cheers,

Einar

**Comment by leopoul** [comment]
Thanks Einar,

Aashiq, I'd say the same thing as Einar, you can check the https://github.com/ncclient/ncclient/wiki/Debug page for more details

Let us know if that worked for you.

Thanks,
L

**Comment by einarnn** [comment]
@prince07, since there has been no further information on this thread I am assuming it is no longer an active issue. Please feel free to reopen if there is still a problem.
