### ISSUE TITLE
Let sub_ele inherit parent namespace per default

### ISSUE THREAD

**Issue by plajjan** [ncclient/ncclient#176]
sub_ele defaults to using the `urn:ietf:params:xml:ns:netconf:base:1.0` namespace.

Further, unlike new_ele for which there is a new_ele_ns that also accepts a namespace, there is no such equivalent for sub_ele. How am I supposed to add subelement in my namespace of choice?

I suggest that:
 * a sub_ele_ns is introduced which let's the user specify the namespace to use
 * that sub_ele defaults to using the namespace of its parent

I implemented the first https://github.com/plajjan/ncclient/commit/8ab482b19c5135987f947de812eabc6077740dc2 (can open PR..). The second addition would greatly reduce the code required since it's very very common that nodes actually use the same namespace as their parent. I'm happy to put that in as a PR too.

Apologies if I've just misunderstood how this is supposed to work.

**Comment by fredgan** [comment]
Hi @einarnn ,
This issue is resolved by PR #404, so it can be closed :)

**Comment by einarnn** [comment]
Resolved by #404
