### ISSUE TITLE
Getting JSON from very old software causes a ValueError.

### ISSUE THREAD

**Issue by jeffsilverm** [ncclient/ncclient#177]
With very old (12.1X46-D60.4) software, a JunOS SRX-210 will return empty JSON, which then causes a `ValueError` exception to be raised.  This problem is an unintended consequence of issue of [issue 147](https://github.com/ncclient/ncclient/pull/147) and is incredibly arcane.

The fix I created was to enclose the call to `json.loads` in a `try..except` block to catch a `ValueError` exception.

    23,29c21,22
    <     try :
    <         payload = json.loads(result_json.xpath('.')[0].text)
    < # This exception might be thrown if the device is too old
    <     except ValueError as v:
    <         print("There was a problem getting the results in JSON format, error is %s" % v.__str__, file=sys.stderr )
    <     else :
    <         print((payload['configuration']['system']['services']))
     ---
    >     payload = json.loads(result_json.xpath('.')[0].text)
    >     print(payload['configuration']['system']['services'])

I also ran the code through 2to3, added an `import six` statement and `from __future__ import print_function` at the top of the file,  It now runs quite nicely on both python 2.7.12 and python 3.5.2

**Comment by leopoul** [comment]
Hi,

Would you like me to add it to edit-config-jnpr-json.py or you prefer to create a PR? It should run on py3 out of the box.

Thanks,
L

**Comment by jeffsilverm** [comment]
Leopoul,

I will defer to your preference.

The software **does** run on P3 out of the box.  I have worked at places where they had a million bajillon lines of code that would not run on P3, and they felt that there was no compelling reason to change.  They were concerned that upgrading would break their old code, their developers already knew how to write in 2.7.x and didn't want to come down a learning curve, and they knew that they would be gone to other things when the bill for the technical debt came due.

**Comment by einarnn** [comment]
No further feedback; closing for now.
