### ISSUE TITLE
ncclient waits for a server's hello message

### ISSUE THREAD

**Issue by maseev** [ncclient/ncclient#181]
Correct me if I'm wrong, but according to [spec](https://tools.ietf.org/html/rfc6241#section-8.1) server and client don't have to wait for each other's hello messages that include their capabilities:

> Capabilities are advertised in messages sent by each peer during
   session establishment.  When the NETCONF session is opened, each peer
   (both client and server) MUST send a <hello> element containing a
   list of that peer's capabilities.
> ...
> Each peer sends its <hello> element simultaneously as soon as the
   connection is open.  A peer MUST NOT wait to receive the capability
   set from the other side before sending its own set.

Right now, it looks like ncclient is waiting for a server to send a ```hello``` message first which clearly violates the spec.

**Comment by leopoul** [comment]
https://github.com/ncclient/ncclient/blob/master/ncclient/transport/session.py#L97 indicates that there is no blocking when it comes to hello messages exchange with server. Could you provide an example or code references for the opposite?

**Comment by maseev** [comment]
Sorry, it was a long time ago. I was able to make my application work with `ncclient` in the end. I'm not sure I'll be able to provide a reproducer for this case. It was probably a bug in my application code. Thanks anyway.
