### ISSUE TITLE
Unable to send an RPC

### ISSUE THREAD

**Issue by maseev** [ncclient/ncclient#182]
I was trying to send an RPC to the NETCONF server using [one](https://github.com/ncclient/ncclient/blob/f734dfc7124a20bf067df1b12c23bba191bcdb89/examples/juniper/execute-rpc-string.py) of the examples that you provide. Here's my code:

```python
#!/usr/bin/env python

from ncclient import manager

def connect(host, port, user, password, source):
    print('establishing connection...')
    conn=manager.connect(host=host,
                         port=port,
                         username=user,
                         password=password,
                         timeout=10,
                         hostkey_verify=False,
                         device_params={'name':'default'})
    try:
        print("connection has been established")
        print("server capabilities:")

        for c in conn.server_capabilities:
            print(c)

        rpc = """
        <get-chassis-inventory>
            <detail/>
        </get-chassis-inventory>"""

        print('sending an RPC')
        result = conn.rpc(rpc)
        print(result)
    except Exception as rpcException:
        print("An exception occurred while sending an RPC: " + str(rpcException))
    finally:
        print("closing connection...")
        try:
            conn.close_session()
        except Exception as sessionException:
            print("An exception occurred while closing the session :" + str(sessionException))
        print("connection has been closed")


if __name__ == '__main__':
    connect('localhost', 1830, 'user', 'pass', 'candidate')
```

Calling `conn.rpc(rpc)` throws the following exception:

`Invalid tag name u'\n        <get-chassis-inventory>\n            <detail/>\n        </get-chassis-inventory>'`

which doesn't make a lot of sense. Am I doing something wrong? From the exception message it's very unclear what I'm supposed to do.

**Comment by jwwilcox** [comment]
Try conn.dispatch instead of conn.rpc

**Comment by maseev** [comment]
@jwwilcox Just tried it - same error

**Comment by jwwilcox** [comment]
Ah found it.

    from ncclient.xml_ import to_ele
    ...
    conn.dispatch(to_ele("<my-rpc><string/></my-rpc>"))

**Comment by jwwilcox** [comment]
Yes you can use the to_xml function from the same module (ncclient.xml_)

**Comment by maseev** [comment]
@jwwilcox Is it possible to send an xml document as is or at least change the xml namespace? Right now when I'm trying to send a request to the server: 

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:rpc xmlns:ns2="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="64">
  <ns2:rpcOperation>
    <operation-name>switch.get-switches-page</operation-name>
    <operation-argument>
      <page-request-in>
        <page>0</page>
        <size>15</size>
      </page-request-in>
    </operation-argument>
  </ns2:rpcOperation>
</ns2:rpc>
```

I've got the following document on the server side:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
        message-id="urn:uuid:b16d648f-0941-4e46-aa86-1036764cae16">
  <nc:rpc message-id="64">
    <nc:rpcOperation>
      <operation-name>switch.get-switches-page</operation-name>
      <operation-argument>
        <page-request-in>
          <page>0</page>
          <size>15</size>
        </page-request-in>
      </operation-argument>
    </nc:rpcOperation>
  </nc:rpc>
</nc:rpc>
```

It looks like ncclient wraps the passed xml document inside another `rpc` tag which is not what I intended to do.

When I change the initial XML document to this:

```xml
  <ns2:rpcOperation>
    <operation-name>switch.get-switches-page</operation-name>
    <operation-argument>
      <page-request-in>
        <page>0</page>
        <size>15</size>
      </page-request-in>
    </operation-argument>
  </ns2:rpcOperation>
```

I've got the following XML on the server side:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
        message-id="urn:uuid:96d2bf76-d3ec-4670-8dd2-3686e41d4638">
  <ns2:rpcOperation>
    <operation-name>switch.get-switches-page</operation-name>
    <operation-argument>
      <page-request-in>
        <page>0</page>
        <size>15</size>
      </page-request-in>
    </operation-argument>
  </ns2:rpcOperation>
</nc:rpc>
```

**Comment by jwwilcox** [comment]
Yeah it's going to automatically create the outer rpc tag for you. If you needed to set some custom namespace you can do that on your own top-level element. E.g.:

    <my-ns:some-operation xmlns:my-ns="http://example.com">
        <my-ns:more-stuff>Something</my-ns:more-stuff>
    </my-ns:some-operation>

Or you could just set the default namespace:

    <some-operation xmlns="http://example.com">
        <more-stuff>Something</more-stuff>
    </some-operation>

**Comment by maseev** [comment]
It seems to be working OK now. At least I can send a request to the server and the server returns a reply, but it looks like ncclient throws an exception when it tries to parse the reply from the server (exception message is empty again :disappointed:). Is it possible to somehow enable logging (if there's any) on the nccclient side so I'll be able to debug what's going on?

**Comment by jwwilcox** [comment]
This will spam a bunch of stuff to stdout (you can send it to a file as well).

    import logging
    import sys
    logging.basicConfig(level=logging.DEBUG,
                        format='%(asctime)s %(levelname)s: %(message)s',
                        stream=sys.stdout)

**Comment by maseev** [comment]
Looks like I need to set a path to an XSD file so ncclient will be able to parse the incoming data from the netconf server. Am I right? Or this is unnecessary?

**Comment by maseev** [comment]
It's definitely something wrong with the data server sends back to a client:

```
2017-03-22 01:14:53,251 DEBUG: Selecting netconf:base:1.1 for encoding
2017-03-22 01:14:53,252 DEBUG: parsing netconf v1.1
2017-03-22 01:14:53,252 DEBUG: x: 

2017-03-22 01:14:53,252 DEBUG: x: 

2017-03-22 01:14:53,252 DEBUG: invalid base:1:1 frame (1: expect "#")
2017-03-22 01:14:53,252 DEBUG: Broke out of main loop, error=Exception()
2017-03-22 01:14:53,252 DEBUG: dispatching error to <ncclient.transport.session.NotificationHandler object at 0x7fdeba64e810>
2017-03-22 01:14:53,252 DEBUG: dispatching error to <ncclient.operations.rpc.RPCReplyListener object at 0x7fdebb24edd0>
```

I'm not really sure how to interpret this one:

```
invalid base:1:1 frame (1: expect "#")
```

**Comment by jwwilcox** [comment]
It was looking for the message framer for NETCONF 1.1 (#), but instead it got a newline.

Seems likely due to a non-compliant NETCONF 1.1 server but it's hard to tell for sure. You could try to get it to negotiate for 1.0 instead, but I can't recall how to do that off hand.

**Comment by maseev** [comment]
@jwwilcox Just to make sure we're on the same page, Are you talking about [chunked framing mechanism](https://tools.ietf.org/html/rfc6242#section-4.2)?

**Comment by jwwilcox** [comment]
Yes

**Comment by maseev** [comment]
Yep, you are right. The problem was in the additional '\n' symbol before the NETCONF reply message. The problem now is that ncclient for some reason can't parse the rpc-reply document. I removed the statement that sends the RPC. So now ncclient only sends a hello message, gets the server capabilities and then issues the session-close event. Ncclient sends the following XML to the server:

```xml
#184
<?xml version="1.0" encoding="UTF-8"?>
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
        message-id="urn:uuid:3db293c8-c13c-4a0c-a9d8-18129b2f06c1">
  <nc:close-session/>
</nc:rpc>
##
```

and the server responds with:

```xml
#286
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:rpc-reply xmlns:ns2="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:3db293c8-c13c-4a0c-a9d8-18129b2f06c1">
    <ns2:ok xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="rpcOk"/>
</ns2:rpc-reply>
##
```

but ncclient throws the following exception:

```
2017-03-22 20:39:41,853 DEBUG: parsed new chunk: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:rpc-reply xmlns:ns2="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:3db293c8-c13c-4a0c-a9d8-18129b2f06c1">
    <ns2:ok xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="rpcOk"/>
</ns2:rpc-reply>
#
2017-03-22 20:39:41,853 DEBUG: x: #
2017-03-22 20:39:41,853 DEBUG: invalid base:1:1 frame (3: expect newline)
```

What 'newline' does it actually expect? From what I see, the server sends the correct method separator at the end of the message body - ##.

**Comment by maseev** [comment]
I think I finally got it. The problem is in the incorrectly computed chunk size which determines the size of the message body. It looks like one of the off by one error.

**Comment by maseev** [comment]
Phew! That was quite an adventure! Thanks for you help @jwwilcox. I wish all that information was in the docs :disappointed:

**Comment by thearpittripathi** [comment]
@maseev Please share the complete code. I am also sending RPC XML to trigger notification manually. I want to do it using ncclient.
