### ISSUE TITLE
There is not have a get-next operation for huawei device.

### ISSUE THREAD

**Issue by enhellowhy** [ncclient/ncclient#187]
Huawei netconf support get-next operation, but our netconf client don not support.

**Comment by 9723** [comment]
Maybe can take a look at this pull #221 and the example [get_next](https://github.com/9723/ncclient/blob/904656abb2879d651225f112304c0f432de1b9e4/examples/hw01.py#L122)

**Comment by einarnn** [comment]
Question seems to have been answered.
