### ISSUE TITLE
Issue on sending content with specific length, NETCONF delimiter gets split

### ISSUE THREAD

**Issue by sergafts** [ncclient/ncclient#189]
When trying to send (to a Juniper device) a set of commands with a specific length ncclient crashes.
It seems that the netconf delimiter (`]]>]]>`) is being split while transporting.

DEBUG level logging output:

```
DEBUG:ncclient.transport.session:dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x7fde1eb66ad0>: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/15.1R5/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:ebf7759f-9a0d-4b90-a8ae-ac7818f68338">
DEBUG:ncclient.operations.rpc:Delivering to <ncclient.operations.third_party.juniper.rpc.ExecuteRpc object at 0x7fde25ab5e90>
DEBUG:ncclient.transport.ssh:Trying another round of parsing since there is still data
DEBUG:ncclient.transport.ssh:parsing netconf v1.0
DEBUG:ncclient.transport.ssh:EOF in transport thread
DEBUG:ncclient.transport.ssh:Broke out of main loop, error=SessionCloseError('Unexpected session close\nIN_BUFFER: `\n`',)
DEBUG:ncclient.transport.session:dispatching error to <ncclient.transport.session.NotificationHandler object at 0x7fde1eb66e10>
DEBUG:ncclient.transport.session:dispatching error to <jnpr.junos.device.DeviceSessionListener object at 0x7fde25f70d50>
DEBUG:ncclient.transport.session:dispatching error to <ncclient.operations.rpc.RPCReplyListener object at 0x7fde1eb66ad0>
```

While debugging, [this](https://github.com/ncclient/ncclient/blob/master/ncclient/transport/ssh.py#L135) seems to be the problematic code snippet:

```
        else:
            # handle case that MSG_DELIM is split over two chunks
            self._parsing_pos10 = buf.tell() - MSG_DELIM_LEN
            if self._parsing_pos10 < 0:
                self._parsing_pos10 = 0
```

This is located in `SSHSession._parse10()` which is called from `SSHSession.run()`. The latter reads message data and adds it into a buffer, for `_parse10()` to read. Then `_parse10()` tries to locate the 
NETCONF delimiter inside the buffer. If, however, the delimiter is split between two buffers it cannot locate it. I tried altering the code in `_parse10()` to move the buffer pointer in the end of the buffer, hoping that when `run()` loads the next chunk directly afterwards the delimiter will be complete and the
next execution of `_parse10()` will locate it correctly. I did not succeed though.

Any ideas?

To reproduce use the python code & input file provided in this [gist](https://gist.github.com/sergafts/fd0d036c2895e82ff66c005d19c4deca)

**Comment by sergafts** [comment]
It seems that we were looking in the wrong place.

The issue is on `SSHSession.run()` but not on the part that calls `_parse10()`, since this is responsible only for listening data and the problem occurs when sending messages.

This function appends `MSG_DELIM` to the data being sent. However, if `len(data) % 4096 > 4096 - MSG_DELIM_LEN` paramiko splits the delimiter.

We have created a temporary solution by left - padding the message with spaces which works. However we cannot find how the value 4096 is decided and whether we can somehow enforce another value on paramiko to make sure this works.

We tried experimenting with `paramiko.Channel`'s `window_size` , `max_packet_size` but no luck so far.
We are thinking of providing a pull request with our fix and then investigate further from there.

**Comment by JVijsma** [comment]
We're hitting this issue too (we think):

From the JunOS trace-option logs:
```
Apr 28 15:48:33 [58160] Incoming: ]>]]>
Apr 28 15:48:33 [58160] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:684abe7d-e52b-453f-a945-19bc3991de9d"><get-configuration compare="rollback" rollback="0" format="text"/></nc:rpc>]]>]]>
Apr 28 15:48:33 [58160] Outgoing: <!-- netconf error: syntax error, expecting &lt;rpc&gt; -->
```
It's missing the first `]`.

**Comment by einarnn** [comment]
Why does the netconf server you are talking to care if the message delimiter is split across multiple fragments by Paramiko? Unless Paramiko is also inserting extra characters, this shouldn't cause a problem. At this point it is not clear that we should be modifying anything in ncclient. This **sounds** more like a netconf server issue, but I don't have access to a device of the reported type to test.

Cheers,

Einar

**Comment by stacywsmith** [comment]
@sergafts @JVijsma I believe you are hitting a known Junos bug which has already been fixed in some Junos releases. Please unicast me (stacys at juniper dot net) the platform and Junos release where you're seeing this issue.

**Comment by sergafts** [comment]
@stacywsmith @einarnn It was my understanding while reading the related NETCONF RFC that Juniper devices made no guarantee if the delimiter is split among multiple fragments the device would be able to understand the message. Nice to know however, we will contact Juniper to continue with this.

**Comment by leopoul** [comment]
@sergafts have you resolved the issue with vendor?
