### ISSUE TITLE
Not connected error

### ISSUE THREAD

**Issue by azlux** [ncclient/ncclient#191]
Here the issue I've start at the end of this issue #59: 
On windows with this [code](https://azlux.fr/bin/?4d6b586a33d38a62#sBTdWwmwiNShX6nrqPZqzyyl4fzB+e5uX6l0AFrXUvc=) I still have [this error](https://azlux.fr/bin/?d7b26d954dabff74#+2lItbt0pdjf7U45oejjI3Fvr3VKBDtUgS8PaT1Zmyg=)

It's like the session close but my Cisco IOS XR Software, Version 5.3.3 have this conf : 

```
netconf-yang agent
 ssh
!
ssh server v2
ssh server netconf port 830
ssh timeout 120
```

So I don't know why I have this error. (The running conf appears into the buffer when the program exit but stop on ```<interface-name>GigabitEthernet0/0/0/19</interface-name>\\n    <shutdown></shutdown>\\n   </interface-configuration>\\n  </interface-configurations>\\n\'`',)```

**Comment by azlux** [comment]
HUmmm .. [I have found this error too](https://azlux.fr/bin/?5448917ab9bbdd1f#ZpxLyyUvV6+7OY5c9Q8ALm2gfE2AnqvP/Ml/mmyYDWg=) On windows and linux. Maybe [my code](https://azlux.fr/bin/?4603e739170a5fa0#3tXD//ouzgTwXqpELJAOGtw13poGos5V2ylLf+YkZSw=) don't have enough debug to understand the pb.

**Comment by leopoul** [comment]
Can you enable debug mode?
eg. 
```
import logging

logging.basicConfig(
    level=logging.INFO,
)
```
at the top of your file. Could you also try to connect via cli? 
```
ssh -p <IP> -s netconf
```

Thanks,
Leonidas

**Comment by einarnn** [comment]
@azlux, since there has been no further information on this thread I am assuming it is no longer an active issue. Please feel free to reopen if there is still a problem.
