### ISSUE TITLE
ncclient.operations.rpc.RPCError: Key leaf given twice with different value

### ISSUE THREAD

**Issue by arslanqadeer** [ncclient/ncclient#198]
I am trying to push configuration but facing above error. I have written following python script for that. Please guide me where i am wrong. Thanks

#!/usr/bin/python
from ncclient import manager
from ncclient.xml_ import *

system_config = """
<?xml version='1.0' encoding='UTF-8'?>
<config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
        <vpn xmlns="http://viptela.com/vpn" xc:operation="replace">
                <vpn-instance>
                                <vpn-id>0</vpn-id>
                                <interface>
                                        <if-name>ge0/0</if-name>
                                        <ip>
                                                <address>3.3.3.3/24</address>
                                        </ip>
                                        <autonegotiate>true</autonegotiate>
                                        <mtu>1500</mtu>
                                        <tunnel-interface>
                                                <hello-interval>1000</hello-interval>
                                                <color>
                                                        <value>default</value>
                                                </color>
                                                <carrier>default</carrier>
                                                <hello-tolerance>12</hello-tolerance>
                                                <nat-refresh-interval>5</nat-refresh-interval>
                                                <allow-service>
                                                        <netconf>true</netconf>
                                                        <all>false</all>
                                                        <stun>true</stun>
                                                        <ntp>true</ntp>
                                                        <sshd>true</sshd>
                                                        <bgp>true</bgp>
                                                        <dns>true</dns>
                                                        <dhcp>true</dhcp>
                                                        <icmp>true</icmp>
                                                        <ospf>true</ospf>
                                                </allow-service>
                                                <encapsulation>
                                                        <encap>ipsec</encap>
                                                </encapsulation>
                                        </tunnel-interface>
                                        <shutdown>false</shutdown>
                                        <pmtu>false</pmtu>
                                        <flow-control>autoneg</flow-control>
                                        <clear-dont-fragment>false</clear-dont-fragment>
                                        <arp-timeout>1200</arp-timeout>
                                </interface>
                                <ecmp-hash-key>
                                        <layer4>false</layer4>
                                </ecmp-hash-key>
                                <vpn-id>512</vpn-id>
                               <interface>
                                        <arp-timeout>1200</arp-timeout>
                                        <if-name>eth0</if-name>
                                        <ip>
                                                <address>1.1.1.21/24</address>
                                        </ip>
                                        <autonegotiate>true</autonegotiate>
                                        <mtu>1500</mtu>
                                        <shutdown>false</shutdown>
                                        <pmtu>false</pmtu>
                                        <clear-dont-fragment>false</clear-dont-fragment>
                                </interface>
                                <ecmp-hash-key>
                                        <layer4>false</layer4>
                                </ecmp-hash-key>
                                <dns>
                                        <role>primary</role>
                                        <dns-addr>8.8.8.8</dns-addr>
                                </dns>
                                <ip>
                                        <route>
                                                <next-hop>
                                                        <distance>1</distance>
                                                        <address>1.1.1.1</address>
                                                </next-hop>
                                                <prefix>0.0.0.0/0</prefix>
                                        </route>
                                </ip>
                </vpn-instance>
        </vpn>
</config>
                    """

def connect(host, port, user, password, source):
    conn = manager.connect(host=host,
                           port=port,
                           username=user,
                           password=password,
                           timeout=10,
                           hostkey_verify=False)
    return conn
print(system_config)
vedge_conn = connect('1.1.1.21', 830, 'admin', 'admin', 'candidate')
vedge_conn.edit_config(target='candidate', config=system_config, test_option='set')
vedge_commit_config = vedge_conn.commit()

When i run the above script i hit following error:
    vedge_conn.edit_config(target='candidate', config=system_config, test_option='set')
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 162, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/edit.py", line 67, in request
    return self._request(node)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/rpc.py", line 337, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: Key leaf given twice with different value

**Comment by arslanqadeer** [comment]
Here is the correct XML configuration which i am trying to push: https://pastebin.mozilla.org/9025498

**Comment by einarnn** [comment]
Just a guess, but I'd say that you probably shouldn't be specifying `<vpn-id>` twice. That is probably the key for the `<vpn-instance>`. Maybe you are actually trying to create two `<vpn-instance>` entries?

However, without the underlying schema, it's hard to tell.

**Comment by einarnn** [comment]
However, this isn't an ncclient issue, but a problem with the data passed to the device. The ncclient library is correctly reporting the error returned by the target netconf server.

**Comment by arslanqadeer** [comment]
Yes you are absolutely right my XML was wrong. Thanks
