### ISSUE TITLE
A bug in lambda new_ele and others for python-lxml <=3.2

### ISSUE THREAD

**Issue by ipaoTAT** [ncclient/ncclient#204]
new_ele lambda define as:
```
new_ele = lambda tag, attrs={}, **extra: etree.Element(qualify(tag), attrs, **extra)
```
which means attrs has a default value, but in python-lxml <=3.2, function _initNodeAttributes would update attrs argument. 
```
if extra is not None and extra:
        if attrib is None:
            attrib = extra
        else:
            attrib.update(extra)
```
So, if i run code under:
```
from  ncclient.xml_ import new_ele, to_xml
filter = new_ele("filter", type="subtree")
node = new_ele("get")
print to_xml(node)
```
it will output 
```
<?xml version="1.0" encoding="UTF-8"?><nc:get xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" type="subtree"/>
```
rather than under (**without 'type='subtree''**)
```
<?xml version="1.0" encoding="UTF-8"?><nc:get xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"/>
```
Is it a bug? and can i modify new_ele as:
```
new_ele = lambda tag, attrs=None, **extra: etree.Element(qualify(tag), attrs, **extra)
```
 instead?

**Comment by einarnn** [comment]
The requirements.txt for `ncclient` currently define `lxml>=3.3.0`. Is this also an issue for versions of `lxml` 3.3.0 and above?

**Comment by einarnn** [comment]
No further feedback. Closing issue for now. Please feel free to re-open with more data.
