### ISSUE TITLE
Bad handling in NotificationHandler callback in rpc.py

### ISSUE THREAD

**Issue by einarnn** [ncclient/ncclient#205]
See:

https://github.com/ncclient/ncclient/blob/f734dfc7124a20bf067df1b12c23bba191bcdb89/ncclient/operations/rpc.py#L206-L227

The last `else` is at the level of the `for`. This is bogus, and looks like the code is damaged. If `message-id` is the only attribute of the RPC reply, code will not fail, but if there are any other attributes, then code will probably not work properly. Need to check logic.

**Comment by leopoul** [comment]
I'd like to test that, however, that is a for: else: loop. If no break occurs and the loop ends then "else" statement is reached.
I'll test the patch in any case.
Thanks!
Leo

**Comment by leopoul** [comment]
Also, correct me if I'm wrong or I have missed something, "message-id" is mandatory by RFC, right?

Best,
Leo

**Comment by einarnn** [comment]
Yes, message-id is mandatory for rpc-reply.
