### ISSUE TITLE
"Unexpected session close' to N9k

### ISSUE THREAD

**Issue by micyew** [ncclient/ncclient#208]
I've the following code and it always file with "Unexpected session close". The debug message is below. I can use CLI ssh to send hello from a Linux box. But when comes to ncclient, it always file.

Is there some bug in then ncclient?

`
from ncclient import manager
import logging

def main():

    logging.basicConfig(filename='debug_nxos.log',level=logging.DEBUG)

    with manager.connect(host='192.168.0.33',
                         port=22,
                         username='admin',
                         password='xxxxx',
                         hostkey_verify=False,
                         device_params={'name': 'nexus'},
                         allow_agent=False,
                         look_for_keys=False
                         ) as cisco_manager:
        #for capability in cisco_manager.get_capabilities:
            #print (capability)
        print (cisco_manager)

if __name__ == '__main__':
    main()
`

Debug:
`DEBUG:ncclient.transport.session:<SSHSession(session, initial daemon)> created: client_capabilities=<dict_keyiterator object at 0x0338FD50>
DEBUG:ncclient.transport.ssh:starting thread (client mode): 0x33936b0
DEBUG:ncclient.transport.ssh:Local version/idstring: SSH-2.0-paramiko_2.0.2
DEBUG:ncclient.transport.ssh:Remote version/idstring: SSH-2.0-OpenSSH_6.2 PKIX FIPS
INFO:ncclient.transport.ssh:Connected (version 2.0, client OpenSSH_6.2)
DEBUG:ncclient.transport.ssh:kex algos:['ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] client mac:['hmac-sha1'] server mac:['hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:ncclient.transport.ssh:Kex agreed: diffie-hellman-group1-sha1
DEBUG:ncclient.transport.ssh:Cipher agreed: aes128-ctr
DEBUG:ncclient.transport.ssh:MAC agreed: hmac-sha1
DEBUG:ncclient.transport.ssh:Compression agreed: none
DEBUG:ncclient.transport.ssh:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:ncclient.transport.ssh:Switch to new keys ...
DEBUG:ncclient.transport.ssh:userauth is OK
INFO:ncclient.transport.ssh:Auth banner: b'User Access Verification\n'
INFO:ncclient.transport.ssh:Authentication (password) successful!
DEBUG:ncclient.transport.ssh:[chan 0] Max packet in: 32768 bytes
DEBUG:ncclient.transport.ssh:[chan 0] Max packet out: 32768 bytes
DEBUG:ncclient.transport.ssh:Secsh channel 0 opened.
DEBUG:ncclient.transport.ssh:[chan netconf-subsystem-0] Sesch channel 0 request ok
DEBUG:ncclient.transport.ssh:[chan netconf-subsystem-0] EOF received (netconf-subsystem-0)
DEBUG:ncclient.transport.session:installing listener <ncclient.transport.session.NotificationHandler object at 0x034EC7B0>
DEBUG:ncclient.transport.ssh:[chan netconf-subsystem-0] EOF sent (netconf-subsystem-0)
DEBUG:ncclient.transport.session:installing listener <ncclient.transport.session.HelloHandler object at 0x034EC850>
DEBUG:ncclient.transport.session:queueing <?xml version="1.0" encoding="UTF-8"?><hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:capability:xpath:1.0</capability><capability>urn:ietf:params:netconf:capability:notification:1.0</capability><capability>urn:ietf:params:netconf:capability:validate:1.0</capability><capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability><capability>urn:liberouter:params:netconf:capability:power-control:1.0</capability><capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability><capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</capability><capability>urn:ietf:params:netconf:capability:candidate:1.0</capability><capability>urn:ietf:params:netconf:capability:interleave:1.0</capability><capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:base:1.1</capability></capabilities></hello>
DEBUG:ncclient.transport.session:starting main loop
DEBUG:ncclient.transport.ssh:Broke out of main loop, error=SessionCloseError('Unexpected session close',)
DEBUG:ncclient.transport.session:dispatching error to <ncclient.transport.session.NotificationHandler object at 0x034EC7B0>
DEBUG:ncclient.transport.session:dispatching error to <ncclient.transport.session.HelloHandler object at 0x034EC850>
DEBUG:ncclient.transport.session:discarding listener <ncclient.transport.session.HelloHandler object at 0x034EC850>
DEBUG:ncclient.transport.ssh:EOF in transport thread`

**Comment by cspeidel** [comment]
I was able to repeat this issue with ncclient 0.5.3 and a N9k (C92160YC-X).

**Comment by cspeidel** [comment]
@micyew what version of NXOS are you running?

**Comment by einarnn** [comment]
@micyew, since there has been no further information on this thread I am assuming it is no longer an active issue. Please feel free to reopen if there is still a problem.

**Comment by rajvijay68** [comment]
In my case,
Just using port 830 helped fix this issue.
