### ISSUE TITLE
easy way to format hello messages?

### ISSUE THREAD

**Issue by jensenja** [ncclient/ncclient#217]
I'm attempting to work with some Brocade IronWare devices. They don't seem to like this as a HELLO message:

```
<?xml version="1.0" encoding="UTF-8"?>
    <nc:hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
        <nc:capabilities>
            <nc:capability>urn:ietf:params:xml:ns:netconf:base:1.0</nc:capability>
            <nc:capability>urn:ietf:params:netconf:base:1.0</nc:capability>
        </nc:capabilities>
    </nc:hello>]]>]]>
```

They do however appear to like this:

```
<?xml version="1.0" encoding="UTF-8"?>
    <hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
        <capabilities>
            <capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability>
            <capability>urn:ietf:params:netconf:base:1.0</capability>
        </capabilities>
    </hello>]]>]]>
```

Is there a way to customize the HELLO message format? I worked around this a few years ago by overriding `HelloHandler`'s `build()` method in `transport/session.py` - these hacks still work but are kind of ugly, and they're also causing other methods I want to use ie `get`, `get_config` etc to fail (I'm doing something wrong with the XML handling, I can smell it).

Also is there an easy way to alter the capabilities that ncclient provides to a server before any connection is initiated? I remember you used to be able to assign a list of capabilities to `manager.CAPABILITIES` a few years ago but this appears to no longer be the case. My Brocades also don't appear to like the long capability list that ncclient provides by default and I would like to define my own.

Thanks.

**Comment by jensenja** [comment]
I guess my next question is - would the existing code to facilitate adding third party device support allow me to modify the hello messages used for Brocade switches running NetIron? The issue seems to be that `new_ele()` calls `qualify()` in `ncclient.xml_` and `qualify()` just defaults to using `urn:ietf:params:xml:ns:netconf:base:1.0` with a `nc` namespace prefix. I'd also need https://github.com/ncclient/ncclient/issues/176 to be addressed as well since the sub-elements don't inherit from the parent namespace and there's currently no way to set their namespace to `None`.

**Comment by einarnn** [comment]
The first hello message variant is incorrect XML as the XML namespace declaration, `xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"`, does not define the prefix `nc` that is used elsewhere. Thus Brocade IronWare devices were correct to replace that format of hello message if it was produced by ncclient.

However, here is a sample of the current hello messages produced by the latest ncclient library with a default device handler, which is now correct with respect to namespacing:

```
<?xml version="1.0" encoding="UTF-8"?>
<nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <nc:capabilities>
    <nc:capability>urn:ietf:params:netconf:base:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:base:1.1</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:writable-running:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:candidate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:startup:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:xpath:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:notification:1.0</nc:capability>
    <nc:capability>urn:liberouter:params:netconf:capability:power-control:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:interleave:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:with-defaults:1.0</nc:capability>
  </nc:capabilities>
</nc:hello>
```

Thus this issue doesn't seem to still be active. Closing.
