### ISSUE TITLE
Any plan for a new release of ncclient ?

### ISSUE THREAD

**Issue by sbadia** [ncclient/ncclient#227]
Hi,

Thanks for ncclient !

I'm wondering if a new release is planed, the latest release was made in [december 2016](https://github.com/ncclient/ncclient/commit/633d178e68d54535fb4b934b4f62474463024c15) and test suite didn't pass anymore on 0.5.3 due to a [paramiko change](https://github.com/ncclient/ncclient/issues/218), refs: https://bugs.debian.org/894432

Thanks in advance!

**Comment by einarnn** [comment]
Only testing run under Python 2.6 fails.

**Comment by sbadia** [comment]
Hi @einarnn !

Yes, indeed.
However tests doesn't run on the 0.5.3 tag but on master and we have [±53 additional commits](https://github.com/ncclient/ncclient/compare/v0.5.3...master) on it.

**Comment by attila123** [comment]
+1 for more frequent releases (e.g. after significant bugfixes).
"If it hurts, do it more often."

**Comment by einarnn** [comment]
I've pinged @leopoul to see what we can perhaps do.

Cheers,

Einar

**Comment by einarnn** [comment]
Targeting a 0.5.4 to be released approximately mid-July 2018.

**Comment by sbadia** [comment]
@einarnn thanks !

**Comment by einarnn** [comment]
0.5.4 went out, followed by 0.6.0 with an incompatible API change to account for Python3 reservation of `async` as a keyword.
