### ISSUE TITLE
Do we need to maintain ncclient for Python 2.6 still?

### ISSUE THREAD

**Issue by einarnn** [ncclient/ncclient#228]
The current test suite fails when run with Python 2.6 due to changes in Paramiko. Given Python 2.6 is no longer updated, should we still maintain testing for it? Or disable it?

**Comment by jwwilcox** [comment]
People who still use Python 2.6 also probably don't update their development libraries like ncclient often either.

**Comment by last-partizan** [comment]
I'm pretty sure it's time to drop python 2.6.

**Comment by hugovk** [comment]
Drop it to reduce the maintenance burden and more modern Python features to be used.

It's been unsupported by the core Python team for 4.5 years, and no longer receives security updates.

It's also little used. Here's the pip installs for ncclient from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  64.10% |          7,802 |
| 3.5            |  19.03% |          2,316 |
| 3.6            |   9.82% |          1,195 |
| 3.4            |   6.93% |            844 |
| 2.6            |   0.07% |              8 |
| 3.7            |   0.05% |              6 |

Source: `pypinfo --start-date -42 --end-date -12 --percent --pip --markdown ncclient pyversion`

**Comment by glennmatthews** [comment]
Drop it.

**Comment by hugovk** [comment]
Please see PR https://github.com/ncclient/ncclient/pull/233.
