### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 778966: ordinal not in range(128)

### ISSUE THREAD

**Issue by lent1** [ncclient/ncclient#231]
Hello,

I'm trying to use ncclient with a PulseSecure gateway.
My test is pretty simple:
```from ncclient import manager
from ncclient import manager
import logging

logging.basicConfig(level=logging.DEBUG)
with manager.connect(host=host, port=22, username=username, hostkey_verify=False, password=passwd, device_params={'name':'default'}) as m:
    c = m.get_config(source='running').data_xml
```
The following error occured:
```
DEBUG:ncclient.transport.ssh:parsing netconf v1.0
DEBUG:ncclient.transport.ssh:Broke out of main loop, error=UnicodeEncodeError('ascii', u'<nc:rpc-reply message-id="urn:uuid:b7872541-d4c0-4ed7-8a62-17823c0e9742" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">\n    <data>\n        <configuration xmlns="http://xml.juniper.net/ive-sa/8.2R7.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" iveData="2708" saData="2602"> .....  </configuration>\n    </data>\n</nc:rpc-reply>', 778966, 778967, 'ordinal not in range(128)')
DEBUG:ncclient.transport.session:dispatching error to <ncclient.transport.session.NotificationHandler object at 0x7fb353452750>
DEBUG:ncclient.transport.session:dispatching error to <ncclient.operations.rpc.RPCReplyListener object at 0x7f4810044210>
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/virtualenv/local/lib/python2.7/site-packages/ncclient/manager.py", line 214, in __exit__
    self.close_session()
  File "/virtualenv/local/lib/python2.7/site-packages/ncclient/manager.py", line 162, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/virtualenv/local/lib/python2.7/site-packages/ncclient/manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/virtualenv/local/lib/python2.7/site-packages/ncclient/operations/session.py", line 28, in request
    return self._request(new_ele("close-session"))
  File "/virtualenv/local/lib/python2.7/site-packages/ncclient/operations/rpc.py", line 326, in _request
    raise self._error
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 778966: ordinal not in range(128)
>>> DEBUG:ncclient.transport.ssh:EOF in transport thread
```

I know that the reply has a lot of accented word as well as Japanese and Chinese characters.

I'm trying to find the correct way to deal with this encoding issues (btw i'm in python 2.7.12).

Has anyone already faced this kind of problem?

Thanks

**Comment by einarnn** [comment]
Hi,

Can you enable debug logging for ncclient.transport.ssh?

Note that in RFC 6241 (https://tools.ietf.org/html/rfc6241#section-3) we see:

  All NETCONF messages MUST be well-formed XML, encoded in UTF-8
  [RFC3629].  If a peer receives an <rpc> message that is not well-
  formed XML or not encoded in UTF-8, it SHOULD reply with a
  "malformed-message" error.  If a reply cannot be sent for any reason,
  the server MUST terminate the session.

First step would be to use the debug logging suggested above to determine if the returned data is UTF-8-compliant. If it isn’t, the device vendor may need to comment.

Cheers,

Einar

**Comment by einarnn** [comment]
Can you enable debug logging for ncclient.transport.ssh?

Note that in RFC 6241 (https://tools.ietf.org/html/rfc6241#section-3) we see:

```
  All NETCONF messages MUST be well-formed XML, encoded in UTF-8
  [RFC3629].  If a peer receives an <rpc> message that is not well-
  formed XML or not encoded in UTF-8, it SHOULD reply with a
  "malformed-message" error.  If a reply cannot be sent for any reason,
  the server MUST terminate the session.
```

First step would be to use the debug logging suggested above to determine if the returned data is UTF-8-compliant. If it isn’t, the device vendor may need to comment.

Cheers,

Einar

**Comment by lent1** [comment]
Hello,

to avoid this issue, i switched to python 3.7.

I think you're right, the rpc reply is not correctly encoded by the device.

This issue can be closed.

Thanks for your reply.
