### ISSUE TITLE
replace old style print-s in the examples

### ISSUE THREAD

**Issue by attila123** [ncclient/ncclient#236]
Hi,
Great stuff, however the examples are full of old style print-s ("print whatever" instead of "print(whatever)"). These do not work with recent python 3 (plus having used other programming languages these are plain ugly and WTF-ish (not sure why python introduced the old-style print in the first place)). Plus these confuse PyCharm formatting - should you try to copy-paste such code to PyCharm.

I think **logging.info() should be the best replacement for print-s**. Initialization of logging is easy with logging.basicConfig(), and **it would also make it easy for the users to change the log level to DEBUG to see ncclient debug logs if needed while playing with the examples**.

I would do a PR for this if needed, and if my proposal is acceptable by the author(s) and/or maintainer(s).

Example for basicConfig:
```
import logging
import sys

LOG_FORMAT = '%(asctime)s %(levelname)s %(filename)s:%(lineno)d %(message)s'
logging.basicConfig(stream=sys.stdout, level=logging.INFO, format=LOG_FORMAT)

logging.info('Hello %s', 'world!')
```

**Comment by attila123** [comment]
What do you devs think about this?
@leopoul ?

**Comment by attila123** [comment]
Dear recent commiters,
@einarnn @hugovk @jwwilcox @cspeidel ,
could you please comment on this issue, would you merge my MR if I implement this?
Sorry for the spam!

**Comment by hugovk** [comment]
I don't have merge rights, but something along those lines sounds sensible.

Or add `from __future__ import print_function, unicode_literals` and convert `print x` to `print(x)`. https://github.com/asottile/pyupgrade can do the conversion after the `imports` are added.

**Comment by cspeidel** [comment]
I don't have merge rights either, but you may want to consider these recommendations (NullHandler) for library logging in Python:
https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

The requests library has a good example of importing for both Python 2.7 and 3+
https://github.com/requests/requests/blob/991e8b76b7a9d21f698b24fa0058d3d5968721bc/requests/__init__.py

**Comment by einarnn** [comment]
If there are still examples of non-compliant code with respect to print functions, any PR would be looked at by me for sure. It looks like the only py2-style print statements are in example code, though. Is there anything else that is concerning you?

Cheers,

Einar

**Comment by attila123** [comment]
Hi @einarnn, yes, my intention was to improve the example code (examples/juniper), so that they would be easier to run and easier understood by new users (and easier to report any issues regarding them - if any). Please check https://github.com/ncclient/ncclient/pull/243. There is some coverage decrease reported, but I cannot figure out coveralls.io, plus I am not sure why there is any change at all when I only modified example code.
Also, sorry for the lot of code formatting changes in the same commit! I should have separated them to a separate commit.
