### ISSUE TITLE
confirm-commit and check fails on junos devices

### ISSUE THREAD

**Issue by ganeshrn** [ncclient/ncclient#238]
Invoking `commit()` with confirm timeout for Juniper devices result in executing in below xml on device
```
  <?xml version="1.0" encoding="UTF-8"?>
  <nc:commit xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  	<nc:confirmed/>
  	<nc:confirm-timeout>5</nc:confirm-timeout>
  	<nc:log>configured by junos_config</nc:log>
  </nc:commit>
```
This rpc call does not work for confirm commit as seen from device logs after exectung the rpc
```
user@junos# show | compare rollback ?
Possible completions:
  0                    2018-06-14 04:59:12 UTC by user via netconf
  1                    2018-06-14 04:59:07 UTC by user via netconf commit confirmed, rollback in 0mins
```

As per Juniper documentation here https://www.juniper.net/documentation/en_US/junos/topics/reference/tag-summary/junos-xml-protocol-commit-configuration.html the right xml tag for confirm commit and other features to work properly is `commit-configuration`.
Executing below xml with `commit-configuration` work as expected
```
  <?xml version="1.0" encoding="UTF-8"?>
  <nc:commit-configuration xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  	<nc:confirmed/>
  	<nc:confirm-timeout>5</nc:confirm-timeout>
  	<nc:log>configured by junos_config</nc:log>
  </nc:commit-configuration>
```
Device logs
```
  user@junos# show | compare rollback ?
Possible completions:
  0                    2018-06-14 05:06:58 UTC by root via other
  1                    2018-06-14 05:01:46 UTC by user via netconf commit confirmed, rollback in 5mins
```

Also, check mode handling is not supported in current Juniper implementation of `commit` as described by Juniper documentation

**Comment by attila123** [comment]
@ganeshrn thanks for reporting this and providing a fix. I am new to netconf and ncclient and even Junos, and I also just bumped to this issue. I guess this is the same issue described here: https://github.com/ncclient/ncclient/issues/234
Sadly, it seems to mean that Junos does not comply with the netconf protocol for confirmed commit? See the first example at netconf RFC here: https://tools.ietf.org/html/rfc6241#section-8.4.5 .
Unfortunately Junos also does not comply with the units of confirm-timeout, in the Junos documentation you linked:
"<confirm-timeout>—Specify the number of minutes for which the configuration remains active when the <confirmed/> tag is enclosed in the <commit-configuration> tag element."
But the netconf protocol defines it in seconds, see https://tools.ietf.org/html/rfc6241#section-8.4.5
Also, the ncclient library following the ncclient standard and use seconds for confirmed-commit, see http://ncclient.readthedocs.io/en/latest/manager.html#ncclient.manager.Manager.commit
So could you please modify your fix to use seconds? Something like math.ceil(timeout / 60) should work.

**Comment by attila123** [comment]
I implemented this at https://github.com/attila123/ncclient/commit/3bc35e5c2e7ef6496041415517ad49b5d08a93ec
I will try to update the tests and submit a pull request.

**Comment by attila123** [comment]
Update: I deleted my original commit and created this one:
https://github.com/attila123/ncclient/commit/834c9861cfdefe530faae809f881bfe24bc03f92
This also updates the unit tests, and removes the namespace for commit-configuration (the Junos link does not mention that it should have any namespace).

**Comment by attila123** [comment]
One more commit for python2 compatibility fix, and now the PR is green: https://github.com/ncclient/ncclient/pull/241

**Comment by a-v-popov** [comment]
From original post  it seems that <commit> on Junos is RFC-compliant - it was asked to rollback in 5 seconds and it did as requested.
What was the goal of switching to vendor proprietary extension?

**Comment by einarnn** [comment]
@a-v-popov, can you confirm the payloads used with Junos? If Juniper have now implemented RFC compliant support, it could be that this vendor extension could be retired, but if older versions still need the vendor extension implemented by @ganeshrn, maybe it should be left in place?

@ganeshrn -- any comments?

Cheers,

Einar
