### ISSUE TITLE
How to KeepAlive 

### ISSUE THREAD

**Issue by zgysc** [ncclient/ncclient#262]
I need to connect device permanently， could you give me some advise？ thanks

**Comment by zgysc** [comment]
@shikhar  please help me with the issue

**Comment by zgysc** [comment]
@einarnn  please help me

**Comment by einarnn** [comment]
This is not really an ncclient issue, but more for the underlying SSH transport. As such, once you have successfully connected to the device and obtained a Manager object, `m`, you could try something like:

```
m._session._transport.set_keepalive(10.0)
```

This sets a keepalive time of 10 seconds on he underlying Paramiko transport used by ncclient. Be aware that the `_`-prepended variables are considered private and thus _may_ change in the future.

**Comment by zgysc** [comment]
@einarnn  thank you very much, I will try it
