### ISSUE TITLE
Is there an option to omit? <?xml version="1.0" encoding="UTF-8"?>

### ISSUE THREAD

**Issue by nastyfast** [ncclient/ncclient#264]
When using ncclient all rpc messages sent to the netconf server start with `<?xml version="1.0" encoding="UTF-8"?>`

I was wondering if there is an option to omit this from the rpc?
For some reason Pulse Secure software is having issues with this. (Works perfectly with all other vendors I have tested)

Example:

Does not work:
```<?xml version="1.0" encoding="UTF-8"?>
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:d66c8ded-1735-44c9-8903-25239a57f2e6">
<nc:get-active-users/>
</nc:rpc>
```

Works:

```
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:d66c8ded-1735-44c9-8903-25239a57f2e6">
<nc:get-active-users/>
</nc:rpc>
```

**Comment by einarnn** [comment]
Closing this issue as there isn't an issue with `ncclient` in this case, more with the "Pulse Secure" software, and `ncclient` provides the device handler extension point to allow customization.

**Comment by nastyfast** [comment]
Thank you for the help @einarnn I am first going to try and see if I can work with Pulse Secure to see if I can get them to fix the software, If they will not I will likely create my own Handler.
