### ISSUE TITLE
Subscriptions and Notifications - 

### ISSUE THREAD

**Issue by Sentinel07** [ncclient/ncclient#275]
I am using following api to fetch notifs & dump to a file. The problem is I am not receiving as many notifs as sent by the network-device. Since this is ssh connection, there is no possibility of notif-drops. How can i debug this on ncclient lib? Is there any notif-receive-counter available?

no = session.take_notification(block=True, timeout=None)
raw_string = no.notification_xml
pretty_string = xmltodict.unparse(xmltodict.parse(raw_string), pretty=True)
\# dump pretty_string to file

**Comment by einarnn** [comment]
We don't have a counter available, but you can enable verbose debugs. See an example at:

https://github.com/CiscoDevNet/ncc/blob/master/ncc-event-listener.py#L36-L41

Cheers,

Einar
