### ISSUE TITLE
enhance rpc.py

### ISSUE THREAD

**Issue by zgysc** [ncclient/ncclient#284]
In rpc.py,  line221
 why not use this: 
**rpc = self._id2rpc.pop(id)**
instead of
**rpc = self._id2rpc[id]** 

I think you don't have to write this :   **del self._id2rpc[id]**

what's more， Line168   

 

> @property
>     def ok(self):
>         "Boolean value indicating if there were no errors."
>         **return not self.errors** # empty list => false

I think it should also call "**self.parse()**" before "**return not self.errors**"

**Comment by zgysc** [comment]
@adamcubel @shikhar    I am not sure about my issue, pls check it

**Comment by einarnn** [comment]
Yes, self.parse should be called in the ok method. I have generated a pull request for that change, #286.

Not sure about using `pop` vs lookup + `del`. Current behavior will leave the RPC id in `_id2rpc` if there is an exception thrown by `rpc.deliver_reply(raw)`. If we use `pop` instead, then `_id2rpc` will already have been modified if an exception is thrown by `rpc.deliver_reply(raw)`. This will change existing bahavior, and I would recommend against that unless and until a detailed analysis of the implications has been done.
