### ISSUE TITLE
Receive notifications in my Manager with SessionListener

### ISSUE THREAD

**Issue by alarrosa5** [ncclient/ncclient#290]
Someone could help me to connect a manager with a session listener. Now I have this code but it does not compile:

```
def demo(host, map, ip):
        with manager.connect(host=host, port=830, username="netconf", password="netconf",hostkey_verify=False) as m:
             for c in m.server_capabilities:
                   print (c)
             c = m.get_config(source='running').data_xml>         
             assert(":validate" in m.server_capabilities)
             snippet = etree.tostring(etree.parse(map.get(ip)[0]), pretty_print=True)
             m.edit_config(target='running', config=snippet, test_option='test-then-set')
             m.create_subscription()
             q = Queue()
             listener = NotificationHandler(q)
             session = Session(m.server_capabilities)
             session.add_listener(listener)
             notif = q.get_nowait()
             print notif
```

I need a simple example of receiving notification

**Comment by einarnn** [comment]
Antonio,

Even if it did compile, this code wouldn't work for at least two reasons:

- The `Session` you have created is not connected to any netconf server
- You're calling `get_nowait()` on a queue, so that would only give you a notification if one happened to have arrived on the session.

Currently, as a client outside of the ncclient library, it is not possible to add a notification listener in this way as the underlying session is intended to be private. You could temporarily violate this, and do something like:

```
from ncclient import manager
from ncclient.transport.session import SessionListener
import time

class MyNotifactionHandler(SessionListener):
    def callback(self, root, raw):
        tag, _ = root
        if tag == qualify('notification', NETCONF_NOTIFICATION_NS):
            #### put your logic here ####
            print(raw)

def demo(host, map, ip):
    with manager.connect(host=host, port=830, username="netconf", password="netconf", hostkey_verify=False) as m:
        # note that using m._session breaks the Manager abstraction
        # and thus may not be supported in the future
        m._session.add_listener(MyNotificationHandler())
        m.create_subscription(stream_name='NETCONF')
        while True:
            time.sleep(5)
            print('tick...')
```

I haven't tested this code, so some debugging may be required.

Cheers,

Einar

**Comment by einarnn** [comment]
I should add that I do not really recommend this approach. The notification handler in this case would be executed on the ncclient transport thread, and any operations you performed there would have the possibility of deadlock. E.g. if you executed a synchronous `<edit-config>`.

A better approach is to use a separate listener thread that uses the `take_notification` function of the ncclient manager object.

Cheers,

Einar

**Comment by einarnn** [comment]
No fixes required to `ncclient`.
