### ISSUE TITLE
poor performance of netconf

### ISSUE THREAD

**Issue by yusong0926** [ncclient/ncclient#295]
I just found some of the netconf rpc calls take more than 20 seconds to finish. I am thinking if that's the problem of netconf and xml.
when you run netconf over ssh in command line, in the response of a rpc call, each xml tag is output on it's own line there is very poor buffering happing and it's flushing and delivering the stream to the client every new line.
not sure if that's the problem for the poor performance  I got.

**Comment by einarnn** [comment]
Please try enabling debug for the rpc and ssh ncclient modules and running your commands, and post the results here.

**Comment by einarnn** [comment]
No further information provided. Closing this issue for now. Please feel free to reopen if more data becomes available!
