### ISSUE TITLE
sending traceroute rpc with _request method issue

### ISSUE THREAD

**Issue by brunoonovais** [ncclient/ncclient#298]
hi team...been trying to send a simple traceroute through ncclient. I was able to find an example on cisco community that works (initially made for ping: https://community.cisco.com/t5/yang-development-kit-ydk/ping-rpc-error-with-cisco-ios-xr-ping-act-module/m-p/3484581), however I was trying to understand how to make it work without having to override the _wrap function for the RPC class as well as the REPLY_CLS class. not sure how those relate.
I was able to create the connection and send the request, but i believe because the router can't find the namespace, it doesn't understand the "traceroute" request i am giving.

Here's an example of what I am getting:

# full rpc in text, no override of RPC or REPLY_CLS:

```
    filter="""<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101">
<traceroute xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-traceroute-act">
        <ipv4>
            <destination>
                10.0.0.2
            </destination>
        </ipv4>
</traceroute>
</rpc>
    """

...

    with m.connect(**d, hostkey_verify=False,look_for_keys=False, allow_agent=False) as con:
        print(con)

        rpc = RPC(con._session, con._device_handler)
        reply = rpc._request(lxml.etree.fromstring(filter))
        print(reply)

```

the below gives me the following rpc response:

```
<?xml version="1.0"?>
<rpc-reply message-id="urn:uuid:3c16d6cf-4e92-476a-aad2-55da641b95a2" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <rpc-error>
  <error-type>protocol</error-type>
  <error-tag>unknown-namespace</error-tag>
  <error-severity>error</error-severity>
  <error-info>
   <bad-element>rpc</bad-element>
   <bad-namespace>urn:ietf:params:xml:ns:netconf:base:1.0</bad-namespace>
  </error-info>
 </rpc-error>
</rpc-reply>
```

I have tried different variations, but basically the only way i can make it work, is by using the example mentioned in the link above. appreciate any thoughts on what i am doing wrong.

thanks
Bruno

**Comment by brunoonovais** [comment]
Well, figured out what I was doing wrong. I omitted the rpc tag and so my filter looks like this:

```
    filter="""
 <traceroute xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-traceroute-act">
        <ipv4>
            <destination>
                10.0.0.2
            </destination>
        </ipv4>
 </traceroute>
    """
```

it works now with the following example code:

```
    with m.connect(**d, hostkey_verify=False,look_for_keys=False, allow_agent=False) as con:

        rpc = RPC(con._session, con._device_handler)
        reply = rpc._request(lxml.etree.fromstring(filter))
        print(reply)
```

**Comment by dataopensystem** [comment]
I was looking  up for this!!

**Comment by dataopensystem** [comment]
Based on in your response, It's also possible  to use:
from lxml.etree import fromstring

... abbreviated...

  with m.connect(**d, hostkey_verify=False,look_for_keys=False, allow_agent=False) as con:
        reply = m.dispatch(fromstring(filter_))
        print(reply)
