### ISSUE TITLE
error: Failed to apply configuration changes to device.\nerror: Wrong parameter found.

### ISSUE THREAD

**Issue by menkeyi** [ncclient/ncclient#300]
When the Huawei firewall occasionally delivers the configuration, it will encounter this error message. After running it once, it can be successfully issued. I don't know why?

**Comment by einarnn** [comment]
Try enabling debug logging on the following modules:

- 'ncclient.transport.ssh’
- 'ncclient.transport.session'
- 'ncclient.operations.

This should give you more information.

**Comment by einarnn** [comment]
Closing this issue as no further feedback or issues raised.
