### ISSUE TITLE
Incomplete get_config documentation

### ISSUE THREAD

**Issue by jmwri** [ncclient/ncclient#304]
The docs @ https://ncclient.readthedocs.io/en/latest/manager.html?highlight=get_config#ncclient.manager.Manager.get_config are missing the `with_defaults` parameter as per https://github.com/ncclient/ncclient/blob/master/ncclient/operations/retrieve.py#L116.

**Comment by einarnn** [comment]
Unfortunately, readthedocs.io is not regularly maintained at this time. With respect to enhancements, please feel free to suggest documentation updates via a pull request!! :)

**Comment by fredgan** [comment]
Hi @einarnn , I think this issue can be closed :)
