### ISSUE TITLE
ssh_config doesn't make any difference

### ISSUE THREAD

**Issue by horseinthesky** [ncclient/ncclient#305]
Hello.
I'm working with a lot of network devices and using `ncclient` to get/put configugation to them.
Now I need to use a jumphost to get to some of these devices. I have `~/.ssh/config` file which describes all the appropriate options
```
Host somenetworkdevice
  ProxyCommand ssh -W %h:%p jumphost
```

It works from SHELL but `ncclient` doesn't use this file even if I set `ssh_config=True`:
```
with manager.connect(
    host=host,
    port=22,
    ssh_config=True,
    username='username',
    hostkey_verify=False,
    device_params={'name': 'junos'}
) as m:
```
It just failes with this:
```
Traceback (most recent call last):
  File "./JunOS_get.py", line 26, in <module>
    timeout=5
  File "/usr/local/lib/python3.6/dist-packages/ncclient/manager.py", line 163, in connect
    return connect_ssh(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/ncclient/manager.py", line 128, in connect_ssh
    session.connect(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/ncclient/transport/ssh.py", line 384, in connect
    raise SSHError("Could not open socket to %s:%s" % (host, port))
ncclient.transport.errors.SSHError: Could not open socket to <mydeviceip>:22
```

Could you pls help me to tell `ncclient` to use SSH config file.

I also need this ability for Ansible (2.7.7) `netconf_config` module. 
I tried to use
```
ansible_netconf_ssh_config = True
```
or
```
[netconf_connection]
ssh_config = 1
```
in `ansible.cfg`

and `export ANSIBLE_NETCONF_SSH_CONFIG=1` environment variable but nothing works.

Ansible failes with this:
```
fatal: [cloud-m9-b1.cloud.yandex.net]: FAILED! => {"msg": "Could not open socket to cloud-m9-b1.cloud.yandex.net:22"}
```

As soon as Ansible uses `ncclient` I guess these two should be connected somehow. But now neither `ncclient` nor the Ansible uses SSH config file.

Btw I'm on Ubuntu 18.04.1 LTS.

**Comment by markafarrell** [comment]
@horseinthesky is `jumphost` a reference to another host in your ssh config file?

I don't believe that paramiko looks up the host information for the proxy command.

Try specifying the entire proxy command e.g.

```
Host somenetworkdevice
    ProxyCommand ssh -W %h:%p username@jumphost.fqdn.com -i /path/to/key.pem
```

Also, depending on if you are using the pip version of ncclient or not you may need to explicitly set the netconf port you are using in the proxy command (it you are using a port other than 22).

e.g.

```
Host somenetworkdevice
    ProxyCommand ssh -W %h:830 username@jumphost.fqdn.com -i /path/to/key.pem
```
For ansible you will want to set either:
* export ANSIBLE_NETCONF_SSH_CONFIG=1
* ssh_config = 1 in the [netconf_connection] section of ansible.cfg

**Comment by horseinthesky** [comment]
@markafarrell Thank you!
I messed up with `ProxyJump` which is not parsed by Paramiko.
`ProxyCommand` works with `ncclient` with `ssh_config=True` option perfectly fine.

Ansible is different. I set up 
```
[netconf_connection]
ssh_config = 1
```
but it works for one group of hosts but doesn't work for another.

**Comment by einarnn** [comment]
@horseinthesky, is this still judged by you to be a problem with ncclient? Or is it an Ansible issue?

**Comment by horseinthesky** [comment]
> @horseinthesky, is this still judged by you to be a problem with ncclient? Or is it an Ansible issue?

No, `ncclient` has nothing to do with the issue. It was a Paramiko to blame.

And there is an Ansible issue which is described here.
https://github.com/ansible/ansible/issues/54859
