### ISSUE TITLE
pip install broken v0.6.5 because test-requirements not found

### ISSUE THREAD

**Issue by davidban77** [ncclient/ncclient#321]
Hello,

It seems that pip fails installation because is not finding the `test-requirements.txt`.

Here is the error shown:
```
pip install --no-cache-dir ncclient
Collecting ncclient
  Downloading https://files.pythonhosted.org/packages/d2/1f/4333dba7d63bebb27232d0cd5d2173ed14615f50c92a41479b86aab3217d/ncclient-0.6.5.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 2.3MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/22/3rnqkrbj7g5242vvqjkpkfx40000gn/T/pip-install-q5ipqk1a/ncclient/setup.py", line 37, in <module>
        test_req_lines = [line.strip() for line in open("test-requirements.txt").readlines()]
    FileNotFoundError: [Errno 2] No such file or directory: 'test-requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/22/3rnqkrbj7g5242vvqjkpkfx40000gn/T/pip-install-q5ipqk1a/ncclient/
```

My python is 3.7
```
python --version
Python 3.7.3
```

**Comment by nlopez** [comment]
I ran into this with Python 2.7.5 when installing ncclient as an eventual dependency of [napalm-ansible](https://github.com/napalm-automation/napalm-ansible) I've worked around it with a `ncclient<0.6.5` requirements constraint for now.

**Comment by sean-kang** [comment]
I am seeing the same problem. It broke one of our CI/CD pipeline. I'm running Python 3.6.8.

**Comment by sseaky** [comment]
same problem on python 3.7.2. 
"pip install ncclient==0.6.4" works fine.

**Comment by svarshaa28** [comment]
Same issue  with python 2.7 . 

 pip install netconf-console
Collecting netconf-console
  Downloading https://files.pythonhosted.org/packages/c4/fa/a7997d9f813d71c0d1caeaea33e7e55bc9a223305a91fc8345dde36d96d6/netconf_console-2.1.1-py2.py3-none-any.whl
Collecting ncclient>=0.5.2 (from netconf-console)
  Downloading https://files.pythonhosted.org/packages/d2/1f/4333dba7d63bebb27232d0cd5d2173ed14615f50c92a41479b86aab3217d/ncclient-0.6.5.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 292kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wxx7IM/ncclient/setup.py", line 37, in <module>
        test_req_lines = [line.strip() for line in open("test-requirements.txt").readlines()]
    IOError: [Errno 2] No such file or directory: 'test-requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wxx7IM/ncclient/

**Comment by einarnn** [comment]
All, thanks for the heads up, and apologies for the broken 0.6.5 release. It has been pulled, and 0.6.6 is now live.
