### ISSUE TITLE
Only the first error's severity is checked in replies

### ISSUE THREAD

**Issue by devicenull** [ncclient/ncclient#326]
I have a juniper device that's returning multiple rpc-error items in [response.txt](https://github.com/ncclient/ncclient/files/3281846/response.txt) to a commit.  Of these, the first one is a warning, and the subsequent ones are errors.

However, it looks like _request only looks at one error when deciding to raise an error or not:
https://github.com/ncclient/ncclient/blob/master/ncclient/operations/rpc.py#L340

Should this be looking at the entire contents of  RPCReply._errors instead?

**Comment by einarnn** [comment]
As far as I can tell, it should look at all the errors returned. When an `rpc-reply` is parsed, the code [here](https://github.com/ncclient/ncclient/blob/master/ncclient/operations/rpc.py#L153-L157) should add all the errors to a list. The [code you pointed at ](https://github.com/ncclient/ncclient/blob/master/ncclient/operations/rpc.py#L340) looks at a boolean to check if there was **any** error, and then processes the list of errors [here](https://github.com/ncclient/ncclient/blob/master/ncclient/operations/rpc.py#L58-L76) while creating an `RPCError` object, including setting the severity of the "highest" `rpc-error` as the severity of the exception raised. You _should_ be able to look at the entire set of errors in the exception object by iterating the exception object's member variable `errors`.

If this is not the case, please provide some sample on-the-wire data.

Cheers,

Einar

**Comment by einarnn** [comment]
@devicenull, as there has been no further dialog on this issue I'm assuming it is resolved as I have noted above. Is this is not the case, feel free to reopen the issue!

Cheers,

Einar
