### ISSUE TITLE
Using concurrent/threating with ncclient

### ISSUE THREAD

**Issue by metabsd** [ncclient/ncclient#335]
I am currently trying to use the python 3 concurrent library to be able to receive some of the hundreds switch configuration.  As soon as I use several worker at the same time I do not receive any more results.  I would like to know if you think it's possible to connect to several switches at the same time with the ncclient library.

 Thank you!

**Comment by einarnn** [comment]
@metabsd, can you provide a runnable sample of how you are doing this?

**Comment by metabsd** [comment]
There is nothing wrong with NCCLIENT. I figure out how to fix it. It's about my logic. Thx!
