### ISSUE TITLE
not a valid URI

### ISSUE THREAD

**Issue by shade999** [ncclient/ncclient#340]
lxml.etree.XMLSyntaxError: xmlns: 'ODM://flash:/custom.odm//show_ip_interface_brief' is not a valid URI, line 1, column 349

The error appears when I change an ODM fornat on cisco device to custom. "format global flash:/custom.odm"
If I try to exchange inrormation through pure ssh, it works well. 
There is one differense in deviсe response. 
<ShowIpInterfaceBrief xmlns="ODM://built-in//show_ip_interface_brief">
<ShowIpInterfaceBrief xmlns="ODM://flash:/custom.odm//ShowIpInterfaceBrief">

**Comment by einarnn** [comment]
Can you share your full payload?

Cheers,

Einar

**Comment by shade999** [comment]
Hello Einar,

Recuest:
<?xml version="1.0" encoding=\"UTF-8\"?>
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
    <get>
       <filter>
          <config-format-text-cmd>
             <text-filter-spec> | include None </text-filter-spec>
          </config-format-text-cmd>
          <oper-data-format-xml>
             <show>ip interface brief</show>
          </oper-data-format-xml>
       </filter>
    </get>
 </rpc>]]>]]>
 
Recponce with byild in odm (pure ssh):
<?xml version="1.0" encoding="UTF-8"?><rpc-reply message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><data><cli-config-data><cmd></cmd></cli-config-data><xml-oper-data><item><show>ip interface brief</show><response><ShowIpInterfaceBrief xmlns="ODM://built-in//show_ip_interface_brief">
    <SpecVersion>built-in</SpecVersion>
    <IPInterfaces>
      <entry>
        <Interface>Te0/0/0</Interface>
        <OK>YES</OK>
        <Method>NVRAM</Method>
        <Status>administratively down</Status>
        <Protocol>down</Protocol>
      </entry>
	...
	</IPInterfaces>
  </ShowIpInterfaceBrief></response></item></xml-oper-data></data></rpc-reply>]]>]]>

Responce with custom odm (pure ssh):
<?xml version="1.0" encoding="UTF-8"?><rpc-reply message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><data><cli-config-data><cmd></cmd></cli-config-data><xml-oper-data><item><show>ip interface brief</show><response><ShowIpInterfaceBrief xmlns="ODM://flash:/custom.odm//show_ip_interface_brief">
    <SpecVersion>built-in</SpecVersion>
    <IPInterfaces>
      <entry>
        <Interface>Te0/0/0</Interface>
        <OK>YES</OK>
        <Method>NVRAM</Method>
        <Status>administratively down</Status>
        <Protocol>down</Protocol>
      </entry>
	...
	</IPInterfaces>
  </ShowIpInterfaceBrief></response></item></xml-oper-data></data></rpc-reply>]]>]]>

Recponce with byild in odm (ncclient): there is no differense exept in message-id.
Responce with custom odm (ncclient):
Traceback (most recent call last):
  File "./nc_asr.py", line 21, in <module>
    result = m.get(netconf_filter)
  File "/home/cisco/Dev/cisco/lib/python3.6/site-packages/ncclient/manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/home/cisco/Dev/cisco/lib/python3.6/site-packages/ncclient/operations/retrieve.py", line 91, in request
    return self._request(node)
  File "/home/cisco/Dev/cisco/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 339, in _request
    self._reply.parse()
  File "/home/cisco/Dev/cisco/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 148, in parse
    root = self._root = to_ele(self._raw, huge_tree=self._huge_tree) # The <rpc-reply> element
  File "/home/cisco/Dev/cisco/lib/python3.6/site-packages/ncclient/xml_.py", line 124, in to_ele
    return x if etree.iselement(x) else etree.fromstring(x.encode('UTF-8'), parser=_get_parser(huge_tree))
  File "src/lxml/etree.pyx", line 3234, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: xmlns: 'ODM://flash:/custom.odm//show_ip_interface_brief' is not a valid URI, line 1, column 349

**Comment by einarnn** [comment]
Ok, this is a bug in the output produced by the Cisco device. You may wish to report that bug to Cisco via TAC or your account team, as the ODM infrastructure should produce valid namespace URIs.

However, to unblock you, I think this can be worked around by monkey-patching the XML parser used by ncclient. This can be accomplished something like the code below, which is extracted and from `xml_.py` from `ncclient` and tweaked to use an `lxml` recovering parser:

```python
import sys
from ncclient.xml_ import to_ele

recovering_parser = etree.XMLParser(recover=True)
recovering_huge_parser = etree.XMLParser(recover=True, huge_tree=True)

def my_get_parser(huge_tree=False):
    return recovering_huge_parser if huge_tree else recovering_parser

def my_to_ele(x, huge_tree=False):
    if sys.version < '3':
        return x if etree.iselement(x) else etree.fromstring(x, parser=my_get_parser(huge_tree))
    else:
        return x if etree.iselement(x) else etree.fromstring(x.encode('UTF-8'), parser=my_get_parser(huge_tree))

old_to_ele = to_ele
to_ele = my_to_ele

# ...do ncclient operation...

to_ele = old_to_ele
```

Please note that if you do this, it will skip over the invalid namespace URI, but may also skip over other problems. The final `to_ele = old_to_ele` is to restore parsing behavior to normal.

Cheers,

Einar

**Comment by shade999** [comment]
Thank you for explanations.
Code you provided don't work for me, but now I understand which way I should go.
