### ISSUE TITLE
XML namespace tag nc:

### ISSUE THREAD

**Issue by northmirko** [ncclient/ncclient#344]
Hi, I dont think this is an issue with ncclient, but I cant find option to turn off xml namespace tagging.

ncclient sends this RPC,
`<?xml version="1.0" encoding="UTF-8"?>
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:cdad1414-956b-47e7-8efc-fee92888475c">
    <nc:get-config>
        <nc:source>
            <nc:running />
        </nc:source>
    </nc:get-config>
</nc:rpc>`

But,
my device (Ericsson Telecom Packet Core elements) do not support xml namespace tags, 
and expect request to be formated as:
`<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:cdad1414-956b-47e7-8efc-fee92888475c">
    <get-config>
        <source>
            <running />
        </source>
    </get-config>
</rpc>`

How can I turn off **nc:** ?

**Comment by einarnn** [comment]
Mirko,

The ncclient library uses the lxml library to create valid XML. The fragment you show below that is apparently what the Ericsson device accepts is invalid XML, and we cannot get lxml to produce invalid XML.

There may be a way to do this for your specific device type. I’ll take a quick look soon and see, but I advise you to get in touch with your vendor and ask  why they do not accept valid XML payloads.

Cheers,

Einar

**Comment by einarnn** [comment]
There is currently no implemented way to reformat a request made by a client. This could be added if someone wants to provide an extra hook in the `DefaultDeviceHandler`.

**Comment by chrisinmtown** [comment]
@einarnn please say how the XML block is invalid.  An element can be put into a namespace via an explicit namespace prefix plus definition of that prefix, or using a default namespace declaration. I see the latter in the question from @northmirko, it looks valid to me, but maybe I'm missing something?

**Comment by einarnn** [comment]
@chrisinmtown, sorry for the delayed response.

According to @northmirko, the XML block that the Ericsson device apparently accepts is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="...">
  <get-config>
    <source><running /></source>
   </get-config>
</rpc>
```

The tag `rpc` has no explicit namespace prefix, and is thus in the default namespace of the document. What is the default namespace of the document? It is not declared. Thus what namespace is `rpc`, and all subsequent tags, to be interpreted as belonging to? The only namespace declaration is for the prefix `nc`. Thus the document is not valid.

> See [here](https://www.w3.org/TR/xml-names/#defaulting) for a discussion of default XML namespaces.

When `ncclient`, using `lxml`, creates the XML payload, `lxml` knows that the `rpc` element, and the others in the example, belong to the namespace with the prefix `nc`, and so adds the namespace prefix to each element. It could also have set the default namespace instead, but it doesn't.

What I think is happening (and I have seen this in the embedded implementations before) is that the XML parser is pre-configured with `urn:ietf:params:xml:ns:netconf:base:1.0` as the default namespace. I know that in the past both Cisco IOS XR and Cisco IOS XE have done this.

**Comment by chrisinmtown** [comment]
I see two XML instances described as what-Ericsson-device-wants. They are different but I think both are valid XML. 

The XML instance posted by @northmirko in the first comment (actually the second instance in his comment) has all elements in a defined (non-default) namespace.  

The XML instance posted by @einarnn a few minutes ago today has all elements in the default namespace. The declaration of the "nc" namespace is not used on any element. Totally fine for elements to float in the default namespace, that was the case for all XML before the committee defined namespaces :) 

An XML message recipient like an Ericss///on device can impose constraints such as requiring a namespace declaration, but that's a slightly different issue.

Am I reading the instances correctly here?

**Comment by einarnn** [comment]
@chrisinmtown, this document, which is the second from @northmirko, is fully valid:

```
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="...">
  <get-config>
    <source><running/></source>
   </get-config>
</rpc>
```

This one, which defines the prefix `nc`, I would argue, in and of itself is "invalid" unless there is knowledge and agreement on the part of both the netconf client and the netconf server of what the default namespace is:

```
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="...">
  <get-config>
    <source><running /></source>
   </get-config>
</rpc>
```

> Totally fine for elements to float in the default namespace, that was the case for all XML before the committee defined namespaces :)

Sure, agreed. But for that to work and be valid when exchanging documents between two clients over netconf, both sides need to agree on what that default namespace is. And there is currently no mechanism defined for netconf for clients to make the assumption that a netconf server will define the default namespace to be `urn:ietf:params:xml:ns:netconf:base:1.0` in the absence of a definition of the default namespace being defined in the document.

And we are still left with the Ericsson device rejecting this well-formed message:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="...">
  <nc:get-config>
    <nc:source>
      <nc:running/>
    </nc:source>
  </nc:get-config>
</nc:rpc>
```

Regardless, I did a little investigation into whether or not we can get `lxml` to set `urn:ietf:params:xml:ns:netconf:base:1.0` as the default namespace for messages, and it is possible to do this using the `nsmap` parameter to various functions. `ncclient` even has a partial way of allowing this to be specified on a per-device-type basis. For example, you can define a class such as:

```python
from ncclient.devices.default import DefaultDeviceHandler

class NamespaceTweaker(DefaultDeviceHandler):
    def get_xml_base_namespace_dict(self):
        return {None: 'urn:ietf:params:xml:ns:netconf:base:1.0'}
```

...and pass this to the `manager.connect` call as `device_params={'handler': NamespaceTweaker}`.

However, this is currently only honored for the initial "hello" excahnge, not pervasively.

@northmirko, if you want to investigate the `ncclient` code to see how this could be honored more broadly, I would happily review a pull request, but I don't have the time to look at this right now.

**Comment by fredgan** [comment]
@northmirko Hi Mirko, I am researching this issue. I also tried to print the content of an RPC, there is no `nc:` in the request.  I use the latest master version. 

I don't know which version you are using. Could you show how you use ncclient?

**Comment by valeriodigregorio** [comment]
In my test infra, I do:
```python
element = etree.Element("config")
```
Then I subtree and set values. When I push the netconf request with ncclient I get:
```xml
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:fea7d025-5339-41b2-b3b6-5be9fa6de27f">
	<nc:edit-config>
		<nc:target>
			<nc:running/>
		</nc:target>
		<config>
			<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
				<stealthwatch-cloud-monitor xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-swc">
					<sensor-name>ciao</sensor-name>
				</stealthwatch-cloud-monitor>
			</native>
		</config>
	</nc:edit-config>
</nc:rpc>
```
As you can see tag should rather be "nc:config". Any workaround? I tried:
```python
element = etree.Element("nc:config")
```
But no luck :(

**Comment by valeriodigregorio** [comment]
I realised that in some case it adds "ns0" rather than "nc", I think this is when xml tree is created as a global variable, but I'm not entirely sure.

**Comment by einarnn** [comment]
You can try replacing:
	element = etree.Element(“{urn:ietf:params:xml:ns:netconf:base:1.0}config")

…with:
	element = etree.Element(“{urn:ietf:params:xml:ns:netconf:base:1.0}config")

Cheers,

Einar

**Comment by fredgan** [comment]
@einarnn 
> You can try replacing:
> 	element = etree.Element(“{urn:ietf:params:xml:ns:netconf:base:1.0}config")
>
> …with:
>	element = etree.Element(“{urn:ietf:params:xml:ns:netconf:base:1.0}config")
>

I'm sorry but I am just curious because they look exactly the same.

**Comment by einarnn** [comment]
Sorry, typo. Have updated: I meant:

You can try replacing:

```python
	element = etree.Element(“nc:config")
```
…with:

```python
	element = etree.Element(“{urn:ietf:params:xml:ns:netconf:base:1.0}config")
```
Cheers,

**Comment by sbarguil** [comment]
Hello all, 

I was facing the same issue trying to send the "edit-config" to a confd Netconf Server. The edit-config was well formed, however it has a "**nc**" prefix in the rpc message:

``
<**nc**:rpc message-id="urn:uuid:53fadf51-1879-4eb3-bd85-b3496b4a33cc" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
...
``

This generates and invalid path error and avoid the correct configuration:

```
<rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:53fadf51-1879-4eb3-bd85-b3496b4a33cc" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-element</error-tag>
    <error-severity>error</error-severity>
    <error-path>
    /rpc
  </error-path>
    <error-info>
      <bad-element>edit-config</bad-element>
    </error-info>
  </rpc-error>
</rpc-reply>
```

After reading this issue and try several things, I have used the option **device_params={'name': 'huawei'}**.  This handler removes the "nc" prefix and allows the configuration, whitout any change in the nc library:

``
<rpc message-id="urn:uuid:22bd61cb-83b4-4274-b088-a0fbb9f8630b" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <interfaces xmlns="http://openconfig.net/yang/interfaces">
        <interface>
          <name>2</name>
          <config>
``

**Comment by einarnn** [comment]
@sbarguil, do you know which version of confd you were having issues with? (I'm assuming that by "confd" you mean Tail-F's ConfD?)

**Comment by sbarguil** [comment]
The version Im using is:

```
vsn: 7.3.1
SMP support: no
Using epoll: no
available modules: backplane,netconf,cdb,cli,snmp,webui
```

**Comment by einarnn** [comment]
> Hello all,
> 
> I was facing the same issue trying to send the "edit-config" to a confd Netconf Server. The edit-config was well formed, however it has included an "**nc**" prefix in the rpc message:
> 
> ```
> <**nc**:rpc message-id="urn:uuid:53fadf51-1879-4eb3-bd85-b3496b4a33cc" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
>   <edit-config>
>     <target>
>       <running/>
>     </target>
>     <config>
> ...
> ```

Please note that this payload isn't actually well-formed in the XML sense. You need to also have the `nc` prefix on each of the other elements also.

> This generates and invalid path error and avoids the device configuration:
> 
> ```
> <rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:53fadf51-1879-4eb3-bd85-b3496b4a33cc" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
>   <rpc-error>
>     <error-type>protocol</error-type>
>     <error-tag>unknown-element</error-tag>
>     <error-severity>error</error-severity>
>     <error-path>
>     /rpc
>   </error-path>
>     <error-info>
>       <bad-element>edit-config</bad-element>
> ```

And this error demonstrates the problem. Because there is no prefix, the `edit-config` tag is assumed to be in the defauklt namespace, and there isn't a default namespace declared for the XML payload. So, the ConfD XML parser does not know that the `edit-config` is in the netconf base namespace.

IIRC, earlier versions of ConfD may have parsed XML as if the netconf base namespace was the default namespace, in which case this error would have been missed.

> ```
>     </error-info>
>   </rpc-error>
> </rpc-reply>
> ```
> 
> After reading this issue and try several things, I have used the option **device_params={'name': 'huawei'}**.
> This handler removes the "nc" prefix and allows the configuration, whitout any change in the nc-client library. The new rpc message is the following:
> 
> ```
> <rpc message-id="urn:uuid:22bd61cb-83b4-4274-b088-a0fbb9f8630b" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
>   <edit-config>
>     <target>
>       <running/>
>     </target>
>     <config>
>       <interfaces xmlns="http://openconfig.net/yang/interfaces">
>         <interface>
>           <name>2</name>
>           <config>
> ```

Yep, and this should (and does) work fine. But, to be clear again, the first payload was not valid given ConfD makes no assumptions about a default namespace.

Cheers,

Einar

**Comment by einarnn** [comment]
#420 shows how devices that don't parse XML correctly may be "helped" using a device handler. That is all that can be done to address this issue for now.
