### ISSUE TITLE
Create-Subscription exception

### ISSUE THREAD

**Issue by songxl** [ncclient/ncclient#346]
Hi,

I am using ncclient 0.6.0 from NSO, python2.7.2
the line got exception is below:

            reply = nso.ncclient.create_subscription(stream_name='viptela',
                                                     start_time=start_time_str)

However we got this traceback:
               Traceback (most recent call last):
                 File "/nobackup/xiaolson/nfvis-sanity/nfvis/tests-
v2/clouddock_netconf_tests/nfvis_colomgr_bringup.py", line 585, in check_nso_access
                   start_time=start_time_str)
                 File "/auto/nfvos-builds01/pyats_clouddock/lib/python3.4/site-packages/ncclient/manager.py", 
line 170, in wrapper
                   return self.execute(op_cls, *args, **kwds)
                 File "/auto/nfvos-builds01/pyats_clouddock/lib/python3.4/site-
packages/yang/connector/__init__.py", line 357, in execute
                   return super().execute(cls, *args, **kwargs)
                 File "/auto/nfvos-builds01/pyats_clouddock/lib/python3.4/site-packages/ncclient/manager.py", 
line 240, in execute
                   raise_mode=self._raise_mode).request(*args, **kwds)
                 File "/auto/nfvos-builds01/pyats_clouddock/lib/python3.4/site-
packages/ncclient/operations/subscribe.py", line 64, in request
                   return self._request(node)
                 File "/auto/nfvos-builds01/pyats_clouddock/lib/python3.4/site-
packages/ncclient/operations/rpc.py", line 336, in _request
                   raise self._reply.error
               ncclient.operations.rpc.RPCError: {'tag': 'unknown-element', 'message': None, 'path': '\n    
/rpc/p0:create-subscription\n  ', 'info': '<?xml version="1.0" encoding="UTF-8"?><error-info 
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
<bad-element>stream</bad-element>\n</error-info>\n', 'type': 'protocol', 'severity': 'error'}

I tried to use netconf browser to send below netconf:
<create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
  <stream>viptela</stream>
  <startTime>2019-09-26T21:08:28+00:00</startTime>
</create-subscription>

Got reply and notifications correctly.

**Comment by einarnn** [comment]
Addressed in #350.
