### ISSUE TITLE
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply

### ISSUE THREAD

**Issue by menkeyi001** [ncclient/ncclient#347]
I don't know why this problem occurs and there's no way to get all the configurations?

Firewall version:
H3C-M9006

from ncclient import manager

with manager.connect(host="xxxxxxxxxx", port=830, password="xxxxxxxxxxxxxxxx",
                     username="netconf", hostkey_verify=False,
                     device_params={'name':'h3c'}) as m:
    c = m.get_config(source='running').data_xml
    with open("%s.xml" % host, 'w') as f:
        f.write(c)

/usr/local/python3/lib/python3.7/site-packages/paramiko/ecdsakey.py:164: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.ecdsa_curve.curve_class(), pointinfo
Traceback (most recent call last):
  File "t2.py", line 70, in get_current_configuration
    c = m.get_config(source='running').data_xml
  File "/usr/local/python3/lib/python3.7/site-packages/ncclient/manager.py", line 216, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/usr/local/python3/lib/python3.7/site-packages/ncclient/operations/retrieve.py", line 166, in request
    return self._request(node)
  File "/usr/local/python3/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 347, in _request
    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t2.py", line 96, in <module>
    device_params={'name':'h3c'})
  File "t2.py", line 73, in get_current_configuration
    f.write(c)
  File "/usr/local/python3/lib/python3.7/site-packages/ncclient/manager.py", line 198, in __exit__
    self.close_session()
  File "/usr/local/python3/lib/python3.7/site-packages/ncclient/manager.py", line 216, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/usr/local/python3/lib/python3.7/site-packages/ncclient/operations/session.py", line 28, in request
    return self._request(new_ele("close-session"))
  File "/usr/local/python3/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 347, in _request
    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.

**Comment by menkeyi001** [comment]
The one that needs to be executed first！！！！！！！！！！H3C
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>
     capability-set
   </capability>
 </capabilities>
</hello>

**Comment by menkeyi001** [comment]
How to add the following XML after sending Hello package？


<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>
     capability-set
   </capability>
 </capabilities>
</hello>

**Comment by leimgitub** [comment]
I believe your get will give a huge xml, it will take more than 30 seconds. And I check the code, classncclient.operations.RPC(session, device_handler, async=False, **timeout=30**, raise_mode=0), the default value is 30.

**Comment by einarnn** [comment]
If a lot of data is being returned, please increase the RPC timeout. This can be done by adding the key parameter `manager_params={"timeout": 300}` (300 is just an example), which will give a 5 minute timeout to `get`, `get-config`, etc.

Closing this issue as it's not a problem with ncclient unless other information comes to light.
