### ISSUE TITLE
Why notice point to CISCO

### ISSUE THREAD

**Issue by vnitinv** [ncclient/ncclient#353]
https://github.com/ncclient/ncclient/blob/master/NOTICE

This project is developed by all the vendors. Why this notice is very specific to CISCO?

**Comment by einarnn** [comment]
@vnitinv, this is an attribution that Cisco Legal asked for based on the rules they have for open source contributions by Cisco employees. I had a discussion with Cisco legal to ensure that the notice was suitably worded and reflected the fact that Cisco employees have only made contributions and are by no means the primary authors.

If other vendors have similar contribution requirements they are free to add them here or separately.

**Comment by einarnn** [comment]
@vnitinv -- I'll assume that no response means you are ok with this response. If you wish to attach similar text for Juniper, please feel free add text to the NOTICE file in a PR.
