### ISSUE TITLE
Internal error when trying to retrieve SRX configuration

### ISSUE THREAD

**Issue by doesitblend** [ncclient/ncclient#356]
Using the attached script I am getting an error when trying to pull my configuration:

```
('invalid command: 721 %s %s', u'internal error: Huge input lookup, line 105527, column 33', 'show configuration | display set')
```

This is using the current stable release of the library (0.6.6). I am able to remove a single single from y configuration, the line is semi-arbitrary and the script will work as expected.

To get the error to show up I made some slight modifications the ncclient library on line 721 where the error seemed to be occurring and updated the message to print the exception. However, I'm unable to determine whether the issue is happening on the NETCONF server or within the library directly.

[test_connect.py.zip](https://github.com/Juniper/py-junos-eznc/files/3832525/test_connect.py.zip)

**Comment by doesitblend** [comment]
@vnitinv Can you please review this issue.

This issue is likely happening pyez. Can you please look into that? 

Thanks in advance.

**Comment by einarnn** [comment]
@doesitblend, @vnitinv -- can you guys please confirm if this issue has been addressed in PyEz? And, if so, @doesitblend, can you close this issue?

Thanks!

Einar

**Comment by vnitinv** [comment]
This has been fixed in PyEZ. I am closing this issue. If someone face any problen (via PyEZ) please raise it at https://github.com/Juniper/py-junos-eznc
