### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by markgoddard** [ncclient/ncclient#359]
It's been a while since 0.6.6, could we have a new release please?

**Comment by einarnn** [comment]
I can look at this in a week or two.

Cheers,

Einar

**Comment by einarnn** [comment]
More than a couple of weeks, but [v0.6.7][(https://github.com/ncclient/ncclient/releases/tag/v0.6.7) is now up on PyPi!

**Comment by markgoddard** [comment]
Thanks!
