### ISSUE TITLE
Sysrepo Compilation Failing.

### ISSUE THREAD

**Issue by akshatagage51** [ncclient/ncclient#360]
Hi,
I am trying to install sysrepo on ubuntu 18.04.
I have cloned the latest sysrepo repository and followed the steps provided in install.md, compiled sysrepo with release version.
Installed following packages,
libxml2, libxml2-dev, libxml2-utils, libxml2-dbg, liburcu-dev, libjson0, libuv1-dev, libuv1, nasm, libnuma-dev, python, yasm, gcc, make, cmake, bison, flex, valgrind, python-dev, lua5.2,   libev-dev, libavl-dev, libprotobuf-c-dev, protobuf-c-compiler, swig, build-essential, libpcre3-dev.

Cmocks version : libcmocka.so.0.7.0

Getting following error on make:

_system_helper.c:(.text+0x5d1): undefined reference to `_assert_true'
CMakeFiles/HELPERS.dir/helpers/system_helper.c.o: In function `assert_null_bt':
system_helper.c:(.text+0x61e): undefined reference to `_assert_true'
CMakeFiles/HELPERS.dir/helpers/system_helper.c.o: In function `assert_true_bt':
system_helper.c:(.text+0x657): undefined reference to `_assert_true'
CMakeFiles/HELPERS.dir/helpers/system_helper.c.o: In function `assert_false_bt':
system_helper.c:(.text+0x697): undefined reference to `_assert_true'
CMakeFiles/HELPERS.dir/helpers/system_helper.c.o: In function `assert_string_equal_bt':
system_helper.c:(.text+0x6df): undefined reference to `_assert_string_equal'
CMakeFiles/HELPERS.dir/helpers/system_helper.c.o: In function `assert_int_equal_bt':
system_helper.c:(.text+0x71e): undefined reference to `_assert_int_equal'
CMakeFiles/HELPERS.dir/helpers/system_helper.c.o: In function `assert_int_not_equal_bt':
system_helper.c:(.text+0x8ef): undefined reference to `_assert_int_not_equal'
CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function `new_nacm_config':
nacm_module_helper.c:(.text+0x32): undefined reference to `_assert_true'
nacm_module_helper.c:(.text+0x5e): undefined reference to `_assert_true'
nacm_module_helper.c:(.text+0x8a): undefined reference to `_assert_true'
CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function `save_nacm_config':
nacm_module_helper.c:(.text+0xc9): undefined reference to `_assert_int_equal'
CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function `enable_nacm_config':
nacm_module_helper.c:(.text+0x184): undefined reference to `_assert_true'
CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function `set_nacm_read_dflt':
nacm_module_helper.c:(.text+0x1e2): undefined reference to `_assert_true'
CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function `set_nacm_write_dflt':
nacm_module_helper.c:(.text+0x242): undefined reference to `_assert_true'
CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function `set_nacm_exec_dflt':
nacm_module_helper.c:(.text+0x2a2): undefined reference to `_assert_true'
CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function `enable_nacm_ext_groups':
nacm_module_helper.c:(.text+0x314): undefined reference to `_assert_true'
CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o:nacm_module_helper.c:(.text+0x3c6): more undefined references to `_assert_true' follow
CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function `save_nacm_config':
nacm_module_helper.c:(.text+0xf5): undefined reference to `_assert_int_equal'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/values_test.dir/build.make:107: recipe for target 'tests/values_test' failed
make[2]: *** [tests/values_test] Error 1
CMakeFiles/Makefile2:1401: recipe for target 'tests/CMakeFiles/values_test.dir/all' failed
make[1]: *** [tests/CMakeFiles/values_test.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2_

Can you please provide some solution...

Thanks Akshata

**Comment by einarnn** [comment]
@akshatagage51, this isn't an ncclient issue as far as I can see. Suggest you find the appropriate repo under the sysrepo project itself:

> https://github.com/sysrepo
