### ISSUE TITLE
MissingCapabilityError: Server does not support [:notification] in cisco ios

### ISSUE THREAD

**Issue by dounialab** [ncclient/ncclient#361]
hello,
we want to work on netconf notifications using manager.create_subscription(). and we got this error :
ncclient.operations.errors.MissingCapabilityError: Server does not support [:notification]
cisco device =switch catalyst 2960-s iosxr 
device capabilities=
Les capabilities:   .....    urn:ietf:params:netconf:base:1.0
Les capabilities:   .....    urn:ietf:params:netconf:capability:writeable-running:1.0
Les capabilities:   .....    urn:ietf:params:netconf:capability:startup:1.0
Les capabilities:   .....    urn:ietf:params:netconf:capability:url:1.0
Les capabilities:   .....    urn:cisco:params:netconf:capability:pi-data-model:1.0
Les capabilities:   .....    urn:cisco:params:netconf:capability:notification:1.0

**Comment by einarnn** [comment]
@dounialab, the feedback from ncclient and the behavior of the Cisco device seem to be mismatched, and I think this reflects the fact that the Cisco Catalyst 2960-S switch doesn't support netconf notifications as far as I am aware.

For Cisco switches, you will need to have a more recent switch that  can run IOS XE, such as a the Catalyst 9x00, Catalyst 3850 or Catalyst 3650. I strongly recommend IOS XE 16.10.1 or later.

Regardless, this is a vendor issue, not an ncclient issue, so I am closing this issue.
