### ISSUE TITLE
ncclient.operations.rpc.RPCError: ifm has invalid namespace: http://www.huawei.com/netconf/vrp/huawei-ifm.

### ISSUE THREAD

**Issue by stvnkem** [ncclient/ncclient#376]
Dear,

I got the following exception while testing my very first Netconf-Yang call.
The code sample is from Huawei documentation.

```
Traceback (most recent call last):
  File "netconf_yang_test.py", line 29, in <module>
    test_get('ipi-zhb790-r-ml-98', '22', 'taakeis1', 'o8Vah12+')
  File "netconf_yang_test.py", line 25, in test_get
    get_reply = m.get(("subtree", FILTER))
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/ncclient/manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/ncclient/operations/retrieve.py", line 91, in request
    return self._request(node)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/ncclient/operations/rpc.py", line 348, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: ifm has invalid namespace: http://www.huawei.com/netconf/vrp/huawei-ifm.
```

Code:
https://codeshare.io/ayREp9

Here are the logs recorded by the device:
https://codeshare.io/5vRpry

Any idea why?

Thanks,
Istvan

**Comment by einarnn** [comment]
@stvnkem, the error message suggests that for whatever reason the device is unaware of the namespace `http://www.huawei.com/netconf/vrp/huawei-ifm`, which isn't really a `ncclient` problem.

I suggest that you start with a get-config with no filter at all, and see what content you get back, which can also help you compose a subtree filter. You could also check `m.server_capabilities` for the models advertised by the device and check the namespaces being advertised by the device.

Good luck! But I am closing this issue as there is no apparent problem with `ncclient` here! 🙂
