### ISSUE TITLE
ncclient broken in EPEL for CentOS 7

### ISSUE THREAD

**Issue by azzid** [ncclient/ncclient#378]
I just started trying to use `ncclient` to configure a HPE Apollo 10/40GbE Switch and had a real bad time doing so until I realized that the problem might be in the packaging for epel.

    # yum info python-ncclient  
    Available Packages  
    Name        : python-ncclient  
    Arch        : noarch  
    Version     : 0.4.2  
    Release     : 2.el7  
    Size        : 164 k  
    Repo        : epel/x86_64  
    Summary     : Python library for NETCONF clients  
    URL         : https://pypi.python.org/pypi/ncclient  
    License     : ASL 2.0  
    Description : This project is a Python library that facilitates client-side  
                : scripting and application development around the NETCONF protocol.  

ncclient version 0.4.2 is quite old by now and is even missing the device_params={'name': 'hpcomware'} that my switch would supposedly benefit from.

The code I struggled to get working looks like:

    #!/usr/bin/python
    from ncclient import manager

    with manager.connect(host='comware710switch',
                         port=830,
                         username='admin',
                         password='admin',
                         hostkey_verify=False,
                         allow_agent=False,
                         look_for_keys=False,
                         device_params={'name': 'default'}
                        ) as netconf_manager:
      filter = '''
                <top xmlns="http://www.hp.com/netconf/data:1.0">
                </top>
               '''
      data = netconf_manager.get(('subtree', filter))

and the error I get is:

    Traceback (most recent call last):
      File "./test.py", line 21, in <module>
        data = netconf_manager.get(('subtree', filter)).xml
      File "/usr/lib/python2.7/site-packages/ncclient/manager.py", line 203, in __exit__
        self.close_session()
      File "/usr/lib/python2.7/site-packages/ncclient/manager.py", line 151, in wrapper
        return self.execute(op_cls, *args, **kwds)
      File "/usr/lib/python2.7/site-packages/ncclient/manager.py", line 221, in execute
        raise_mode=self._raise_mode).request(*args, **kwds)
      File "/usr/lib/python2.7/site-packages/ncclient/operations/session.py", line 28, in request
        return self._request(new_ele("close-session"))
      File "/usr/lib/python2.7/site-packages/ncclient/operations/rpc.py", line 308, in _request
        raise self._reply.error
    ncclient.operations.rpc.RPCError: Unexpected attribute '':'type' of element '/rpc/close-session[1]'.

I lack the skill to pair up that error with any particular commit modernizing rpc.py and I don't know how to report this issue to the EPEL maintainers. Maybe someone from this community could do something to help EPEL get a working version of ncclient?

I created a modern virtual environment with ncclient 0.6.7 and tried my code in it and verified that both the code and switch configuration is working, so while I fail to exactly identify the bug in EPEL I'm fairly certain it is there.

**Comment by einarnn** [comment]
@azzid, suggest you take a look at https://fedoraproject.org/wiki/EPEL#How_can_I_contribute.3F to see how you might engage with the EPEL team. I’m afraid I don’t have time to follow up on this, especially if more recent versions of ncclient Just Work™ on your target version of CentOS.
