### ISSUE TITLE
Huawei USG returns no output

### ISSUE THREAD

**Issue by stvnkem** [ncclient/ncclient#379]
Dear,

I am new to Netconf and trying to query a Huawei USG firewall. The queries with subtree filter usually do return no output, except 1 case where I managed to modify the XML, I will describe it below.
`m.get_config(('running'))` returns the full config, this works.
I am using XML filters given in the official doc.

Limitations described in the doc:
Obtains data, including running status data and configuration data. <filter> element: filters  information. If <filter> is not specified, the system returns the information about the entire configuration datastore. NOTE:   V600R006C00 supports only the subtree filter, but not the XPath filter. The target datastore of all operations must be the running datastore. That is, the `<source></source>  value must be <running/>.`

Example 1, NCCLIEN returns an error when the entire filter is used:

```
FILTER = """
<?xml version="1.0" encoding="UTF-8"?>
<rpc message-id="1008" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get-config>
    <source>
      <running/>
    </source>
    <filter type="subtree">
      <sec-policy xmlns="urn:huawei:params:xml:ns:yang:huawei-security-policy">
      </sec-policy>
    </filter>
  </get-config>
</rpc>
"""
```

`return m.get(("subtree", FILTER))`

`ValueError: Invalid tag name '(\'subtree\', \'\\n<?xml version="1.0" encoding="UTF-8"?>\\n<rpc message-id="1008" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">\\n  <get-config>\\n    <source>\\n      <running/>\\n    </source>\\n    <filter type="subtree">\\n      <sec-policy xmlns="urn:huawei:params:xml:ns:yang:huawei-security-policy">\\n      </sec-policy>\\n    </filter>\\n  </get-config>\\n</rpc>\\n\')'`

After removing the first line of the FILTER ' <?xml version="1.0" encoding="UTF-8"?> '
It returns no data:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:b0d2ab74-e8c6-42ef-ac1f-546fb9969eb8"><data/></rpc-reply>

Example 2, managed to modify the XML.

The filter given in the doc is not working:

```
FILTER = """
<rpc message-id="1002" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get-config>
    <source>
      <running/>
    </source>
    <filter type="subtree">
      <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces"      xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"  
      xmlns:urn1="urn:huawei:params:xml:ns:yang:huawei-interface" 
      xmlns:urn2="urn:huawei:params:xml:ns:yang:huawei-security-zone"
      xmlns:urn3="urn:ietf:params:xml:ns:yang:ietf-ip"
      xmlns:urn4="urn:huawei:params:xml:ns:yang:huawei-eth-trunk"
      xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">
      </interfaces>
    </filter>
  </get-config>
</rpc>
"""
```

`return m.get(("subtree", FILTER))`

`<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:e82b3a48-eb5d-49f5-b195-e6fca381dfae"><data/></rpc-reply>`

After modifying the filter the data was properly returned.

```
FILTER = """
      <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces"      xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"  
      xmlns:urn1="urn:huawei:params:xml:ns:yang:huawei-interface" 
      xmlns:urn2="urn:huawei:params:xml:ns:yang:huawei-security-zone"
      xmlns:urn3="urn:ietf:params:xml:ns:yang:ietf-ip"
      xmlns:urn4="urn:huawei:params:xml:ns:yang:huawei-eth-trunk"
      xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">
      </interfaces>
"""
```

`<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:9627e56d-5be1-46bf-a4f3-6c7b0865074a"><data><interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces" xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type" xmlns:hw-if="urn:huawei:params:xml:ns:yang:huawei-interface"` ----------------- output ommitted.

I did not manage to modify any other filters to get them working.
What is the trick? What am I doing wrong?

Full code:
[https://trinket.io/python/e053ac9fe8](url)

**Comment by einarnn** [comment]
@stvnkem , when using the ncclient `get` and `get_config` functions, the filter should just be the content that sits inside the `<filter>` element. So, for the IETF interfaces model, you would have:

```python
from ncclient import manager

FILTER = '''<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces"/>'''

m = manager.connect(
    host=host, port=port,
    username=user, password=password,
    hostkey_verify=False, allow_agent=False, look_for_keys=False,
    device_params={'name': "huawei"})

# get from operational state
result = m.get(filter=('subtree', FILTER))

# get from running
result = m.get(source='running', filter=('subtree', FILTER))
```

**Comment by einarnn** [comment]
BTW, please feel free to look at other sample ncclient-based code:

https://github.com/CiscoDevNet/ncc/blob/master/ncc

**Comment by stvnkem** [comment]
@einarnn Hello, thank you for your help!

I think I started to understand the issue more.
The other filters I have been failing with are Huawei filters, not IETF like `xmlns="urn:huawei:params:xml:ns:yang:huawei-security-policy`

Could you please give an example of how to format the filter below? It would be a great reference.

```
<?xml version="1.0" encoding="UTF-8"?>
<rpc message-id="1008" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get-config>
    <source>
      <running/>
    </source>
    <filter type="subtree">
      <sec-policy xmlns="urn:huawei:params:xml:ns:yang:huawei-security-policy">
      </sec-policy>
    </filter>
  </get-config>
</rpc>
```

Thank you in advance!

**Comment by fredgan** [comment]
Hi,

For your first case, you can try :
```python
filter = """
<sec-policy xmlns="urn:huawei:params:xml:ns:yang:huawei-security-policy">
      </sec-policy>
"""
c = m.get_config(source='running', filter=filter).data_xml
print(c)
```

For your second case, you can try:
```python
rpc = new_ele('ipv6-session-verbose')
sub_ele(rpc, 'namespace').text="urn:huawei:yang:huawei-security-session"
#todo add input elements to rpc...
response = m.dispatch(rpc)
print(response)
```

**Comment by stvnkem** [comment]
``

> Hi,
> 
> For your first case, you can try :
> 
> ```python
> filter = """
> <sec-policy xmlns="urn:huawei:params:xml:ns:yang:huawei-security-policy">
>       </sec-policy>
> """
> c = m.get_config(source='running', filter=filter).data_xml
> print(c)
> ```
> 
> For your second case, you can try:
> 
> ```python
> rpc = new_ele('ipv6-session-verbose')
> sub_ele(rpc, 'namespace').text="urn:huawei:yang:huawei-security-session"
> #todo add input elements to rpc...
> response = m.dispatch(rpc)
> print(response)
> ```

Hello @fredgan none of them seem to work. The second example is complaining about undefined variables, nem_ele & sub_ele

Response of the first example:
`raise XMLError("Element [%s] does not meet requirement" % ele.tag)
ncclient.xml_.XMLError: Element [{urn:huawei:params:xml:ns:yang:huawei-security-policy}sec-policy] does not meet requirement
`

**Comment by fredgan** [comment]
Sorry for the first one, 'subtree' is missed.
```python
filter = """
<sec-policy xmlns="urn:huawei:params:xml:ns:yang:huawei-security-policy">
      </sec-policy>
"""
c = m.get_config(source='running', filter=('subtree', filter)).data_xml
print(c)
```

As for the second one, please import:
```python
from ncclient.xml_ import *
```

**Comment by stvnkem** [comment]
> Sorry for the first one, 'subtree' is missed.
> 
> ```python
> filter = """
> <sec-policy xmlns="urn:huawei:params:xml:ns:yang:huawei-security-policy">
>       </sec-policy>
> """
> c = m.get_config(source='running', filter=('subtree', filter)).data_xml
> print(c)
> ```
> 
> As for the second one, please import:
> 
> ```python
> from ncclient.xml_ import *
> ```

 @fredgan Thank you! The first one worked.

After importing the required modules:

`ncclient.operations.rpc.RPCError: An unexpected element is present.
`

**Comment by fredgan** [comment]
Hi  @stvnkem ,
I am not sure what you use in the second case.
From your `rpc content`, what I wrote is incomplete. You must add some sub nodes to the `ipv6-session-verbose`

**Comment by einarnn** [comment]
Assuming this issue is now resolved given the dialog.
