### ISSUE TITLE
comment entry is not right

### ISSUE THREAD

**Issue by neilliu89** [ncclient/ncclient#387]
In the file(ncclient/ncclient/devices/h3c.py), the file comment entry is not right.
The right is like this:
'''
Handler for H3c device specific information.
'''
not:
'''
Handler for Huawei device specific information.
'''

**Comment by fredgan** [comment]
Seems you are right! Would you like to make an PR for modify this? If not, I would do for you. ^_^

**Comment by neilliu89** [comment]
Of course, I am glad to do this! ^_^


| |
neilliu
|
|
lyqqjh@163.com
|
签名由网易邮箱大师定制
On 4/30/2020 10:45，FredGan<notifications@github.com> wrote：

Seems you are right! Would you like to make an PR for modify this? If not, I would do for you. ^_^

**Comment by fredgan** [comment]
@neilliu89 Your PR's merged, so you can close it.

**Comment by einarnn** [comment]
Addressed by #388
