### ISSUE TITLE
BGP EDIT CONFIG 

### ISSUE THREAD

**Issue by Priyanka-TK** [ncclient/ncclient#389]
Hi,

I am new to the NETCONF operations. I am trying to edit the configuration with ncclient on cisco XRv devices in future Juniper device. I am able to parse the XML RPC request and getting OK response but it is not reflecting in candidate DB and some time facing problem in parsing also.

Any leads will be helpful.

Regards,
Priyanka

**Comment by einarnn** [comment]
Priyanka,

You could take a look at two tools and see how they use ncclient internally:

- https://github.com/CiscoDevNet/ncc
- https://bitbucket.org/martin_volf/ncc/src/master/

These both work with NETCONF servers in a non-vendor-specific way, and should give you hints. You will also find that most vendors' website give sample code, some based around ncclient.

However, this is not an issue with ncclient as such, so I am closing it.

Cheers,

Einar
