### ISSUE TITLE
m.locked("running") error

### ISSUE THREAD

**Issue by menkeyi** [ncclient/ncclient#390]
Write a running error as follows:

/usr/local/lib/python3.6/site-packages/ncclient/manager.py
def locked(self, target):
        """Returns a context manager for a lock on a datastore, where
        *target* is the name of the configuration datastore to lock, e.g.::

            with m.locked("running"):
                # do your stuff

        ... instead of::

            m.lock("running")
            try:
                # do your stuff
            finally:
                m.unlock("running")
        """

[root@localhost ~]# python3 t2.py
<?xml version="1.0" encoding="UTF-8"?><nc:security xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><nc:nat><nc:source><nc:rule-set><nc:name>api-mky12</nc:name><nc:from><nc:zone>trust</nc:zone></nc:from><nc:to><nc:zone>untrust</nc:zone></nc:to></nc:rule-set></nc:source></nc:nat></nc:security>
Traceback (most recent call last):
  File "t2.py", line 110, in <module>
    with m.locked("running"):
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/lock.py", line 67, in __enter__
    Lock(self.session, self.device_handler, raise_mode=RaiseMode.ERRORS).request(self.target)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/lock.py", line 35, in request
    return self._request(node)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 348, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: syntax error

**Comment by fredgan** [comment]
Please show your t2.py code

**Comment by einarnn** [comment]
No further discussion forthcoming, assuming this is no longer an issue, so closing for now!
