### ISSUE TITLE
How to execute rpc without using device params during connect.

### ISSUE THREAD

**Issue by deeptijain34** [ncclient/ncclient#396]
Hi Guys ,

I have a requirement here , i want to execute rpc using netconf .
I see if we pass the (device_params={'name': 'nexus'}) while creating the netconf connection object we get the attribute (rpc) added to the connection object which can then be further used to execute rpc.
Something like this :
connect = rpc(rpc=rpcConfig).

But i have a connection object created without passing device_params argument to it , with that connection object , Is there any way to execute the rpc  ?

conect = manager.connect(host=host, port=port  username=username, password=password, look_for_keys=False, allow_agent=False, hostkey_verify=False)
With this connection object i do not see any option to execute rpc : 

In [3]: conect.
conect.async_mode           conect.copy_config          conect.get                  conect.raise_mode           conect.timeout
conect.channel_id           conect.create_subscription  conect.get_config           conect.reboot_machine       conect.unlock
conect.channel_name         conect.delete_config        conect.get_schema           conect.scp                  conect.validate
conect.client_capabilities  conect.discard_changes      conect.kill_session         conect.server_capabilities
conect.close_session        conect.dispatch             conect.lock                 conect.session
conect.commit               conect.edit_config          conect.locked               conect.session_id
conect.connected            conect.execute              conect.poweroff_machine     conect.take_notification

Any help or suggestions would be helpful .

Thanks & Regards,
Deepti Jain

**Comment by einarnn** [comment]
Deepti,

Have a look at the "dispatch" call on the manager object:

https://github.com/ncclient/ncclient/blob/54d50ec18e5634e3737ab38e165939997516bba4/ncclient/operations/retrieve.py#L200-L239

If you correctly construct the lxml etree for your RPC, you can call manager.dispatch with that etree instance. You can take a look at other third party RPCs to see how to do that.

Cheers,

Einar

**Comment by deeptijain34** [comment]
@einarnn  That helped , Thanks !
