### ISSUE TITLE
Issue in getting notification

### ISSUE THREAD

**Issue by rissahu** [ncclient/ncclient#398]
When i am pushing the rpc for the notification subscription , the rpc response come as "subscription already exists" . When i am pushing the rpc for alarms , it creates new session and closes the same but i don't receive any notification . Is there any solutions to this problem ?

**Comment by smrigupt** [comment]
I am facing issue while recieving notification though the subscription already exists in ncclient. Can anyone help me with the solution for this?

**Comment by einarnn** [comment]
Can you provide sample code that demonstrates the problem?

**Comment by smrigupt** [comment]
Earlier issue is been solved.
But this time i need to pass start time and stop time in create_subscription. There should be some syntax to be followed, i couldnt find it.

e.g  m.create_subscription(stream_name="")
Could you please provide me with the correct syntax to be followed while passing start time and stop time?

**Comment by einarnn** [comment]
Please see:

https:// .com/ncclient/ncclient/blob/3bd7ce3177e747c307afd6340878ed0be8691cc6/ncclient/operations/subscribe.py#L27-L49

In summary, pass in two parameters:

- start_time: an RFC 3339/ISO 8601 date and time
- stop_time: an RFC 3339/ISO 8601 date and time

Cheers,

Einar
