### ISSUE TITLE
Edit config operational issueH

### ISSUE THREAD

**Issue by Maku-chan** [ncclient/ncclient#399]
Hello,

I am currently trying to push the configuration using the ncclient and getting the below error

Traceback (most recent call last):
  File "configuration_file.py", line 23, in <module>
    m.edit_config(target='running', config=configuration, format='xml')
  File "/usr/local/lib/python3.7/site-packages/ncclient/manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/ncclient/operations/edit.py", line 69, in request
    return self._request(node)
  File "/usr/local/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 348, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: {'type': 'protocol', 'tag': 'unknown-element', 'severity': 'error', 'info': '<?xml version="1.0" encoding="UTF-8"?><error-info xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><bad-element>config</bad-element>\n</error-info>\n', 'path': '\n    /rpc/edit-config\n  ', 'message': None}

But it works completely fine with the same configuration when I try to push it using the netconf console with the help of my xml file.

The version which I am using for ncclient is "0.6.7"

-Maku_chan

**Comment by einarnn** [comment]
`netconf-console`, IIRC, allows you to push entire XML blobs that conform to entire messages.

However, when you are using ncclient to invoke the `edit-config` RPC, you only provide it content from the `config` element down. You should not include the `<rpc>` or `<edit-config>` nodes, for example, and the target datastore is passed as another parameter.

See some of the simple examples at:

> https://github.com/ncclient/ncclient/tree/master/examples

There is one example that shows how to create an lxml.etree programmatically, and several that show using plain text as input.

If this resolves the problem you are seeing above, please close this issue!

**Comment by einarnn** [comment]
Ok, hoping that this resolved the issue. Closing this for now, please re-open if a problem with ncclient is found!
