### ISSUE TITLE
Hii, i am seeing issue with take_notification

### ISSUE THREAD

**Issue by smrigupt** [ncclient/ncclient#400]
My execution keeps waiting for the notification, but cant recieve any , I have used the following code, cud anyone help?

m.create_subscription(stream_name="")
n =m.take_notification(block=True, timeout=60)
				print(n.notification_xml)

**Comment by smrigupt** [comment]
my script got stuck and doesnt get any notification

**Comment by einarnn** [comment]
This may well be because the netconf server you are connected to doesn't have a stream with the empty string as its name. You may want to try

```
m.create_subscription(stream_name="NETCONF")
```

...as the stream "NETCONF" is quite commonly supported.

**Comment by smrigupt** [comment]
Even after passing stream , i am unable to listen to notifications,I am using the following RPC with stream 

CREATE_SUBSCRIPTION = '''<?xml version="1.0" encoding="UTF-8"?>
  <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="{}">
    <create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
      <stream>OPENROADM</stream>
    </create-subscription>
  </rpc>'''


and also i have tried with 
m.create_subscription(stream_name="NETCONF")
but still i am seeing my script is blocked.

**Comment by smrigupt** [comment]
@einarnn, even after passing stream , i am unable to listen to notifications,I am using the following RPC with stream

CREATE_SUBSCRIPTION = '''<?xml version="1.0" encoding="UTF-8"?>
  <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="{}">
    <create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
      <stream>OPENROADM</stream>
    </create-subscription>
  </rpc>'''
and also i have tried with
m.create_subscription(stream_name="NETCONF")
but still i am seeing my script is blocked.

**Comment by smrigupt** [comment]
@einarnn even after passing stream , i am unable to listen to notification when alarm is raising.
m.create_subscription(stream_name="OPENROADM").

I am able to listen to notification right after using edit operation for some configuration, but not when i am raising alarm. Could u pls help?

**Comment by einarnn** [comment]
If you are able to provide a simple, short example of your script, I may be able to provide some review comments. However, without access to the device it will be hard to provide detailed comments or advice.

Cheers,

Einar

**Comment by einarnn** [comment]
Assuming that this issue is no longer live; closing.

**Comment by dadivenkat** [comment]
This is a issue. Sometimes the notifications are getting fetched and sometimes not fetching at all.
Please let me know whether I can change the implementation and check or need to contribute to this take_notification

**Comment by einarnn** [comment]
@dadivenkat, happy for you to contribute! Maintaining backwards compatibility for APIs is preferred.
