### ISSUE TITLE
RPCError: add support for app-tag and accessing multiple errors

### ISSUE THREAD

**Issue by wivory** [ncclient/ncclient#408]
RPCError should provide access to the error-app-tag element, and also access to the individual errors when a returned RPCError contains multiple errors.

**Comment by wivory** [comment]
@einarnn - thanks for merging.  Should I close the issue, or should a maintainer do that?  Also, any idea when you might release the next version?

**Comment by einarnn** [comment]
William,

As far as I'm concerned, you can close the issue yourself with a reference to the commit that resolved the issue. I should be doing a release this week or next.

Nice interacting again!

Cheers,

Einar

**Comment by wivory** [comment]
Resolved by commits in pull request #409.

**Comment by wivory** [comment]
Done.  Can you let me know when the release is done as I have a local
debian-packaged version that I will update (or see if I can persuade
the 'public' debian-packaged-version maintainer to update to latest for
Debian10 / Ubuntu 1804/2004.
Thanks,
William

**Comment by einarnn** [comment]
@wivory , release 0.6.8 should be on PyPi now. See [here](https://pypi.org/project/ncclient/).
