### ISSUE TITLE
How about developing feature that make ncclient support CLI 

### ISSUE THREAD

**Issue by fredgan** [ncclient/ncclient#413]
Hi Einar @einarnn  I have an idea that if we can make ncclient a command line tool, which can send some simple request on command line. How do you think about it? I would like to do it.

BTW, I have send you two emails, but not replied, so I am not sure whether you received or not.

**Comment by einarnn** [comment]
Fred,

There are already two CLI tools based on ncclient. Look for “netconf-console” and “ncc” on PyPi.

Cheers,

Einar
