### ISSUE TITLE
Special device connect: after login terminal to input 'xml' to switch netconf session  

### ISSUE THREAD

**Issue by joysboy** [ncclient/ncclient#42]
Hi Leopoul
  My device is very special. I have to login terminal over ssh, then input some commands to switch in netconf session. How can i do?

1.use 'handle_connection_exceptions' do it? 
https://github.com/leopoul/ncclient/blob/master/ncclient/devices/default.py#L208
```python
    def handle_connection_exceptions(self, sshsession):
        c = sshsession._channel = sshsession._transport.open_channel(kind="session")
        c.set_name("netconf-command-" + str(sshsession._channel_id))
        c.exec_command("enable")
        c.exec_command("netconf")
        return True
```

2.Or overwrite connect
at first, add 'get_ssh_connect_handler' in device handler, special device hanlder return True
https://github.com/leopoul/ncclient/blob/master/ncclient/devices/default.py#L214
```python
    def get_ssh_connect_handler(self):
        return False
```

then modify connect_ssh
https://github.com/leopoul/ncclient/blob/master/ncclient/manager.py#L112
```python
def connect_ssh(*args, **kwds):
    ...
    device_handler = make_device_handler(device_params)
    ...
    if device_handler.get_ssh_connect_handler():
        import_string = 'ncclient.transport.third_party.'
        import_string += device_params['name'] + '.ssh'
        third_party_import = __import__(import_string, fromlist=['DeviceSSH'])
        session = third_party_import.DeviceSSH(device_handler)
    else:
        session = transport.SSHSession(device_handler)
        session.load_known_hosts()

    session.connect(*args, **kwds)
    return Manager(session, device_handler, **kwds)
```

at last, add special device transport third_party
ncclient/transport/third_party/my_device/ssh.py
```python
class DeviceSSH(SSHSession):

    def __init__(self, device_handler):
        super(DeviceSSH, self).__init__(device_handler)

    def connect():
        ...
```

What is the best way to do it?

Thanks

**Comment by leopoul** [comment]
Hi,
Have you resolved this issue?
The most "clean" solution is the last one. A different device handler.
Do you need to establish connection with the device first and then enable NETCONF? Otherwise, I would suggest an ssh config file with ProxyCommand.

Best,
Leo
