### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by stevebail** [ncclient/ncclient#421]
Any plans to support TLS 1.2/1.3?
If not, any suggestions to "add" TLS to the ncclient library?
Thanks.

**Comment by einarnn** [comment]
> Any plans to support TLS 1.2/1.3?
> 
> If not, any suggestions to "add" TLS to the ncclient library?
> 
> Thanks.

No, no active plans to add TLS support. Please feel free to propose its addition via a pull request.

Cheers,

Einar

**Comment by nickbroon** [comment]
Possible duplicate of #271  ?

**Comment by einarnn** [comment]
@nickbroon, yes, a duplicate of #271. Closing this one off.
