### ISSUE TITLE
Latest release?

### ISSUE THREAD

**Issue by badguy99** [ncclient/ncclient#422]
Hi,
Which is the latest release we should be using? 
Looking at https://github.com/ncclient/ncclient/releases/tag/v0.6.8 it has the "latest release" tag, however it also says "pulled due to accidental breaking API change" even though it is still downloadable.
So I'm confused as to what to use at the moment...

Thanks,
Guy

**Comment by fredgan** [comment]
Hi,
0.6.9 is the latest release. https://github.com/ncclient/ncclient/releases/tag/v0.6.9

**Comment by einarnn** [comment]
Sorry for the confusion. I have deleted the release in github also now. The release was initially pulled from PyPi.
