### ISSUE TITLE
url option is missing for edit-config 

### ISSUE THREAD

**Issue by babukt** [ncclient/ncclient#431]
"URL-based config content" support is missing in class [EditConfig(RPC):](https://github.com/ncclient/ncclient/blob/master/ncclient/operations/edit.py#L29) 

Snippet from ietf-netconf.yang

https://github.com/mbj4668/pyang/blob/master/modules/ietf/ietf-netconf.yang#L514

      choice edit-content {
        mandatory true;
        description
          "The content for the edit operation.";

        anyxml config {   
          description
            "Inline Config content.";
        }
        leaf url {  ** >> Support is missing for this**
          if-feature url;
          type inet:uri;
          description
            "URL-based config content.";
        }
      }

Currently, [url](https://github.com/ncclient/ncclient/blob/master/ncclient/operations/edit.py#L49) is added for target, but the supported [target](https://github.com/mbj4668/pyang/blob/master/modules/ietf/ietf-netconf.yang#L429) is either "running" or "candidate".

**Comment by fredgan** [comment]
@einarnn Hi Einar, this issue can be closed. Or you can add me as a assitant to you to this project(Since you have considered my email for quite a long time), I will help do some little fix and management.

**Comment by einarnn** [comment]
#434 resolves this.
