### ISSUE TITLE
support for new RPC's 

### ISSUE THREAD

**Issue by harshad1692** [ncclient/ncclient#437]
can we parse xml file to ncclient?

**Comment by einarnn** [comment]
@harshad1692 , I'm not exactly clear what the expectation here is? Does your CLI command `create /users/user` have a YANG model behind it? Are you asking how to define a YANG model that allows this? Or...?

**Comment by einarnn** [comment]
@harshad1692, sorry, this question doesn't make sense. Please try raising a more fully described issue.
