### ISSUE TITLE
Multi-device transactional behavior

### ISSUE THREAD

**Issue by elpatopedraza** [ncclient/ncclient#440]
Hello,

Currently you have a manager that returns a single connection per device.

Do we have any chance to create a multi-session (multiple devices) to orchestrate configuration loads and rollbacks just in case one of the devices fail?

**Comment by einarnn** [comment]
@elpatopedraza, the `ncclient` library allows you to connect to as many devices as you wish and interact with each of then individually. It's not 100% clear to me what you are trying to achieve, but I think that what you are trying to do is work with multiple devices to deliver an end-to-end network level configuration. For example, create an MPLS VPN with multiple sites, requiring you to configure multiple devices, and, if any configuration on any **one** device fails, rollback the associated config changes on **all** devices.

Assuming so, `ncclient` doesn't do this out of the box, but provides the building blocks assuming the network devices support the appropriate optional NETCONF features, namely:

- candidate datastore
- confirmed commit

With these features it is possible to, for example, make the individual changes on each device, doing a confirmed commit on each device with an appropriate timeout, and, once all devices are configured "successfully", and you have tested the end-to-end behavior, you confirm all the commits. If the configuration failed on a specific device or the end-to-end config didn't work as required, then you can either explicitly cancel the confirmed commits, or let them expire, at which point the configurations will automatically roll back per RFC 6241 definitions.

Does this help? Assuming so, the orchestration above is, as I said, **not** provided by `ncclient`, but is provided by some commercial products.

Cheers,

Einar

**Comment by einarnn** [comment]
No issue here with `ncclient` as far as I can tell.
