### ISSUE TITLE
edit_config() giving RPC Error 

### ISSUE THREAD

**Issue by harshad1692** [ncclient/ncclient#441]
```
snippet = '''<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
                <users>
                  <user>
                    <name>rakesh</name>
                  </user>
                </users>
            </config>'''
```

**code**

```
with manager.connect(host=HOST, port=PORT, username=USER, password=PASS,hostkey_verify=False, device_params={'name': 'default'},look_for_keys=False, allow_agent=False) as m:
    pid = "IQ,d4668"
    assert(":candidate" in m.server_capabilities)
    assert(":validate"  in m.server_capabilities)
    with m.locked(target='candidate'):
      d = m.discard_changes()
      c = m.edit_config(config=snippet)
      v = m.validate()
      m.commit(confirmed=True, timeout="10", persist=pid)
      print ("Running the tests")
      time.sleep(5)
      print ("Committing")
      res = m.commit(confirmed=True)
      m.commit()
```

**Error**

```
Traceback (most recent call last):
  File "user_mgmt_1.py", line 57, in <module>
    test_edit_config()
  File "user_mgmt_1.py", line 47, in test_edit_config
    c = m.edit_config(config=snippet)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/operations/edit.py", line 65, in request
    return self._request(node)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/operations/rpc.py", line 347, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: unknown object
```

why is it coming am clueless, or is it am doing something wrong as am new to this netconf

**Comment by fredgan** [comment]
Hi @harshad1692,
The requests you sent appears to be invalid, so the Server responded with an error. Maybe you can refer to [Chapter 7.2](https://tools.ietf.org/html/rfc6241#section-7.2)

**Comment by harshad1692** [comment]
if i get some example that would be great help

**Comment by einarnn** [comment]
@harshad1692, examples are hard to provide without knowing what models the netconf server you are connecting to supports. Suggest you look at the relevant RFCs (6020, 6241, 7950) as the `ncclient` library does assume a working knowledge of both NETCONF and YANG. If you are able to construct requests that **should** be valid for the netconf server you are connecting to, but are still having problems with `ncclient`, please come back here.

What I can also suggest is that a good way to learn is to do a `get_config` on `running`. That will return the current configuration of the netconf server you are connecting to, and then you can try incremental modifications to that configuration.

However, there appears to be no issues with `ncclient` here, so I am closing the issue for now.
