### ISSUE TITLE
edit config raising issue while parsing xml file

### ISSUE THREAD

**Issue by harshad1692** [ncclient/ncclient#449]
if we parse xml as a string directly from edit config am able to configure, but when I am trying to parse xml file am facing error as below

Traceback (most recent call last):
  File "net_ietf.py", line 76, in <module>
    test_interface_config('enp19s0.50', '50')
  File "net_ietf.py", line 67, in test_interface_config
    c = m.edit_config(config=xml_interface_string())
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/operations/edit.py", line 65, in request
    return self._request(node)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/operations/rpc.py", line 347, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: invalid value

**xml file data**
```

<?xml version="1.0" ?><config ncx:etag="1823" ncx:last-modified="2020-11-04T06:55:43Z" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:ncx="http://netconfcentral.org/ns/yuma-ncx">
              <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
                <interface>
                  <name>enp19s0.50</name>
                  <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:l2vlan</type>
                  <enabled>true</enabled>
                  <base-interface xmlns="urn:o-ran:interfaces:1.0">enp19s0</base-interface>
                  <vlan-id xmlns="urn:o-ran:interfaces:1.0">50</vlan-id>
                </interface>
              </interfaces>
            </config>
```

any lead on this will be great help

**Comment by einarnn** [comment]
@harshad1692, you need to look in more detail at the contents of the RPCError exception. With the information you have provided above it's not possible to suggest what the issue may be.

**Comment by harshad1692** [comment]
@einarnn I tired to look into, but was clueless because when I hardcoded the the same xml in edit config its working as expected, but while parsing file getting issue (**invalid value**)

**Comment by einarnn** [comment]
It is most likely an issue to do with how ncclient manipulates XML content when the default namespace of the `config` tag passed to it has the default namespace set to `urn:ietf:params:xml:ns:netconf:base:1.0`. You could try making your XML file content look like this instead:

```
<?xml version="1.0" ?>
<nc:config ncx:etag="1823" ncx:last-modified="2020-11-04T06:55:43Z" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:ncx="http://netconfcentral.org/ns/yuma-ncx">
  <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
    <interface>
      <name>enp19s0.50</name>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:l2vlan</type>
      <enabled>true</enabled>
      <base-interface xmlns="urn:o-ran:interfaces:1.0">enp19s0</base-interface>
      <vlan-id xmlns="urn:o-ran:interfaces:1.0">50</vlan-id>
    </interface>
  </interfaces>
</nc:config>
```

This **might** help.
