### ISSUE TITLE
calling user defined RPC 

### ISSUE THREAD

**Issue by harshad1692** [ncclient/ncclient#454]
How can we call user defined rpc from ncclient

any lead will be highly appreciated.

**Comment by fredgan** [comment]
@harshad1692 , 
maybe you can use `m.rpc()` to call user defined rpc.
example:
```
from ncclient import manager, operations

config_data = """
    <config>
        <cont xmlns="urn:mod1">
            <le1>one-data</le1>
            <le2>two-data</le2>
        </cont>
    </config>
    """

config_data2 = """
    <filter type="subtree">
        <cont xmlns="urn:mod1"/>
    </filter>
    """

def devices_connect(host, port, user, password):
    return manager.connect(host=host,
                           port=port,
                           username=user,
                           password=password,
                           hostkey_verify = False,
                           device_params={'name': "junos"},
                           allow_agent=False,
                           look_for_keys=False)

def demo(host, port, user, password):
    with devices_connect(host, port=port, user=user, password=password) as m:
        # use `rpc` to send user defined rpc commands.
        a = m.rpc("edit-config", target="candidate", config=config_data)
        print(a)
        print("-------------------------------")

        b = m.rpc("get-config", source="candidate", filter=config_data2)
        print(a)
        print("-------------------------------")

        a = m.rpc("copy-config", target="running", source="candidate")
        print(a)
        print("-------------------------------")

if __name__ == '__main__':
    demo(host, port, username, password)
```

**Comment by harshad1692** [comment]
@fredgan ok let me try this

**Comment by harshad1692** [comment]
Hi @fredgan 

if i use this rpc or dispatch
am getting same error as below

File "trace_module.py", line 66, in <module>
    sys.exit(trace())
  File "trace_module.py", line 54, in trace
    c = m.dispatch(snippet, source='running')
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/operations/retrieve.py", line 233, in request
    node = new_ele(rpc_command)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/xml_.py", line 227, in <lambda>
    new_ele = lambda tag, attrs={}, **extra: etree.Element(qualify(tag), attrs, **extra)
  File "src/lxml/lxml.etree.pyx", line 2998, in lxml.etree.Element (src/lxml/lxml.etree.c:80607)
  File "src/lxml/apihelpers.pxi", line 105, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17198)
  File "src/lxml/apihelpers.pxi", line 1626, in lxml.etree._tagValidOrRaise (src/lxml/lxml.etree.c:35069)
**ValueError: Invalid tag name ' <xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><status xmlns="urn:o-ran:trace:1.0"></status><start-trace-logs></start-trace-logs>'**

xml which am parsing 
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:ncx="http://netconfcentral.org/ns/yuma-ncx">				<status xmlns="urn:o-ran:trace:1.0"></status>
<start-trace-logs></start-trace-logs>
</rpc>
```

**Comment by einarnn** [comment]
Please refer to the resolution for #463 and see if that also resolves your issue here.

Cheers,

Einar

**Comment by einarnn** [comment]
Assuming that this issue is no longer live; closing.
