### ISSUE TITLE
Xpath filtering with tuple containing a dict of namespace and expression

### ISSUE THREAD

**Issue by dipankarshaw** [ncclient/ncclient#464]
Filter parameters
Where a method takes a filter argument, it can take on the following types:

A tuple of (type, criteria).

Here type has to be one of “xpath” or “subtree”.

For “xpath” the criteria should be a string containing the XPath expression or a tuple containing a dict of namespace mapping and the XPath expression.

here, on a Cisco XE device, i used the only expression way by specifying my code as below. **which works fine.**

netconf_reply = m.get(filter=('xpath',"//interfaces-state/interface[name='GigabitEthernet1']/oper-status"))

{'rpc-reply': {'@message-id': 'urn:uuid:1e006fe0-46a8-4e81-8a61-cb4aa64e42e5',
               '@xmlns': 'urn:ietf:params:xml:ns:netconf:base:1.0',
               '@xmlns:nc': 'urn:ietf:params:xml:ns:netconf:base:1.0',
               'data': {'interfaces-state': {'@xmlns': 'urn:ietf:params:xml:ns:yang:ietf-interfaces',
                                             'interface': {'name': 'GigabitEthernet1',
                                                           'oper-status': 'up'}}}}}

_______________________________________________________________________________

But How i can utilize the other option like mentioning "a tuple containing a dict of namespace mapping and the XPath expression."
can you give me an example of that code using my above output. i mean to ask, how i should form the filter 
i tried below, but not working.

netconf_reply = m.get(filter=('xpath',({'xmlns': 'urn:ietf:params:xml:ns:yang:ietf-interfaces','select': "//interfaces-state/interface[name='GigabitEthernet1']/oper-status"})))

error message : 
   netconf_reply = m.get(filter=('xpath',({'xmlns': 'urn:ietf:params:xml:ns:yang:ietf-interfaces','select': "//interfaces-state/interface[name='GigabitEthernet1']/oper-status"})))
  File "/usr/local/lib/python3.6/dist-packages/ncclient/manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/ncclient/operations/retrieve.py", line 83, in request
    node.append(util.build_filter(filter))
  File "/usr/local/lib/python3.6/dist-packages/ncclient/operations/util.py", line 54, in build_filter
    rep.attrib["select"] = criteria
  File "src/lxml/etree.pyx", line 2429, in lxml.etree._Attrib.__setitem__
  File "src/lxml/apihelpers.pxi", line 593, in lxml.etree._setAttributeValue
  File "src/lxml/apihelpers.pxi", line 1538, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'dict

**Comment by dipankarshaw** [comment]
I could solve this, by checking the resolution of Issue no #166 
Sample code : 
                oc_namespace = {"oc-if": "http://openconfig.net/yang/interfaces"}
                oc_select = "/oc-if:interfaces/oc-if:interface/oc-if:state/oc-if:admin-status"
                oc_netconf_reply = m.get(filter=("xpath", (oc_namespace,oc_select)))
                oc_intf_details = xmltodict.parse(oc_netconf_reply.xml)
                oc_output_dict = json.loads(json.dumps(oc_intf_details))
                pprint(oc_output_dict['rpc-reply']['data'])

**Comment by einarnn** [comment]
Cool. I was going to refer you to the sample code if I could find it 👍  I will close this issue.

Cheers,

Einar

**Comment by devopsnetworks** [comment]
It's working Perfectly. @dipankarshaw
