### ISSUE TITLE
Custom save does not work when config is locked

### ISSUE THREAD

**Issue by stvnkem** [ncclient/ncclient#469]
Hi,

I found an error that I cannot overcome.
The built in copy_config fails very often because it takes the device long to save it.
I want to use a custom RPC call with the appropriate delay based on the device hostname (which ultimately identifies the device type).
I do lock the candidate before changing it. I noted that even after unlocking the candidate, the custom RPC call fails with the error: `ncclient.transport.errors.TransportError: Not connected to NETCONF server`

I do  not see the session close or kill when debugging the RPC calls on the device when the custom save make the script fail.
The config gets saved though, just the script reports the device as "failed to change".
I do see the session close when I use the built in copy_config. This however, only works for the 1U devices, not for the chassis type nodes. Without the `with conn.locked(target='candidate'):` the custom save function works fine.

How can I solve that? The relevant script is:
No matter if the custom save is outside of the "lock" block, it fails with the same error.

```
def custom_save_nc(conn, hostname):
    from time import sleep
    save_cfg = f'''<rpc message-id="{generate_message_id()}" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
                 <copy-config>
                  <target>
                   <startup/>
                  </target>
                  <source>
                   <running/>
                  </source>
                 </copy-config>
                </rpc>'''
    conn._session.send(save_cfg)
    if '-r-xx-' in hostname:
        sleep(4)
    elif '-r-zz-' in hostname:
        sleep(25)
    else:
        sleep(35)    


with manager.connect(host=hostname, port=port, username=username, password=password, hostkey_verify=False,
                         device_params={'name': "huawei"}, allow_agent=False, look_for_keys=False,
                         timeout=15) as conn:
        with conn.locked(target='candidate'):
            try:
                res = get_cfg_nc(conn, hostname, get_config_intfDescr_fil, dict_constructor=dict)
            except operations.errors.TimeoutExpiredError:
                logging.error(f'Timeout while executing calls {hostname}.')
            else:
                try:
                    deploy_cfg_candidate_nc(conn, hostname, correct_intf_descr(res), 'intf_descr')
                except operations.errors.TimeoutExpiredError:
                    logging.error(f'Timeout while executing calls {hostname}.')
                else:
                    try:
                        conn.commit()
                    except operations.errors.TimeoutExpiredError:
                        logging.error(f'Timeout while executing commit {hostname}.')
        custom_save_nc(conn=conn, hostname=hostname)
```

**Comment by stvnkem** [comment]
I found a possible workaround, but it is ugly :(

```
    with manager.connect(host=hostname, port=port, username=username, password=password, hostkey_verify=False,
                         device_params={'name': "huawei"}, allow_agent=False, look_for_keys=False,
                         timeout=15) as conn:
        with conn.locked(target='candidate'):
            try:
                res = get_cfg_nc(conn, hostname, get_config_intfDescr_fil, dict_constructor=dict)
            except operations.errors.TimeoutExpiredError:
                logging.error(f'Timeout while executing calls {hostname}.')
            else:
                try:
                    deploy_cfg_candidate_nc(conn, hostname, correct_intf_descr(res), 'intf_descr')
                except operations.errors.TimeoutExpiredError:
                    logging.error(f'Timeout while executing calls {hostname}.')
                else:
                    try:
                        conn.commit()
                    except operations.errors.TimeoutExpiredError:
                        logging.error(f'Timeout while executing commit {hostname}.')
                    else:
                        **with manager.connect(host=hostname, port=port, username=username, password=password,
                                             hostkey_verify=False,
                                             device_params={'name': "huawei"}, allow_agent=False, look_for_keys=False,
                                             timeout=15) as conn:
                            custom_save_nc(conn, hostname)**
```

**Comment by einarnn** [comment]
@stvnkem, this looks like a vendor-specific issue. I'm not sure that ncclient can do anything specific here to help, can it?

**Comment by stvnkem** [comment]
> @stvnkem, this looks like a vendor-specific issue. I'm not sure that ncclient can do anything specific here to help, can it?
> 

@einarnn I am not sure. I am from the vendor. I did some debugging and the device always responses to the custom RPC calls, but printing the response conn._session.send(custom_messahe) returns None. Is it normal?

I am going to do some more debugs together with our R&D support.

**Comment by einarnn** [comment]
Closing this issue as it has been inactive since January.

**Comment by nagarajsg** [comment]
what is the need of locked() operation where there is lock() operation already in ncclient?

**Comment by einarnn** [comment]
It allows idiomatic Context Manager Python code to be written. When you have code like:

```
with conn.locked(target='candidate'):
    conn.edit_config(...)
    conn.edit_config(...)
    conn.edit_config(...)
```

...all the `edit_config` operations will be done with the candidate config locked, and once the `with` block is exited the candidate config will be automatically unlocked.

Take a look at:

    https://docs.python.org/3/reference/compound_stmts.html#the-with-statement

...for more context if you're not familiar with context managers in Python.

**Comment by nagarajsg** [comment]
thanks einarnn
