### ISSUE TITLE
RPC reply is fragmented, how to use get next if supported?

### ISSUE THREAD

**Issue by stvnkem** [ncclient/ncclient#471]
Hello,

There are some query commands that return a large amount of data. Huawei device breaks the data down and returns only the first part. According to the developers, we I need to query the next batch based on the `set-id`
How can I do that? The mode I use is "huawei". When using "huaweiyang" there is no such a problem, or at least I have not met it yet.

```
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:abce3f47-a667-4fd2-808b-ff51df006512" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" set-id="76101">
  <data>
    <qos xmlns="http://www.huawei.com/netconf/vrp" format-version="1.0" content-version="1.0">
```

**Comment by stvnkem** [comment]
My colleague suggested to check [this ](https://github.com/ctlaltlaltc/ncclient/blob/904656abb2879d651225f112304c0f432de1b9e4/examples/hw01.py#L122)issue. This could be a solution for get config, but not for query data.

**Comment by earies** [comment]
This method of "get-next" is proprietary (non-standard) and would need implementation within the huawei device libraries much like is suggested/prototyped in the fork you reference above.  I would suggest anyone with access to huawei devices (or any huawei developers) to submit PRs for further review

**Comment by stvnkem** [comment]
> This method of "get-next" is proprietary (non-standard) and would need implementation within the huawei device libraries much like is suggested/prototyped in the fork you reference above. I would suggest anyone with access to huawei devices (or any huawei developers) to submit PRs for further review

Hey!

I have access to Huawei devices, but my coding skills are insufficient. How can I send a PR?

**Comment by einarnn** [comment]
@stvnkem, there are several examples in the `ncclient` code base to see how to implement custom RPCs, and there are many tutorials online for how to submit pull requests via GitHub. This isn't really an `ncclient` issue, so I will close this issue.
