### ISSUE TITLE
conn._session.send() does not return any output

### ISSUE THREAD

**Issue by stvnkem** [ncclient/ncclient#473]
Hello,

I usually use this command to execute an action. In that case I do not really care about the reply. There is always a way to verify the operation. However, I need to query a firewall session table, but the GET operation is not supported.
I must send a custom RPC message. If I print the reply after sleeping for a while (10 seconds should be more than enough) I always get `None`. I tested the same call with MG NetconfBrowser, wit that it worked. What should I do?

**Comment by einarnn** [comment]
Don't use `conn._session.send()`! 😉 This is a private method, and the implementation just transfers a message onto another thread for execution. If you need to send a custom RPC message, you have a couple of options:

- Create your own custom device handler with appropriate functions. It is now possible to create a device handler that isn't part of the ncclient library. Just define one that has the default device handler as its base class. Yiou can see how to implement custom RPCs from existing device handlers.
- Construct your own RPC using the new [`rpc`](https://github.com/ncclient/ncclient/blob/master/ncclient/manager.py#L286-L292) function.
-

**Comment by einarnn** [comment]
> Don't use `conn._session.send()`!

To expand slightly, by convention variable that start with `_`, like `_session` are considered private to the implementation and should not be depended on as they may change between releases.
