### ISSUE TITLE
url encoding problem on windows

### ISSUE THREAD

**Issue by asaforoneh** [ncclient/ncclient#476]
We see different behavior on windows & linux. when running a request with the following data inside:

start_app = """
    <edit-config>
    <target>
      <candidate/>
    </target>
    <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
      <appmgr xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-appmgr-cfg">
        <applications>
          <application>
            <name>app1.0.0.107</name>
            <activate>
              <type>docker</type>
              <source>app1.0.0.107</source>
            </activate>
          </application>
        </applications>
      </appmgr>
    </config>
  </edit-config>
"""
It works just fine when client runs on linux but on windows we get the following  error:

Invalid application name: Application name 'dpro-1%2e0%2e0%2e107' must match the pattern '^[a-zA-Z0-9][a-zA-Z0-9_.-]+$'

The value was urlencoded on windows. Is there a way to avoid it ?

**Comment by earies** [comment]
Will assume this issue was opened in error against the wrong repo - if you have an ncclient issue, reopen describing exact issue in detail
