### ISSUE TITLE
urn:ietf:params:xml:ns:netconf:base:1.0  does not meet requirement

### ISSUE THREAD

**Issue by lu-li-xin** [ncclient/ncclient#497]
python==3.6
ncclient==0.6.12

```
snippeet="""<rpc message-id ="101" 
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"  
xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">   
<edit-config> <target> <running/> </target>     
<config>       
<top xmlns="http://www.h3c.com/netconf/config:1.0" xc:operation="create">
        <OMS>
            <IPv4Groups>
                <Group>
                    <Name>H3C_deny_group</Name>
                    <Description>this deny group</Description>
                </Group>
            </IPv4Groups>
        </OMS>
    </top>    
		</config>   
	</edit-config> 
</rpc> 
```

error: 
Get the following error:

Traceback (most recent call last):
  File "testncclient.py", line 31, in <module>
    m.edit_config(target='running', config=snippet)
  File "/Library/Python/3.6/site-packages/ncclient/manager.py", line 156, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/Library/Python/3.6/site-packages/ncclient/manager.py", line 226, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/Library/Python/3.6/site-packages/ncclient/operations/edit.py", line 62, in request
    node.append(validated_element(config, ("config", qualify("config"))))
  File "/Library/Python/3.6/site-packages/ncclient/xml_.py", line 111, in validated_element
    raise XMLError("Element [%s] does not meet requirement" % ele.tag)
ncclient.xml_.XMLError: Element [{urn:ietf:params:xml:ns:netconf:base:1.0}rpc] does not meet requirement

**Comment by lu-li-xin** [comment]
<rpc message-id ="101" 
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"  
xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">   
	<edit-config>     
			<target>       
			<running/>     
			</target>     
		<config>       
			  <top xmlns="http://www.h3c.com/netconf/config:1.0" xc:operation="create">
        <OMS>
            <IPv4Groups>
                <Group>
                    <Name>H3C_deny_group</Name>
                    <Description>this deny group</Description>
                </Group>
            </IPv4Groups>
        </OMS>
    </top>    
		</config>   
	</edit-config> 
</rpc>

**Comment by lu-li-xin** [comment]
<rpc message-id ="101" 
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"  
xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">   
	<edit-config>     
			<target>       
			<running/>     
			</target>     
		<config>       
			  <top xmlns="http://www.h3c.com/netconf/config:1.0" xc:operation="create">
        <OMS>
            <IPv4Groups>
                <Group>
                    <Name>H3C_deny_group</Name>
                    <Description>this deny group</Description>
                </Group>
            </IPv4Groups>
        </OMS>
    </top>    
		</config>   
	</edit-config> 
</rpc> 

-

**Comment by einarnn** [comment]
You probably want to try something more like:

```
from ncclient import manager

snippet = '''
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <top xmlns="http://www.h3c.com/netconf/config:1.0" operation="create">
    <OMS>
      <IPv4Groups>
        <Group>
          <Name>H3C_deny_group</Name>
          <Description>this deny group</Description>
        </Group>
      </IPv4Groups>
    </OMS>
  </top>    
</config>
'''

m = manager.connect(...)
response = m.edit_config(target='running', config=snippet)
```

This is because `manager.edit_config()` expects to get
