### ISSUE TITLE
nccclient with other yang simulators

### ISSUE THREAD

**Issue by rkkilari** [ncclient/ncclient#501]

**Comment by rkkilari** [comment]
Yes it worked. I could execute get and get-config requests against the toaster simulator. I am struggling to run edit-config command using ncclient. Here is my code and am getting rpc error.
ncclient code --->
.....

value = '''
<config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
    <toaster xmlns="http://netconfcentral.org/ns/toaster">
          <darknessFactor nc:operation="replace">750</darknessFactor>
    </toaster>
</config>
'''

print (eos.edit_config(target="running", config=value, default_operation="none"))
...

Below command works from ssh.

<rpc message-id="m-9" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <edit-config>
        <target>
            <running/>
        </target>
        <config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
            <toaster xmlns="http://netconfcentral.org/ns/toaster">
                <darknessFactor nc:operation="replace">750</darknessFactor>
            </toaster>
        </config>
    </edit-config>
</rpc> 
]]>]]>

What I am missing in ncclient code? I suspect it is XML but I could not figure out

**Comment by rkkilari** [comment]
finally below code worked for me. It may help someone!! I have to remove **operation=replace**. How ncclient spports merge/replace operations? 

```
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <toaster xmlns="http://netconfcentral.org/ns/toaster">
          <darknessFactor>750</darknessFactor>
    </toaster>
</config>
```

**Comment by einarnn** [comment]
Merge is the default. You can pass an operation value to the edit config call that applies to entire payload.
