### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Zero960612** [ncclient/ncclient#504]
when I use it at arm, I used command "from ncclient import manager",then command window had no reaction . It had no error report, at the same time ,it also cannot pass ,just had no reaction. I tried to use ctrl+C, but it didn't work, even command"exit()" couldn't exit. I hope someone can help me,thanks!

**Comment by einarnn** [comment]
There isn't enough information here to comment on. Closing this issue out. Please reopen if you want to add more information, such as platform, Python version, etc.
