### ISSUE TITLE
use filter to get data from get_config

### ISSUE THREAD

**Issue by Zero960612** [ncclient/ncclient#506]
I wanted to use 'filter' to get data which is what I wants, so I used this code to do that:

```
a="""
<filter>
    <node xmlns=http://...>
        <node-name></node-name>
    </node>
</filter>"""
FILTER=("subtree",a)

filtered = m.get_config('running',FILTER)
print(filtered)
```

but it didn't work ,I mean the result is not I want, The result is :
`<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:67a51535-a7ca-4630-858b-b1db497e6288" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><data></data></rpc-reply>`

**Comment by einarnn** [comment]
Assuming that this issue is no longer live; closing.
