### ISSUE TITLE
Lack of "message-id" in notifications

### ISSUE THREAD

**Issue by dcichy90** [ncclient/ncclient#507]
Hi. I would like to ask why exception is raised for lack of "message-id" in notification messages.
Based on examples from: https://datatracker.ietf.org/doc/html/rfc5277 we can see lack of message-id for notification.
Message-id is mandatory only in rpc and rpc-reply: https://datatracker.ietf.org/doc/html/rfc6241. There is no information about mandatory "message-id" for notifications. 

Example of notification:
```
   <notification
      xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
      <eventTime>2007-07-08T00:01:00Z</eventTime>
      <event xmlns="http://example.com/event/1.0">
         <eventClass>fault</eventClass>
         <reportingEntity>
             <card>Ethernet0</card>
         </reportingEntity>
         <severity>major</severity>
       </event>
   </notification>

```

Current implementation:
-  module: operations/rpc.py:
-  class: RPCReplyListener
-  method: callback

```
def callback(self, root, raw):
    ...
    if "message-id" not in attrs:
        # required attribute so raise OperationError
        raise OperationError("Could not find 'message-id' attribute in <rpc-reply>")
    ...
```

Modifications to make it working on system tested by me:

```
def callback(self, root, raw):
    ...
        if "message-id" not in attrs:
            if "rpc-reply" in tag:
                # required attribute so raise OperationError
                raise OperationError("Could not find 'message-id' attribute in <rpc-reply>")
    ...
```

I would like to use your library without local changes and be up to date. I suggest to change it or add parameter to configuration which give us a possibility to allow receiving notification without "message-id".

**Comment by einarnn** [comment]
Put this is the waiting state for any further feedback from @dcichy90.

**Comment by einarnn** [comment]
Assuming that this issue is no longer live; closing. Please reopen if this is not the case.
