### ISSUE TITLE
manager.connect, ssh_config, support to include 'stricthostkeychecking'

### ISSUE THREAD

**Issue by jeremyschulman** [ncclient/ncclient#51]
reference ver: 0.4.3.
Using manager.connect with `ssh_config="~/.ssh/config"`, for example, ncclient does not currently look at the 'stricthostkeychecking' option.  Meaning if the ssh config file has this value set to no, ncclient _still_ requires the use of `hostkey_verify=False`

It would be nice if ncclient would import this value.  

Thoughts?  I can make this change/fork/pull if this is an agreeable approach.

**Comment by vincentbernat** [comment]
I was thinking the same thing but `StrictHostKeyChecking` has 3 values: `yes`, `no` and `ask`. It defaults to `ask` and even when set to `no`, it would fail if the key has changed. So, the semantic is a bit different.
