### ISSUE TITLE
ncclient.manager.call_home is showing cannot assign request error.

### ISSUE THREAD

**Issue by vaibhav1713109** [ncclient/ncclient#515]
Hi @einarnn  
I am using call home but it show below error.
def Call_Home():

    with manager.call_home(host='192.168.1.10', port=4334, username='root', hostkey_verify=False, password='root') as m:
        print(m.server_capabilities)

after running this script is shows below error.

Traceback (most recent call last):
  File "M_CTC_ID_001.py", line 110, in Call_Home
    with manager.call_home(host=host, port=4334, username=user, hostkey_verify=False, password=pas) as m:
  File "/Python_script/yng/lib/python3.6/site-packages/ncclient/manager.py", line 182, in call_home
    srv_socket.bind((host, port))
OSError: [Errno 99] Cannot assign requested address

**Comment by einarnn** [comment]
@vaibhav1713109, this error would seem to indicate that there is a problem with the IP address you provided. Is `192.168.1.10` a valid address for one of your local interfaces?

**Comment by vaibhav1713109** [comment]
@einarnn 
when we do call home manually we didn't need to give ip detail instead of giving ip we get the ip detail of netopeer-server, so is there any way to get ip details through call_home function?

**Comment by einarnn** [comment]
@vaibhav1713109, it's not 100% clear to me what you are trying to achieve.

The `host` parameter to `call_home` specifies the IP address that you want to listen on for incoming call-home connections. If you wish to listen on any local address, you should specify `0.0.0.0`.

If you wish to determine the IP address of the NETCONF server (netopeer-server) making the call-home request, then that is really abstracted away.

You can access the remote peer's address using:

```
manager._session._transport.sock.getpeername()
```

**But please note that variables prepended with `_` are considered private by convention and thus may change over time.**

**Comment by vaibhav1713109** [comment]
@einarnn 
we manually do listen like this 
vvdn@vvdn:~$ netopeer2-cli 
> listen 
Waiting 60s for an SSH Call Home connection on port 4334...
The authenticity of the host '::ffff:192.168.4.80' cannot be established.
ssh-rsa key fingerprint is 59:9e:90:48:f1:d7:6e:35:e8:d1:f6:1e:90:aa:a3:83:a0:6b:98:5a.
Are you sure you want to continue connecting (yes/no)? no

in reply we get ip and it ask for ssh connection so my question is that how we get this below details using nccleint

:ffff:192.168.4.80'
Are you sure you want to continue connecting (yes/no)? no

**Comment by einarnn** [comment]
@vaibhav1713109, ncclient is intended to be a non-interactive library, not one that asks for inputs in the same way that CLI tools do. If you wish to strictly verify a connecting host, set `hostkey_verify` to True, and ensure that you load the hostkey beforehand for authorized hosts.

**Comment by vaibhav1713109** [comment]
@einarnn It is clear now i am able to get peer name but when i used multiple call home session it shows address already in use error.

i write code like in this way
for _ in range(4):
  m = manager.call_home(host = '', port=4334, hostkey_verify=False,username = 'Operator', password = 'admin123')
  li = m._session._transport.sock.getpeername()   #['ip_address', 'TCP_Port']
  m.close_session()



it shows error address adready in use

**Comment by einarnn** [comment]
@vaibhav1713109, yes, I can see that that is what will happen. There is a defect in how the `call_home` function deal with the bound port, 4334 by default, in that it both leaves that port bound **and** doesn’t provide a way to reuse the server socket.

I can think of a couple of ways to fix this. Would you be open to installing directly from a development branch and testing?

**Comment by einarnn** [comment]
@vaibhav1713109, I've attached a tar.gz file that you can try installing:

[ncclient-0.6.12+12.g8ba4fb3.tar.gz](https://github.com/ncclient/ncclient/files/7814437/ncclient-0.6.12%2B12.g8ba4fb3.tar.gz)

Use a command like `pip install ncclient-0.6.12+12.g8ba4fb3.tar.gz`. Then you can try using `call_home`, which I have now modified to close the listening socket every time it successfully accepts a connection, or use a new function, `call_home_many`, which accepts the same parameters as `call_home`, but instead returns a generator. The returned generator can be used thus:

```python
from ncclient import manager

call_home_listener = manager.call_home_many(
    host='0.0.0.0',
    port=4334,
    hostkey_verify=False,
    username='Operator',
    password='admin123')
while True:
    try:
        m = next(call_home_listener)
        # ...do something with the returned manager...
    except Exception as e:
        # need to decide if the exception is fatal or not
        print(e)
```

I don't have a test setup with a call-home-enabled NETCONF server, so I haven't been able to do anything more than really simple testing, so let me know how it goes.

My preferred approach would be to integrate the new `call_home_many` approach initially, and leave the current `call_home` unchanged.

**Comment by vaibhav1713109** [comment]
@einarnn But I think in call_home function you use srv_socket.close() for closing the socket connection then why it show address already in use.


def call_home(*args, **kwds):
    host = kwds["host"]
    port = kwds.get("port",4334)
    srv_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv_socket.bind((host, port))
    srv_socket.settimeout(10)
    srv_socket.listen()

    sock, remote_host = srv_socket.accept()
    logger.info('Callhome connection initiated from remote host {0}'.format(remote_host))
    kwds['sock'] = sock
    srv_socket.close()
    return connect_ssh(*args, **kwds)

**Comment by vaibhav1713109** [comment]
@einarnn I use the given tar file but its not working

**python code:**
from ncclient import manager



def Call_Home():
    

    call_home_listener = manager.call_home_many(
        host='',
        port=4334,
        hostkey_verify=False,
        username='Operator',
        password='admin123',timeout = 30)
    for i in range(10):
        try:
            m = next(call_home_listener)
            print(m.session_id)
            print(i+1,'th iteration')
            # ...do something with the returned manager...
        except Exception as e:
            # need to decide if the exception is fatal or not
            print(e)

if __name__ == '__main__':
    Call_Home()


Output :

(yng) vvdn@vvdn:~/Python_script/GARUDA_AUTOMATION/M_plane_automation$ python test.py 
16
1 th iteration
timed out

**Comment by einarnn** [comment]
> @einarnn But I think in call_home function you use srv_socket.close() for closing the socket connection then why it show address already in use.
> 
> def call_home(*args, **kwds): host = kwds["host"] port = kwds.get("port",4334) srv_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM) srv_socket.bind((host, port)) srv_socket.settimeout(10) srv_socket.listen()
> 
> ```
> sock, remote_host = srv_socket.accept()
> logger.info('Callhome connection initiated from remote host {0}'.format(remote_host))
> kwds['sock'] = sock
> srv_socket.close()
> return connect_ssh(*args, **kwds)
> ```

The call to `srv_socket.close()` is added in this version.

**Comment by einarnn** [comment]
> @einarnn I use the given tar file but its not working
> 
> **python code:** from ncclient import manager
> 
> def Call_Home():
> 
> ```
> call_home_listener = manager.call_home_many(
>     host='',
>     port=4334,
>     hostkey_verify=False,
>     username='Operator',
>     password='admin123',timeout = 30)
> for i in range(10):
>     try:
>         m = next(call_home_listener)
>         print(m.session_id)
>         print(i+1,'th iteration')
>         # ...do something with the returned manager...
>     except Exception as e:
>         # need to decide if the exception is fatal or not
>         print(e)
> ```
> 
> if **name** == '**main**': Call_Home()
> 
> Output :
> 
> (yng) vvdn@vvdn:~/Python_script/GARUDA_AUTOMATION/M_plane_automation$ python test.py 16 1 th iteration timed out

The timeout is expected given the code if a netconf agent does call within 10 seconds.

**Comment by vaibhav1713109** [comment]
@einarnn Okay I have to implement code in given flow:
call_home --->kill_previous_session ---> connect_ssh ----> configure rpc ---> call_home --->kill_last_session.

**Code For above flow**:: some time its working fine but some time it through error address already in use.
`from logging import exception
import time
from ncclient import manager
from ncclient.operations.rpc import RPCError
from six import with_metaclass
import xmltodict
import xml.dom.minidom
from netconf_client.log import logger
import paramiko


# Killing Session
def kill_ssn(host, port, user, password,sid):
    with manager.connect(host=host, port=port, username=user, hostkey_verify=False, password=password) as m:
        return m.kill_session(sid)  



# Merge a new user 
def Create_user(host, port, nam, pas1):
    
    with manager.connect(host=host, port=port, username='root', hostkey_verify=False, password='root') as m:

        
        print('-'*100)
        print('\n\n\t\t********** Connect to the NETCONF Server ***********\n\n')
        print('-'*100)
        print("Step 1 and 2: The TER NETCONF Client establishes connection and creates an account for new user using o-ran-user9 mgmt.yang")
        print('-'*100)
        
        # server capabilities
        for i in m.server_capabilities:
            print("\t",i)


        # configuration patrt
        try:
            snippet = f"""
                    <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
                    <users xmlns="urn:o-ran:user-mgmt:1.0">
                        <user>
                            <name>{nam}</name>
                            <account-type>PASSWORD</account-type>
                            <password>{pas1}</password>
                            <enabled>true</enabled>
                        </user>
                    </users>
                    </config>"""

            
            print('\n> edit-config  --target running --config --defop merge\n')
            print('-'*100)
            print('******* Replace with below xml ********')
            print('-'*100)
            print(snippet)
        
            data1 = m.edit_config(target="running" , config=snippet)
            dict_data1 = xmltodict.parse(str(data1))
            if dict_data1['nc:rpc-reply']['nc:ok']== None:
                print('\nOk\n')
            print('-'*100)


            #  Notification from server side
            while True:
                n = m.take_notification(timeout=5)
                if n == None:
                    break
                notify=n.notification_xml
                s = xml.dom.minidom.parseString(notify)
                #xml = xml.dom.minidom.parseString(user_name)

                xml_pretty_str = s.toprettyxml()

                print(xml_pretty_str)
                print('-'*100)

        
            # See the changes by using get-filter
            u_name = '''
                    <filter xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
                    <users xmlns="urn:o-ran:user-mgmt:1.0">	
                    </users>
                    </filter>
                    '''

            
            user_name = m.get_config('running', u_name).data_xml
            print('-'*100)
            print("Step 3 and 4: The TER NETCONF Client retrieves a list of users")
            print('-'*100)
            print("\n> get --filter-xpath /o-ran-usermgmt:users/user\n")
            print('-'*100)
            x = xml.dom.minidom.parseString(user_name)
            #xml = xml.dom.minidom.parseString(user_name)

            xml_pretty_str = x.toprettyxml()

            print(xml_pretty_str)

            # Configue other RPC            
            ad_us = f'<user-name>{nam}</user-name>'
            nacm_file = open('/home/vvdn/Python_script/GARUDA_AUTOMATION/Yang_xml/nacm_sudo.xml').read()
            nacm_file = nacm_file.format(add_sudo = ad_us)
            

            print('-'*100)
            print('\n> edit-config  --target running --config --defop merge\n')
            print('-'*100)
            print('******* Replace with below xml ********')
            print('-'*100)
            
            print(nacm_file)
            print('-'*100)
            data2 = m.edit_config(target="running" , config=nacm_file, default_operation = 'merge')
            dict_data2 = xmltodict.parse(str(data2))
            if dict_data2['nc:rpc-reply']['nc:ok']== None:
                print('\nOk\n')
            print('-'*100)
            

            # Notification from server side
            while True:
                n = m.take_notification(timeout=5)
                if n == None:
                    break
                notify=n.notification_xml
                s = xml.dom.minidom.parseString(notify)
                #xml = xml.dom.minidom.parseString(user_name)

                xml_pretty_str = s.toprettyxml()

                print(xml_pretty_str)
                print('-'*100)
                
        except RPCError as e:
            return [e.tag, e.type, e.severity, e,e.message]
        


# Call Home with new user
def Call_Home(host,port,name,pas1):
    
        # rpc=m.create_subscription()
    # time.sleep(5)
    print('-'*100)
    print('Step 5 and 6: NETCONF Server establishes a TCP connection and performs the Call Home procedure to the TER NETCONF Client using the same IP and VLAN.\n\n')
    print('-'*100)
    m1 = manager.call_home(host = '', port=4334, hostkey_verify=False,username = 'Operator', password = 'admin123', timeout = 60)
    li = m1._session._transport.sock.getpeername()   #['ip_address', 'TCP_Port']
    try:
        if m1:
                print('-'*100)
                print("Step 7: TER NETCONF Client and O-RU NETCONF Server exchange capabilities through the NETCONF <hello> messages")
                
                print('-'*100)
                for i in m1.server_capabilities:
                    print(i)
                return m1.session_id
        else:
            m1.close()
    except:
        pass

        



if __name__ == '__main__':
    #give the input configuration in xml file format
    #xml_1 = open('o-ran-hardware.xml').read()
    #give the input in the format hostname, port, username, password
    try:
        
        m = manager.call_home(host = '', port=4334, hostkey_verify=False,username = 'Operator', password = 'admin123', timeout = 60)
        li = m._session._transport.sock.getpeername()   #['ip_address', 'TCP_Port']
        print(li)
        # print(m._session._transport.sock.close())
        sid = m.session_id
        print(sid)
        print(kill_ssn(li[0],830, 'root','root',sid))
        if m:
            
                print('-'*100)
                name = input("Enter new user :\n")
                print('-'*100)
                pas1 = input("Enter new password :\n")
                res = Create_user(li[0],830,name,pas1)
                
                
                if res:
                    host = li[0]
                    port = 22
                    username = "root"
                    password = "root"
                    print('-'*100)
                    print('\t\t\t\tSYSTEM LOGS')
                    print('-'*100)

                    command = "cd /media/sd-mmcblk0p4; tail -500 garuda.log;"
                    ssh = paramiko.SSHClient()
                    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                    ssh.connect(host, port, username, password)

                    stdin, stdout, stderr = ssh.exec_command(command)
                    lines = stdout.readlines()
                    for i in lines:
                        print(i, end='')
                    print('\n','*'*100)
                    print('*'*20,'FAIL_REASON','*'*20)
                    print('\n','*'*100)
                    print(f"{'error-tag' : <20}{':' : ^10}{res[0]: ^10}")
                    print(f"{'error-type' : <20}{':' : ^10}{res[1]: ^10}")
                    print(f"{'error-severity' : <20}{':' : ^10}{res[2]: ^10}")
                    #print(f"{'error-info' : <20}{':' : ^10}{res[3]: ^10}")
                    print(f"{'Description' : <20}{':' : ^10}{res[4]: ^10}")
                    print('\n','*'*100)
                    print(f"{'STATUS' : <50}{'=' : ^20}{'FAIL' : ^20}")
                    print('\n','*'*100)
                else:
                    # For Capturing the logs
                    time.sleep(5)
                    ssid = Call_Home(li[0],li[1],name,pas1)
                    kill_ssn(li[0],830, 'root','root',ssid)
                    host = li[0]
                    port = 22
                    username = "root"
                    password = "root"
                    print('-'*100)
                    print('\t\t\t\tSYSTEM LOGS')
                    print('-'*100)

                    command = "cd /media/sd-mmcblk0p4; tail -500 garuda.log;"
                    ssh = paramiko.SSHClient()
                    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                    ssh.connect(host, port, username, password)

                    stdin, stdout, stderr = ssh.exec_command(command)
                    lines = stdout.readlines()
                    for i in lines:
                        print(i, end='')
                    print('\n','*'*100)
                    print(f"{'STATUS' : <50}{'=' : ^20}{'PASS' : ^20}")
                    print('\n','*'*100)
                    
            
    except exception as e:
        print('-'*100)
        print("*"*30+'Exception'+"*"*30)
        print('-'*100)
        print('\t\t',e)
        print('-'*100)`

**Comment by vaibhav1713109** [comment]
Hi @einarnn 
The issue of "address is already use" is resolve by updating call home function with  "srv_socket.close()" and uses of try, except and finally like below way. You can Close the issue.
def call_home(*args, **kwds):
    host = kwds["host"]
    port = kwds.get("port",4334)
    timeout = kwds["timeout"]
    srv_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv_socket.bind((host, port))
    srv_socket.settimeout(timeout)
    srv_socket.listen()

    sock, remote_host = srv_socket.accept()
    logger.info('Callhome connection initiated from remote host {0}'.format(remote_host))
    kwds['sock'] = sock
    srv_socket.close()
    return manager.connect_ssh(*args, **kwds)
--------------------------------------------------------------------------------------------
try:
     m = manager.call_home(host = '', port=4334, hostkey_verify=False,username = 'Operator', password = 'admin123')
     li = m._session._transport.sock.getpeername() #['ip_address', 'TCP_Port']
except Exception as e:
     print(e)

finally:
     m.close_session()

**Comment by einarnn** [comment]
Closed per request of submitter.
