### ISSUE TITLE
Generic RPC subscription 

### ISSUE THREAD

**Issue by ushagurumurthy** [ncclient/ncclient#516]
Hi,
We are facing an issue how to create sysrepo RPC/action subscription using ncclient.
We are able to send the following rpc using:-

`rpc = '''
            <supervision-watchdog-reset xmlns="urn:o-ran:supervision:1.0">
<supervision-notification-interval>30</supervision-notification-interval>
<guard-timer-overhead>10</guard-timer-overhead>
</supervision-watchdog-reset>
'''`

response = m.dispatch(et.fromstring(rpc))

But we don't know how to subscribe to rpc-reply for the "supervision-watchdog-reset" RPC.

**Comment by einarnn** [comment]
The call:

```
response = m.dispatch(et.fromstring(rpc))
```

...should generate a synchronous response to the RPC, with the return in `response`. What you may be asking is how to subscribe for RFC 5277 notifications that may be generated after invoking that RPC. A simple example of how to subscribe for notifications can be found in:

https://github.com/CiscoDevNet/ncc/blob/master/ncc-event-listener.py

Closing off this issue as there doesn't appear to be any problem with ncclient.

**Comment by ushagurumurthy** [comment]
Worked , Thank you for your response
