### ISSUE TITLE
AuthenticationError

### ISSUE THREAD

**Issue by Zero960612** [ncclient/ncclient#518]
I have met a error when i used function ncclient.manager.connect to connect a device.
The code I used is :
m=manager.connect(host='192.168.1.1',port=830,username=***,password=***,hostkey_verify=False,timeout=3000)
and the error is:
Traceback (most recent call last):
  File "d:\Python\netconftest\threadingtest.py", line 30, in <module>
    netconfread()
  File "d:\Python\netconftest\threadingtest.py", line 9, in netconfread
    m=manager.connect(host='192.168.1.1',port=830,username=***,password=***,hostkey_verify=False,timeout=3000)
  File "D:\Python\Python39\lib\site-packages\ncclient\manager.py", line 176, in connect
    return connect_ssh(*args, **kwds)
  File "D:\Python\Python39\lib\site-packages\ncclient\manager.py", line 143, in connect_ssh
    session.connect(*args, **kwds)
  File "D:\Python\Python39\lib\site-packages\ncclient\transport\ssh.py", line 361, in connect
    self._auth(username, password, key_filenames, allow_agent, look_for_keys)
  File "D:\Python\Python39\lib\site-packages\ncclient\transport\ssh.py", line 466, in _auth
    raise AuthenticationError(repr(saved_exception))
ncclient.transport.errors.AuthenticationError: AuthenticationException('Authentication failed.')

I'm sure the username and password used in function parameter is correct because I used Xsell with same username and password to connect the device is OK.
I hope someone can give me a solution to deal with this error, please

**Comment by einarnn** [comment]
suggest you use a command like `ssh -p 830 your.ip -s netconf`, and see what errors, if any, are returned.

**Comment by Zero960612** [comment]
ok,i will try this way,thanks for your help


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ncclient/ncclient"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月10日(星期一) 凌晨2:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ncclient/ncclient] AuthenticationError (Issue #518)





 
suggest you use a command like ssh -p 830 your.ip -s netconf, and see what errors, if any, are returned.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by einarnn** [comment]
Assuming that this issue is no longer live; closing.

**Comment by xietian511ok** [comment]
> suggest you use a command like `ssh -p 830 your.ip -s netconf`, and see what errors, if any, are returned.

can you help me to find out  where is wrong

(base) tianxie@bogon ~ % ssh -p 830 192.168.10.74 -s netconf
Bad remote protocol version identification: 'SSH-2.0-'
banner exchange: Connection to 192.168.10.74 port 830: invalid format
(base) tianxie@bogon ~ %
