### ISSUE TITLE
no existing session

### ISSUE THREAD

**Issue by mrjoli021** [ncclient/ncclient#520]
I am doing a simple connection to an ASR 9k in our lab.  If I run on the command line "ssh@10.22.108.11 -p 830 -s netconf" I am able to connect and get the capabilities.  But if I run this script below, I keep getting the error "ncclient.transport.errors.AuthenticationError: SSHException('No existing session')"  What am I doing wrong?

```
from ncclient import manager

if __name__ == '__main__':


    with manager.connect(host='10.22.108.11',
                        port=830,
                        username='admin',
                        password='admin',
                        device_params={'name': 'iosxr'},
                        allow_agent=False,
                        hostkey_verify=False
    ) as m:

        print(m.server_capabilities)
```

**Comment by einarnn** [comment]
Assuming that this issue is no longer live; closing.

**Comment by davehouser1** [comment]
If anyone else runs into this issue the solution for me was to set `look_for_keys=False`. Based off what OP posted I would add the following parameter:

```
from ncclient import manager

if __name__ == '__main__':


    with manager.connect(host='10.22.108.11',
                        port=830,
                        username='admin',
                        password='admin',
                        device_params={'name': 'iosxr'},
                        allow_agent=False,
                        hostkey_verify=False,
                        look_for_keys=False
    ) as m:

        print(m.server_capabilities)
```

**Comment by Kani999** [comment]
> If anyone else runs into this issue the solution for me was to set `look_for_keys=False`. Based off what OP posted I would add the following parameter:
> 
> ```
> from ncclient import manager
> 
> if __name__ == '__main__':
> 
> 
>     with manager.connect(host='10.22.108.11',
>                         port=830,
>                         username='admin',
>                         password='admin',
>                         device_params={'name': 'iosxr'},
>                         allow_agent=False,
>                         hostkey_verify=False,
>                         look_for_keys=False
>     ) as m:
> 
>         print(m.server_capabilities)
> ```

@davehouser1 
Works for me, I had the same problem. Thank you !
