### ISSUE TITLE
issue with NCCLIENT methods

### ISSUE THREAD

**Issue by vikrant6613** [ncclient/ncclient#521]
Hi All,

I need your help with the ncclient package. I am unable to run get_schema() or any methods belong to manager class. I was able run server_capabilites and i got the output as well.

even I am not getting hint for these methods with manager object in python ide

Below is my system details :
python  : 3.6..5
ncclient : 0.6.7

i tried with higher versions python(3.9) an nc(0.6.12), but still same error.

program:

```
from ncclient import manager

man = manager.connect(host="192.168.0.104", port='830', username='admin',
                      password='admin', device_params={'name': 'iosxe'}, hostkey_verify=False)

schema = man.get_schema('ietf-ip')
print(schema)

man.close_session()
```

error:
----------------
E:\study\PythonLearning\venv\Scripts\python.exe E:/study/PythonLearning/Netconf/basic_tut.py
Traceback (most recent call last):
  File "E:/study/PythonLearning/Netconf/basic_tut.py", line 9, in <module>
    schema = man.get_schema('ietf-ip')
  File "E:\study\PythonLearning\venv\lib\site-packages\ncclient\manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "E:\study\PythonLearning\venv\lib\site-packages\ncclient\operations\retrieve.py", line 198, in request
    return self._request(node)
  File "E:\study\PythonLearning\venv\lib\site-packages\ncclient\operations\rpc.py", line 348, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: {'type': 'protocol', 'tag': 'access-denied', 'severity': 'error', 'info': None, 'path': None, 'message': None}

Please suggest. Thanks in advance

**Comment by einarnn** [comment]
The code as you have it here should work fine against any modern IOS XE platform, preferably running IOS XE 16.10.1 or greater. Also, you will needed to have configured the more "modern" NETCONF agent, using the configuration `netconf-yang`.

The error you have appears to be an access control problem. Today, the user trying to access NETCONF on IOS XE does need to have "privilege 15" access rights. These can be scoped by also configuring the NACM function on IOS XE.

**Comment by vikrant6613** [comment]
Thanks @einarnn . I will check more details on NACM function on XE. Currently i able to do my lab on sandbox

**Comment by einarnn** [comment]
Closing as no further feedback on any ncclient issue.
