### ISSUE TITLE
edit_config error

### ISSUE THREAD

**Issue by Zero960612** [ncclient/ncclient#529]
i have met a error when i used edit_config to delete some parameters 
the code i used is:
`
configxml = '''
<config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
    <router xmlns="http://tail-f.com/ns/router-dcl">
        <static xmlns="http://tail-f.com/ns/rtm">
            <static-vrf nc:operation="delete">
                <ip>172.25.10.0/24</ip>
                <next-hop>10.128.10.10</next-hop>
                <vrf>global</vrf>
            </static-vrf>
        </static>
    </router>
</config>
'''
edittest = m.edit_config(config = configxml)
`
and the error message is:
`
ncclient.operations.rpc.RPCError: {'type': 'protocol', 'tag': 'unknown-element', 'app_tag': None, 'severity': 'error', 'info': '<?xml version="1.0" encoding="UTF-8"?><error-info xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><bad-element>config</bad-element>\n</error-info>\n', 'path': '\n    /rpc/edit-config\n  ', 'message': None}
`
i don't know why i met this error, i hope someone can help me, thanks

**Comment by einarnn** [comment]
@Zero960612, try correcting `<config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">` to `<nc:config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">` and `</config>` to `</nc:config>`.

**Comment by Zero960612** [comment]
it's very helpful ! thanks very much !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ncclient/ncclient"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月11日(星期一) 下午4:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ncclient/ncclient] edit_config error (Issue #529)





 
Closed #529.
