### ISSUE TITLE
An error message with unknown session number

### ISSUE THREAD

**Issue by fourwilling** [ncclient/ncclient#530]
Hi,

I am attempting to perform a netconf session lock operation in my NETCONF test scripts:
```
from ncclient import manager
import unittest

conn = manager.connect(
    host=***,
    username=***,
    password=***,
    hostkey_verify=False,
)

with conn.locked(target='running'):
    conn.discard_changes()
    suite = unittest.TesetSuite()
    suite.addTest(...)
    suite.addTest(...)
    .....(multiple testcases)
    unittest.TestRunner().run(suite)

conn.close_session()
```
However, I got this error:
`Module "******" is DS-locked by session 9261194. `

Have no idea why this happens. I only set up one NETCONF connection in my test script.

Can I get the 3-digit session ID from 9261194? Really don't how this 7-digit number was created. I would like to kill this locked session with the code below:
```
   try:
       ....
   except operations.rpc.RPCError as e:
       string = str(e)
       index = string.find("session")
       num = string[index+8:-1]
       self.conn.kill_session(toSessionID(num))
```

```
Debian GNU Linux 10 (buster) 
ncclient  0.6.13
```

**Comment by einarnn** [comment]
@fourwilling, not sure why you say a session-id should be 3 digits. It is an unsigned int, with 0 signifying a non-NETCONF client holding the lock. Without seeing much more of your script it is hard to make any suggestions, but one comment I will make is that `discard_changes` is not a valid operation on the `running` datastore. It only makes sense on the `candidate` datastore, which you do not appear to be using.

**Comment by fourwilling** [comment]
@einarnn below is the log I got from the server end:
[](https://controlc.com/8ad5af85)
I blurred some information with "*". Is it possible to see if there's a non-NETCONF session holding the lock from these messages?

**Comment by einarnn** [comment]
@fourwilling, is it possible you are creating more sessions yourself in your test code?

**Comment by fourwilling** [comment]
> Also, is it possible you are accidentally creating more than one session yourself in your test code?

I am not sure. Is there any way to list out all sessions connecting to the client?

**Comment by einarnn** [comment]
@fourwilling, all netconf servers have a way to list how many sessions are connected:

https://datatracker.ietf.org/doc/rfc6022/

this model has other data as well about all active sessions and more.

**Comment by fourwilling** [comment]
@einarnn,

I only see one session before the unit test starts. 

```
from ncclient import manager
import unittest

conn = manager.connect(
    host=***,
    username=***,
    password=***,
    hostkey_verify=False,
)

print(conn.session_id)  --> 390

with conn.locked(target='running'):
    suite = unittest.TesetSuite()
    suite.addTest(testClass("test1"))
    suite.addTest(testClass("test2"))
    ....
    unittest.TestRunner().run(suite)
conn.close_session()
```

Inside testClass, before the first NETCONF operation I added: 
```
netconf_sub = """<netconf-state xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"><datastores/><sessions/><statistics/></netconf-state>"""
print(conn.get(filter=("subtree", netconf_sub)).data_xml)
```
and got

<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
   <netconf-state xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
      <datastores>
         <datastore>
            <name>running</name>
            <locks>
               <global-lock>
                  <locked-by-session>0</locked-by-session>
                  <locked-time>1970-01-01T01:00:00+01:00</locked-time>
               </global-lock>
            </locks>
         </datastore>
         <datastore>
            <name>startup</name>
         </datastore>
         <datastore>
            <name>candidate</name>
         </datastore>
      </datastores>
      <sessions>
         <session>
            <session-id>390</session-id>
            <transport>netconf-ssh</transport>
            <username>root</username>
            <source-host>10.42.0.91</source-host>
            <login-time>2019-03-10T11:59:53+01:00</login-time>
            <in-rpcs>2</in-rpcs>
            <in-bad-rpcs>0</in-bad-rpcs>
            <out-rpc-errors>0</out-rpc-errors>
            <out-notifications>0</out-notifications>
         </session>
      </sessions>
      <statistics>
         <netconf-start-time>2019-02-24T13:02:06+01:00</netconf-start-time>
         <in-bad-hellos>0</in-bad-hellos>
         <in-sessions>390</in-sessions>
         <dropped-sessions>48</dropped-sessions>
         <in-rpcs>18944</in-rpcs>
         <in-bad-rpcs>12</in-bad-rpcs>
         <out-rpc-errors>3935</out-rpc-errors>
         <out-notifications>0</out-notifications>
      </statistics>
   </netconf-state>
</data>

**Comment by einarnn** [comment]
The contents of the error message is defined by the netconf server. That is being returned to ncclient by the netconf server. I can only speculate, but it may be an internal (to the netconf server) handle.

looking at the data from ietf-netconf-monitoring, it seems that session “0” is holding a lock. Session 0 is reserved for clients like the local config CLI, so it may be that however the device is being managed is grabbing the lock. I know, for example, that some Cisco devices grab a lock on the running datastore when a console user enters config terminal mode. Maybe something similar is happening here?

regardless, this doesn’t appear to be an ncclient issue, so closing it off for now.
