### ISSUE TITLE
ncclient.get with filter not getting full data

### ISSUE THREAD

**Issue by harshad1692** [ncclient/ncclient#533]
Hi,

i need to get specific data from yang models so tried using filter but am not getting complete data,

**code**
`ncclient.get(filter='<nc:filter type="xpath" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:tm="urn:o-ran:user-mgmt:1.0" select="/tm:usermgmt/users/user/name"/>')
`
**output**
`<?xml version="1.0" encoding="UTF-8"?><rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:69599685-cc0b-4fb8-a418-7a4e8cac0081" xmlns:ncx="http://netconfcentral.org/ns/yuma-ncx" ncx:last-modified="2022-05-06T03:25:31Z" ncx:etag="2892" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><data></data></rpc-reply>
`
can anyone tell me whats the issue & how to solve it.

Thanks in advance

**Comment by einarnn** [comment]
@harshad1692, you may need to add `tm:` to each element of the `select` XPath.

**Comment by einarnn** [comment]
This isn’t an issue with ncclient, closing for now.
