### ISSUE TITLE
Fetching just the top level tags present in junos running config

### ISSUE THREAD

**Issue by lavanyasingaravelanT** [ncclient/ncclient#534]
Is it possible to fetch just the top level tags in running config for junos rather than fetching the whole running config. 
Like if the running config has interfaces, protocol and COS, I just need just **interfaces, protocol and COS**
to be returned not any values associated with them. Is there any way to do that

**Comment by einarnn** [comment]
If you know the top-level model roots, yes, you can construct a subtree filter and pass that as part of the get config call.

**Comment by lavanyasingaravelanT** [comment]
> If you know the top-level model roots, yes, you can construct a subtree filter and pass that as part of the get config call.
> […](#)
> On May 13, 2022, 2:25 PM +0100, lavanyasingaravelanT ***@***.***>, wrote: Is it possible to fetch just the section name in running config for junos rather than fetching the whole running config. Like if the running config has interfaces, protocol and COS, I just need just interfaces, protocol and COS to be returned not any values associated with them. Is there any function in ncclient for that — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by lavanyasingaravelanT** [comment]
We have a lot of junos routers and I actually need to fetch the top level model roots of all the routers which I'm not aware of and which changes for each router. Is it possible to get the top level model root  of junos devices. Is there any way to do in ncclient

**Comment by einarnn** [comment]
If you don't know which models the routers support, typically I would attach to the router and use the mandatory model `ietf-netconf-monitoring` (or `ietf-yang-library` if supported) to get the models supported by the device, then either get these models from the router (`get-schema` RPC) or from https://github.com/Juniper/yang/tree/maste. You would then parse the supported yang models (eg using library from pyang) and extract the root tags.
