### ISSUE TITLE
Fetching output from IOSXR device in cli format 

### ISSUE THREAD

**Issue by lavanyasingaravelanT** [ncclient/ncclient#535]
Is there any way we can fetch the configuration output of an Cisco - iosxr router in cli format using ncclient. 
Like i need to fetch the output of the command **show running-config interface** in cli format using ncclient. Is there any way to do so?

**Comment by einarnn** [comment]
AFAIK, can't be done using netconf, sorry. You would need to automate using something like, say, the library Netmiko.

Not really an ncclient issue, closing.
