### ISSUE TITLE
processing timed out

### ISSUE THREAD

**Issue by fourwilling** [ncclient/ncclient#539]
Hello,

ncclient will likely throw a timeout error if I perform the <get> operation consecutively. (from port1 to port16). But if I use Netopeer2 instead of ncclient, no timeout error occurs. Below my test code, I increased RPC timeout to 3000 sec:

```
conn = manager.connect(
    host=***,
    username=***,
    password=***,
    hostkey_verify=False,
    manager_params={"timeout": 3000}
)
for i in range(1, 17):
    platform_sub = f"""<components xmln="http://*****">
                            <component>
                                <name>port{i}</name>
                                    <state/>
                            </component>
                        </components>"""

    print(conn.get(filter=("subtree", platform_sub)).data_xml)
```
Error message:
```
Traceback (most recent call last):
  File "testPlatform.py", line 24, in <module>
    print(conn.get(filter=("subtree", platform_sub)).data_xml)
  File "/usr/local/lib/python3.8/dist-packages/ncclient/manager.py", line 232, in execute
    return cls(self._session,
  File "/usr/local/lib/python3.8/dist-packages/ncclient/operations/retrieve.py", line 93, in request
    return self._request(node)
  File "/usr/local/lib/python3.8/dist-packages/ncclient/operations/rpc.py", line 349, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: Callback event "operational" with ID 305 processing timed out.
```

**Comment by einarnn** [comment]
@fourwilling, can I ask:

- How long after the `get` was dispatched was this error message given?
- Can you enable verbose logging and examine the returned data? And please check for inline RPC errors. `ncclient` will raise an execption by default if an inline RPC error is encountered, and the above exception is what is thrown.
- What platform were you querying? I ask because I'm aware that some Cisco platforms will embed RPC errors inline in the responses to some OpenConfig requests (as I _guess_ you are doing from the query you show even though you didn't show the actual namespace)

You can suppress the raising of exceptions:

```
from ncclient.operations import RaiseMode

conn.raise_mode = RaiseMode.NONE
```

Suggest you try what I've suggested above. If you set the raise mode to `RaiseMode.NONE` you will be able to get all data back and examine for an inline error.

**Comment by fourwilling** [comment]
@einarnn

After I added the two lines as you suggested:

```
from ncclient.operations import RaiseMode
conn.raise_mode = RaiseMode.NONE
```

I rarely (still have the error sometimes) see the time-out error even if I set `conn.raise_mode` back to the default value (`RaiseMode.ALL`)
 
> * How long after the `get` was dispatched was this error message given?

It varies. It usually takes less than a minute before I set `conn.raise_mode` to` RaiseMode.NONE`. And this error can occur during every port read.

> * Can you enable verbose logging and examine the returned data? And please check for inline RPC errors. `ncclient` will raise an exception by default if an inline RPC error is encountered, and the above exception is what is thrown.'

Below are log messages:

DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: starting
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: working with buffer of 485 bytes
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: matching from 0 bytes from start of buffer
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: regular expression start=0, end=6
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: found chunk delimiter
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: chunk size 475 bytes
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: appending 475 bytes
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: fragment = "<nc:rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:92d9beb7-d904-4477-acd3-ffe3960fa2b0"><nc:rpc-error><nc:error-type>application</nc:error-type><nc:error-tag>operation-failed</nc:error-tag><nc:error-severity>error</nc:error-severity><nc:error-path>/openconfig-platform:components</nc:error-path><nc:error-message xml:lang="en">Callback event "operational" with ID 1190 processing timed out.</nc:error-message></nc:rpc-error></nc:rpc-reply>"
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: matching from 481 bytes from start of buffer
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: regular expression start=0, end=4
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: found end of message delimiter
INFO:ncclient.transport.ssh:[host *.*.*.* session-id 53] Received:
<nc:rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:92d9beb7-d904-4477-acd3-ffe3960fa2b0"><nc:rpc-error><nc:error-type>application</nc:error-type><nc:error-tag>operation-failed</nc:error-tag><nc:error-severity>error</nc:error-severity><nc:error-path>/openconfig-platform:components</nc:error-path><nc:error-message xml:lang="en">Callback event "operational" with ID 1190 processing timed out.</nc:error-message></nc:rpc-error></nc:rpc-reply>
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] dispatching message to <ncclient.transport.session.NotificationHandler object at 0x7fef9c464910>: <nc:rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:92d9beb7-d904-4477-acd3-ffe3960fa2b0"><nc:rpc-error><nc:error-type>application</nc:error-type><nc:error-tag>operation-failed</nc:error-tag><nc:error-severity>error</nc:error-severity><nc:error-path>/openconfig-platform:components</nc:error-path><nc:error-message xml:lang="en">Callback event "operational" with ID 1190 processing timed out.</nc:error-message></nc:rpc-error></nc:rpc-reply>
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x7fef9c47b070>: <nc:rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:92d9beb7-d904-4477-acd3-ffe3960fa2b0"><nc:rpc-error><nc:error-type>application</nc:error-type><nc:error-tag>operation-failed</nc:error-tag><nc:error-severity>error</nc:error-severity><nc:error-path>/openconfig-platform:components</nc:error-path><nc:error-message xml:lang="en">Callback event "operational" with ID 1190 processing timed out.</nc:error-message></nc:rpc-error></nc:rpc-reply>
DEBUG:ncclient.operations.rpc:[host *.*.*.* session-id 53] Delivering to <ncclient.operations.retrieve.Get object at 0x7fef9c47b040>
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: saving back rest of message after 485 bytes, original size 485
DEBUG:ncclient.transport.ssh:[host *.*.*.* session-id 53] _parse11: ending

Traceback (most recent call last):
  File "testPlatform.py", line 30, in <module>
    print(conn.get(filter=("subtree", platform_sub)).data_xml)
  File "/usr/local/lib/python3.8/dist-packages/ncclient/manager.py", line 231, in execute
    return cls(self._session,
  File "/usr/local/lib/python3.8/dist-packages/ncclient/operations/retrieve.py", line 91, in request
    return self._request(node)
  File "/usr/local/lib/python3.8/dist-packages/ncclient/operations/rpc.py", line 350, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: Callback event "operational" with ID 1190 processing timed out.

> * What platform were you querying? I ask because I'm aware that some Cisco platforms will embed RPC errors inline in the responses to some OpenConfig requests (as I _guess_ you are doing from the query you show even though you didn't show the actual namespace)

I am actually using the goldstone platform.


Thank you!

**Comment by einarnn** [comment]
Ok, this looks like an error being returned by the device as far as I can see. Not a problem with ncclient. Does netopeer return something different?

**Comment by fourwilling** [comment]
> Ok, this looks like an error being returned by the device as far as I can see. Not a problem with ncclient. Does netopeer return something different?

Neoteer2 returns the data same as ncclient do. But it seems that the timeout does not occur if I use Netopeer2.
I have successfully sent 1000 consecutive NETCONF requests and got the correct data from the response.

**Comment by einarnn** [comment]
Can you enable verbose logging with `ncclient` and upload a trace of the debugs for an operation that times out?

**Comment by einarnn** [comment]
@fourwilling, no comments for over a month; assuming issue is no longer live!
