### ISSUE TITLE
RPCError only reports first error (Junos)

### ISSUE THREAD

**Issue by jeremyschulman** [ncclient/ncclient#54]
I am using ncclient with a Junos system.  During a commit cycle, a number of rpc-error elements are generated.  For example:

````xml
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/12.3R3/junos">
<commit-results>
   <rpc-error>
      <error-severity>warning</error-severity>
      <error-path>[edit routing-instances charlie instance-type]</error-path>
      <error-info>
         <bad-element>instance-type virtual-router</bad-element>
      </error-info>
      <error-message>mgd: requires 'virtual-router' license</error-message>
   </rpc-error>
   <rpc-error>
      <error-severity>warning</error-severity>
      <error-path>[edit routing-instances charlie protocols]</error-path>
      <error-info>
         <bad-element>ospf</bad-element>
      </error-info>
      <error-message>mgd: requires 'ospf2' license</error-message>
   </rpc-error>
   <rpc-error>
      <error-severity>error</error-severity>
      <source-daemon>
      eswd
      </source-daemon>
      <error-message>
      No vlan matches vlan tag 200 for interface ge-0/0/1.0
      </error-message>
   </rpc-error>
   <rpc-error>
      <error-severity>error</error-severity>
      <error-message>
         configuration check-out failed
      </error-message>
   </rpc-error>
   </commit-results>
</rpc-reply>
````

The "bug" is that ncclient is only reporting the first `<rpc-error>`, which in this case happens to be a error-severity=warning.  So the calling program is not able to report on the error-severity=error items.

Can this be easily resolved?  I don't know if this issue is specific to the Junos module in ncclient or not.  

I appreciate your time to investigate and provide guidance.  I can attempt to make changes with your guidance and issue pull request when I have a fix; if needed/etc.

Thank you!
-- Jeremy

**Comment by leopoul** [comment]
Hi Jeremy,

I just fixed this in this commit: https://github.com/leopoul/ncclient/commit/4d61c681889c234949e23f18b13754882202f72c

To test I had the following:
```
config = """<config><configuration>
<interfaces><interface><name>em1</name>
<unit><name>0</name><vlan-id>10</vlan-id></unit></interface></interfaces>
<routing-instances>
                <instance>
                    <name>test</name>
                    <protocols>
                        <vpls>
                        </vpls>
                    </protocols>
                </instance>
            </routing-instances>
</configuration></config>"""
```
Raw NETCONF reply is:
```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/12.1R4/junos">
    <rpc-error>
        <error-severity>error</error-severity>
        <source-daemon>
            rpd
        </source-daemon>
        <error-path>
            [edit routing-instances test]
        </error-path>
        <error-info>
            <bad-element>
                protocols
            </bad-element>
        </error-info>
        <error-message>
            Protocol VPLS not allowed under non-forwarding (0x8) instance test
        </error-message>
    </rpc-error>
    <rpc-error>
        <error-severity>error</error-severity>
        <source-daemon>
            dcd
        </source-daemon>
        <error-path>
            [edit interfaces em1]
        </error-path>
        <error-info>
            <bad-element>
                unit 0
            </bad-element>
        </error-info>
        <error-message>
            VLAN-ID can only be specified on tagged ethernet interfaces
        </error-message>
    </rpc-error>
    <rpc-error>
        <error-severity>error</error-severity>
        <error-message>
            configuration check-out failed
        </error-message>
    </rpc-error>

</rpc-reply>
```
Before the patch, we would get only this:

```
ncclient.operations.rpc.RPCError: Protocol VPLS not allowed under non-forwarding (0x8) instance test
```
With the patch we get:
```
ncclient.operations.rpc.RPCError: error:Protocol VPLS not allowed under non-forwarding (0x8) instance test
error:VLAN-ID can only be specified on tagged ethernet interfaces
error:configuration check-out failed
```

Hope it helps

Best,
Leo

**Comment by vnitinv** [comment]
Hi @leopoul its not working for me. 

I am getting _raw not defined error. As i can see you have now moved self._raw declaration at
https://github.com/leopoul/ncclient/blob/master/ncclient/operations/rpc.py#L43
hence only getting set when https://github.com/leopoul/ncclient/blob/master/ncclient/operations/rpc.py#L42 is satisfied.

and most of the time you are calling RPCError with multiple as True https://github.com/leopoul/ncclient/blob/master/ncclient/operations/rpc.py#L333

Hence it's not going into else part (atleast for my case) and self._raw is not set. Hence leading to the error. 

I was using below config to commit:
# show | compare          
[edit interfaces ge-2/3/3 unit 0]
+    vlan-id 1;
[edit]
+  routing-instances {
+      test {
+          protocols {
+              vpls;
+          }
+      }
+  }
[edit]

**Comment by leopoul** [comment]
It should work now

**Comment by vnitinv** [comment]
@leopoul Looks good. Now need to handle err.xml in PyEZ properly as now sometime it can be list too.

Thanks!!

**Comment by shermdog** [comment]
Hi @leopoul ,

Do you have a time frame for when this will hit the release version of ncclient?  I'd like to utilize some of this in updates for PyEZ / Junos Ansible.

Feel free to ping me directly.

Thanks,
-Rick

**Comment by vnitinv** [comment]
Its working in PyEZ 1.3.1
