### ISSUE TITLE
Juniper Junos Device handler (ignore-warnings)

### ISSUE THREAD

**Issue by gcasella** [ncclient/ncclient#545]
Hi!

Would like to say first, I am loving the work that the team is doing with ncclient!

This may be a generic question, but I was curious to know if ncclient has the capability of ignoring warning when a statement does not exist on a Juniper Device.

Reference to this line: https://github.com/ncclient/ncclient/blob/2b500aaaa18585ea7fd5cbd319f80e2a47a8e971/ncclient/operations/third_party/juniper/rpc.py#L20

Using ncclients   examples for junos
https://github.com/ncclient/ncclient/blob/master/examples/vendor/juniper/edit-config-jnpr-set.py

I attempt to delete configuration that I know does not exist on my device and i would receive the following exception;

> Traceback (most recent call last):
> python-BaseException
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "junos_ncc.py", line 49, in <module>
>     connect('192.168.2.2', '830', 'admin', 'password')
>   File "junos_ncc.py", line 22, in connect
>     load_config_result = conn.load_configuration(action='set', config='delete system services telnet')
>   File "/venv/lib/python3.9/site-packages/ncclient/manager.py", line 246, in execute
>     return cls(self._session,
>   File "/venv/lib/python3.9/site-packages/ncclient/operations/third_party/juniper/rpc.py", line 38, in request
>     return self._request(node)
>   File "/venv/lib/python3.9/site-packages/ncclient/operations/rpc.py", line 375, in _request
>     raise self._reply.error
> ncclient.operations.rpc.RPCError: 
> statement not found

Looking at the Juniper jnpr.junos package, they have included an option within their package to ignore rpc-errors when calling the argument `ignore_warning`

https://github.com/Juniper/py-junos-eznc/blob/e50606db402747c2711a4aa846a53961cd399f9d/lib/jnpr/junos/utils/config.py

Any feedback to this would be appreciated.

If more information would be required please let me know!

Update: I do see the ncclient manager.py has the concept of `raise_mode` I think that's what i would be looking for but i don't see a way in modifying it.

**Comment by gcasella** [comment]
Looks like i found an option to use after opening my connection with ncclient, i'm not sure if this is really the correct way to do it but it looked something like this. 
Using `conn.raise_mode = 1` to enforce only real errors will be reported back.

> #!/usr/bin/env python
> import os
> import sys
> 
> import logging
> 
> from ncclient import manager
> 
> 
> def connect(host, port, user, password):
>     conn = manager.connect(host=host,
>                            port=port,
>                            username=user,
>                            password=password,
>                            timeout=60,
>                            device_params={'name': 'junos'},
>                            hostkey_verify=False)
> 
>     conn.lock()
>     conn.raise_mode = 1
> 
>     # configuration as a string
>     load_config_result = conn.load_configuration(action='set', config='delete system services telnet')
>     logging.info(load_config_result)
>     validate_result = conn.validate()
>     logging.info(validate_result)
> 
>     compare_config_result = conn.compare_configuration()
>     logging.info(compare_config_result)
> 
>     conn.commit()
>     conn.unlock()
>     conn.close_session()
> 
> if __name__ == '__main__':
>     LOG_FORMAT = '%(asctime)s %(levelname)s %(filename)s:%(lineno)d %(message)s'
>     logging.basicConfig(stream=sys.stdout, level=logging.INFO, format=LOG_FORMAT)
> 
>     connect('192.168.2.2', '830', 'admin', 'password')

**Comment by einarnn** [comment]
@gcasella 

Changing `raise_mode` is the approach for addressing the issue you have. The one change I might suggest is:

```
# in imports section
from ncclient.operations import RaiseMode

# in your code
conn.raise_mode = RaiseMode.ERRORS
```

This saves you depending on the enum value. See:

https://github.com/ncclient/ncclient/blob/176a23a602185767363ebf4ceb5cee850384350a/ncclient/operations/rpc.py#L272-L288

...for the valid values.
