### ISSUE TITLE
nclient stuck at dead loop when ssh session close

### ISSUE THREAD

**Issue by GreenHandTo** [ncclient/ncclient#548]
Hi. I am using ncclient in openstack/ironic project  (which uses eventlet patched greenthread) to try to add some code to operate switch and using keepalive=1 in nclient.manager.connect method to keep a long time connection. 

But after sometimes the real connection disconnect by itself (or login to switch to close the connection manually). After this, using the Manager object to operate switch, it raised `TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.`, but the Manager's connected attribute is still True. 

I added some log, found that it stucks at SSHSession.close method's while loop when the connection disconnect hits.

    while self.is_alive() and (self is not threading.current_thread()):
        self.logger.info("**********loop join*****************")
        self.join(10)

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/32973023/183238464-58e81e7c-dd60-49ef-918c-0849c298ae90.png">

I've saw comment on loop code is  `# Wait for the transport thread to close.`, is the loop waiting for self._transport   to stop? But I added some log and self._transport is not active.

The project is using Python 2.7.5, Is there any solution to this?

**Comment by GreenHandTo** [comment]
I saw in the SSHSession.run code: If exception hits,  it will call SSHSession.close which will wait for the thread to become inactive. According to threading.isAlive, `This method returns True just before the run() method starts until just after the run() method terminates. `, So in SSHSession.run we call threading.isAlive it will always be True. 

If this is the case, we should add a flag parameter to indicate close method not to wait for thread to become alive.

**Comment by GreenHandTo** [comment]
Ok, I've found the solution. Eventlet has already fixed the `threading.current_thread` stuff.
[https://github.com/eventlet/eventlet/issues/172](url)

**Comment by einarnn** [comment]
@GreenHandTo -- Glad you found a resolution to your problem!

Please note that `ncclient` will not make any attempt to support Python 2.7.x as it moves forward. There will be no attempt to explicitly stop the code from functioning with 2.7.x, but it is no longer part of our CI testing and we will not ask developers to make sure that PRs do not break 2.7.x compatibility.

**Comment by GreenHandTo** [comment]
@einarnn Ok.Thank you. By the way, since which version,does
the CI system not test compatible with python 2.7.x? In the near future?
