### ISSUE TITLE
Add NC server functionality

### ISSUE THREAD

**Issue by plajjan** [ncclient/ncclient#55]
I'm creating this issue to open a discussion on if and how it would be possible to add NC server functionality to ncclient. I guess it's a bit of an oxymoron to add server functionality to a library with "client" in the name but here goes..

The current NETCONF server implementations out from the likes of Cisco and Juniper are proprietary and included in their products. I would like the ability to add NC/YANG functionality to other systems, for example a Linux host running an application where I would want to configure both the Linux machine (IP addresses, routes, hostname..) and the application via NC/YANG, much like I would with a normal router.

I have two active use cases where this would be very nice;
 * Configuration of Snabbswitch, an open source framework for writing NFV-style applications. It can also be used as a vSwitch/vRouter for OpenStack or similar. I'm writing applications using Snabb that do router-like jobs and as such it would be nice to configure them the same way I configure my "real" routers, ie using NC/YANG.
 * I've just added IPv6 support for IPTV-Analyzer to measure quality of IPTV streams in our network. I would like to be able to configure an "appliance" (like a VM image or whatever) of IPTV-Analyzer using NC/YANG. Again, much like any other network appliance. I would really like to avoid manual hacking of configuration files or even using something like Ansible.

I'm not at all familiar with the ncclient code base (yet) so I'm not sure how well suited it is to be molded into being not only a client but also act as a server. If this is the worst idea ever just tell me so but I imagine that there should be common parts between a server and client. I'm open to all and any ideas and an open discussion on the topic :)

**Comment by leopoul** [comment]
Hi Kristian,
Have you tried libnetconf: https://github.com/cesnet/libnetconf ? It's quite customizable and it may fit your needs.

Best,
Leo

**Comment by plajjan** [comment]
@leopoul no I haven't, I was looking for something in Python :)

Is this a bad fit or are there parts in ncclient that could be reused for building a server?

**Comment by leopoul** [comment]
Some parts could be used, however I would consider the server as a completely different project.
