### ISSUE TITLE
Socket timeout in manager.call_home()

### ISSUE THREAD

**Issue by avazquezrd** [ncclient/ncclient#557]
I have been using the _call home_ implementation provided by `ncclient` and, although it works fine (it listens for incoming connections and establishes the SSH session properly) I was wondering if there is any reason to have a predefined socket timeout in the _call_home_ method that cannot be modified. Actually, I think that the _call_home_ could be useful for a NETCONF client to be notified by the NETCONF server when it has been started, and if the server takes longer than the timeout set here, it will fail. 

**Could it be possible to pass this timeout as argument as we do for _host_ or _port_? Would this have any disadvantage?**

```python3
def call_home(*args, **kwds):
    host = kwds["host"]
    port = kwds.get("port",4334)
    srv_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv_socket.bind((host, port))
    srv_socket.settimeout(10)
    srv_socket.listen()

    sock, remote_host = srv_socket.accept()
    logger.info('Callhome connection initiated from remote host {0}'.format(remote_host))
    kwds['sock'] = sock
    return connect_ssh(*args, **kwds)
```

**Comment by einarnn** [comment]
@avazquezrd, there was no specific reason to not have this configurable. Please feel free to submit a PR with appropriate tests.
