### ISSUE TITLE
<config> tag shall use <nc:config>?

### ISSUE THREAD

**Issue by macauleycheng** [ncclient/ncclient#56]
Because "\<nc:edit-config\>" "\<nc:target\>" all have "nc" start,
but "\<config\>" doesn't.

Libnetconf will have problem.
https://code.google.com/p/libnetconf/

**Comment by leopoul** [comment]
Hi Macauley,
Have you setup and tried their interoperability? If so I would be grateful if you could post any issues and/or debug logs.

Thnx
Leo
