### ISSUE TITLE
DeprecationWarning SafeConfigParser no more exist in the python 3.12.0

### ISSUE THREAD

**Issue by delhipnr** [ncclient/ncclient#572]
Replace configparser.SafeConfigParser to configparser.RawConfigParser 3.12.0 in versioneer.py

**Comment by delhipnr** [comment]
to replicate you would be able to install existing ncclient in 3.12 version 
try pip install ncclient in 3.12.0

**Comment by ljarasius** [comment]
Also hitting this bug when attempting to install via `pip`. Appears that this has been addressed in #568, however as a new release has not been made, the fix only comes through when building manually from `master`.

As my use case is a package that has ncclient as a dependency, I am unable to workaround this without downgrading to Python 3.11. @einarnn is there an ETA for a new release? Python 3.12 is now the default download on python.org.

**Comment by einarnn** [comment]
@ljarasius I will release a new version soon.

**Comment by einarnn** [comment]
@ljarasius, 0.6.15 is now out.

**Comment by ljarasius** [comment]
Thanks @einarnn!
