### ISSUE TITLE
How async ncclient works?

### ISSUE THREAD

**Issue by zljubisic** [ncclient/ncclient#579]
I am trying to figure out how async ncclient works but with no success.
Here is the pole position.

I have a list of devices and commands that I would like to run on them.
From this collection I can either create:
1. a multi RPC xml file per device 
2. bunch of RPC netconf xmls (one RPC per command) for each device

In case of multi RPC in bash I could use something like this to execute all commands on one device and get back result: 
`ssh username@host -p 830 -s netconf < multi_rpc.xml > multi_rpc_output.xml`

Second option is to have as much RPCs as I have commands and than by using (`with manager.connect(...) as m:`) `m.get(filter=rpc_xml)` or `m.edit_config(config=rpc_xml)` to get output of each individual command. This works in synchronous way.

In asynchronous way , as I have multiple devices with their commands, I am expecting to create list of tasks, one task per device that will establish the connection and execute (await) all rpc_xmls for that device and return results.

Such list of tasks should be collected like this:
`result = await asyncio.gather(*tasks)`

Here result should contain all task results (one result per device, and in each such result one sub result for each command) with all its command outputs.

By looking through code I couldn't find out an example that would back up my story above.

I am confused with fact that manager is not an async context manager so I can't use `async with manager.connect(...) as m:`, nor I found another context manager that has `__aenter__`, `__aexit__` and so on.

Can you please provide more information how ncclient should be used to execute netconf xmls concurrently on multiple devices?

**Comment by einarnn** [comment]
@zljubisic, I'm afraid that as of today ncclient is not directly compatible with `asyncio`. It does has a kind of support for async behavior, which you can enable using:

```
m.async_mode = True
```

After setting `async_mode` to `True`, an `RPC` object will be returned, which has a property `event` of type `threading.Event`. The RPC will run on a separate thread. As the caller, you can `wait()` on the event, which is a blocking call, or you can call `is_set()` to do a non-blocking test. `is_set()` will eventually return `True` when the RPC is complete.

No-one has yet written an async context manager for this, but it wouldn't be too hard. Would you consider contributing a PR for an implementation of one?

**Comment by einarnn** [comment]
BTW, #76 has a very old implementation, which is dated to before the `async def` syntax. _May_ be a useful reference point.

**Comment by zljubisic** [comment]
@einarnn Can you please provide a small functional code that will send two commands to two devices using async_mode, just to see how it works right now?

**Comment by einarnn** [comment]
Have a look at this:

```python
from ncclient import manager
import time

if __name__ == '__main__':

    m1 = manager.connect(...)
    m2 = manager.connect(...)

    # set each connection to be async
    m1.async_mode = True
    m2.async_mode = True

    # send request to first node
    r1 = m1.get_config(source='running', filter=('xpath', '/native'))

    # artificial delay between gets
    time.sleep(2.0)

    # send request to second node
    r2 = m2.get_config(source='running', filter=('xpath', '/native'))

    # loop until both requests complete
    while (not r1.event.is_set()) or (not r2.event.is_set()):
        time.sleep(1.0)
        if r1.event.is_set(): r1_finished = True
        if r2.event.is_set(): r2_finished = True
        print('r1 complete: {}, r2 complete: {}'.format(r1.event.is_set(), r2.event.is_set()))


    m1.close_session()
    m2.close_session()
```

**Comment by zljubisic** [comment]
@einarnn please give to us some time to test sync and async ncclient approach with code you have supplied.

**Comment by zljubisic** [comment]
@einarnn Thank you very much for the example you have provided. We have executed it but haven't found time difference between sync and async approach.
We benchmarked netconf and comcli protocols and as comcli is much falster than netconf, we decided that we will not use netconf at all.
Thany you very much for information you have provided.

**Comment by einarnn** [comment]
yw
