### ISSUE TITLE
netconf session hang 

### ISSUE THREAD

**Issue by vincenzheng** [ncclient/ncclient#58]
I found netconf session hang sometimes and I traced it to the _post_connect in session.py.
not sure if  the' init_event.wait()' hang the process if the sever can't response correctly

**Comment by leopoul** [comment]
Hi any update/debug info on this?

Best,
Leo

**Comment by vincenzheng** [comment]
hi, Leopoul,

My router node sometimes has something wrong and it can't response with the capabilities. I guess this caused the init_event.wait() hang because there's no response.  so I just changed it to init_event.wait(5) and let the ncclient keep doing the next.

and it works and it never hang again.

Vincent
