### ISSUE TITLE
juniper_junos_command - lxml.etree.XMLSyntaxError: StartTag: invalid element name

### ISSUE THREAD

**Issue by dineshbaburam91** [ncclient/ncclient#580]
The issue is from ncclient module.  Kindly check this GitHub ticket for more details.

https://github.com/Juniper/ansible-junos-stdlib/issues/528

**Comment by einarnn** [comment]
@dineshbaburam91, having read the thread it's not clear to me why this is an `ncclient` issue, but I may have missed something. For example, if an XML payload contains text such as:

```
set policy-options prefix-list ntp-servers apply-path "system ntp server <*>
```

...then the payload does not conform to the encoding rules. `<` should be encoded as `&lt;` and `>` should be encoded as `&gt;`.

Can you please go into more details here as to why you think `ncclient` or the `lxml` parser is at fault? Specifically, can you show payloads that both conform to the NETCONF encoding rules for XML documents (W3C.REC-xml-20001006) **and** triggers a defect in `ncclient`?

Cheers,

Einar

**Comment by einarnn** [comment]
No feedback on examples requested. Closing for now.
