### ISSUE TITLE
When my process calls manager.connect(), there is a small probability that the process hangs.

### ISSUE THREAD

**Issue by CaiBIRen** [ncclient/ncclient#581]
Check that the process status is sleeping. proc wchan displays futex_wait_queue_me, but it is not clear what resource or semaphore it is waiting for.
source code:

self.connection = manager.connect(host=self.host,
                                  username=self.username,
                                  password=self.password,
                                  port=self.port,
                                  timeout =2,
                                  device_params=self.device,
                                  hostkey_verify=False,
                                  allow_agent=False,
                                  look_for_keys=False)

The process got stuck here and never came out.

**Comment by CaiBIRen** [comment]
connect with ssh

**Comment by CaiBIRen** [comment]
my ncclient version 0.6.9.   netconf connect with ssh mode

**Comment by einarnn** [comment]
@CaiBIRen, not really enough details to give any advice or diagnosis...

**Comment by CaiBIRen** [comment]
@einarnn I finally found out that it was a problem with my program, thank you for your attention
