### ISSUE TITLE
Number of threads per connection

### ISSUE THREAD

**Issue by sambhugit** [ncclient/ncclient#582]
**ncclient** currently uses a minimum of 2 threads for a NETCONF connection. One for SSH, and another "session" thread. But this approach is giving a huge number of threads when scaling. If I have to handle around 10000 NETCONF devices, with persistent and always-on connections in order to recieve notifications and monitorning, my program is going to create 20000 threads, which is huge and highly resource utilizing. I have tried to scale up the application using Gunicorn and load balancers. Still the number of devices I can connect to a 16 core CPU machine is only 4000. Is there any method to resolve this issue?

**Comment by einarnn** [comment]
@sambhugit , agreed, if you need to connect concurrently with 10K devices from a single process then the thread count will be too high to be practical. I would also argue that having 10K devices concurrently connected would also pose a challenge in terms of the number of open sockets you would then need to manage.

Regardless, one approach to resolving the thread count issue could be to provide `asyncio` bindings for ncclient. This is entirely possible but is not trivial to do. It has been suggested a couple of times but, as yet, no-one has had the time to make a contribution. Another option, perhaps not preferred, might be to investigate [Twisted](https://github.com/twisted/twisted), but I feel looking at asyncio could result in a library with fewer depedencies.

**Comment by sambhugit** [comment]
Yes. I think the basic cause for this issue is that NETCONF demands to have a persistant connection inorder to recieve notifications. I will go forward on "asyncio" method and see if any results are obtained.

**Comment by einarnn** [comment]
Closing this issue as no remedial actions need to be taken.
