### ISSUE TITLE
求助:ncclient.transport.errors.AuthenticationError: No authentication methods available

### ISSUE THREAD

**Issue by xietian511ok** [ncclient/ncclient#584]
from ncclient import manager

host =  '192.168.10.74'
port = 830
username = 'api'
password = 'api@2024'

with manager.connect(host=host, port=830, username=username, hostkey_verify=False, device_params={'name':'huawei'}) as m:
    c = m.get_config(source='running').data_xml
    with open("%s.xml" % host, 'w') as f:
        f.write(c)

----------------------------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/ncclient/ncclient/assets/31471825/dbd1b6e5-86e9-43c4-bb94-3497b7cc5b5b)
![image](https://github.com/ncclient/ncclient/assets/31471825/a36585a5-0cff-4637-9561-f14a925564ed)

**Comment by xietian511ok** [comment]
ssh登录是可以的,也可以打开文件逐行执行.但是使用ncclient建立链接就不行,用的是密码鉴权-服务类型api和其他都试过了.有查到说华为ssh返回版本不完整导致的.请问各位大神如何解决.
--------------------------------------------
SSH login is possible, and you can also open the file and execute it line by line. However, using ncclient to establish a link is not possible. We have tried using password authentication service type API and other methods. It has been found that Huawei SSH returned an incomplete version, which caused this issue. How can you solve this problem

**Comment by einarnn** [comment]
@xietian511ok, if a device is not conformant with standards, we should **not** connect with it. I am reluctant to change the core implementation.

However, you can perhaps use the Juniper code as a pattern for how to implement a custom transport session implementation if you are confident that it can be done securely. I'll refer you to:

https://github.com/ncclient/ncclient/tree/master/ncclient/transport/third_party/junos

Perhaps you can implement something similar for Huawei devices?

**Comment by xietian511ok** [comment]
> @xietian511ok, if a device is not conformant with standards, we should **not** connect with it. I am reluctant to change the core implementation.
> 
> However, you can perhaps use the Juniper code as a pattern for how to implement a custom transport session implementation if you are confident that it can be done securely. I'll refer you to:
> 
> https://github.com/ncclient/ncclient/tree/master/ncclient/transport/third_party/junos
> 
> Perhaps you can implement something similar for Huawei devices?

感谢你得回复，我现在已经可以连接到设备，并完成了get、get_config和edit_config的操作。但是我现在遇到另一个问题，不知道如何下发ping的命令。

Thank you for your reply. I am now able to connect to the device and have completed the get, get_config, and edit_config operations. But now I'm facing another problem, I don't know how to issue the ping command.

**Comment by fy-hsiao** [comment]
Hi @xietian511ok ,
You can try with 'look_for_keys' and 'allow_agent' option, I had similar situation and it works for me.

```
with manager.connect(host=host, port=830, username=username, hostkey_verify=False,hostkey_verify=False, look_for_keys=False, allow_agent=False, device_params={'name':'huawei'}) as m:
   c = m.get_config(source='running').data_xml
   with open("%s.xml" % host, 'w') as f:
      f.write(c)
```
