### ISSUE TITLE
ncclient-0.6.15 install in python2.7 env  error

### ISSUE THREAD

**Issue by hooleystark** [ncclient/ncclient#586]
hi，my python version is python2.7.13 and os is debian, when i  use command 'pip2 install ncclient' or 'python2 setup.py install ' to  install ncclient 0.6.15 . there is an error 
![image](https://github.com/ncclient/ncclient/assets/48142271/ab65b4fb-aced-42ad-9f11-a545949fef8a)
![image](https://github.com/ncclient/ncclient/assets/48142271/fd6de5c4-eb4a-465c-b22b-b9d59385f1dd)

The issue is likely due to syntax in version0.6.15  incompatibility with Python 2.7. It work fine with ncclient 0.6.9 or with Python 3.6

**Comment by einarnn** [comment]
Python 2.7 support has been removed from later releases of ncclient soon after the Python 2.7 official EOL, 1st January 2020.

ncclient now only supports Python >= 3.6 and <= 3.11. I realize this isn't entirely clear from the README and setup.py, so will get this updated and made clear.

**Comment by hooleystark** [comment]
ok. thinks

**Comment by hooleystark** [comment]
ok ，thanks
