### ISSUE TITLE
<config> tag raises "Missing XML namespace" error

### ISSUE THREAD

**Issue by pdafv** [ncclient/ncclient#588]
Hey there!

I've seen a couple issues referring the lack of the ```nc``` prefix in the ```config```. I'm using ```lxml``` to generate an ```edit-config``` RPC. I've tried generating it without the  ```config``` tag, but ncclient gives an error. 
I also don't know how to set it as the default namespace using ```lxml``` as described in [#251](https://github.com/ncclient/ncclient/issues/251). The only way I got around this problem is by setting the ```device_params``` to ```huawei``` which I got from [#344](https://github.com/ncclient/ncclient/issues/344). Is there another way to do this? That is, without "hardcoding" the XML?

Thanks in advance!

**Comment by einarnn** [comment]
@pdafv, here is a small fragment when `lxml` in in your Python context, just using the Python repl:

```
>>> from lxml import etree
>>> e = etree.Element('config', nsmap={None: 'urn:ietf:params:xml:ns:netconf:base:1.0'})
>>> etree.tostring(e)
b'<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>'
>>>
```

**Comment by einarnn** [comment]
Closing off this issue.
