### ISSUE TITLE
ImportError: No module named ncclient

### ISSUE THREAD

**Issue by sunshineSun** [ncclient/ncclient#79]
python examples/juniper/*.py

Traceback (most recent call last):
  File "examples/juniper/command-jnpr.py", line 3, in <module>
    from ncclient import manager
ImportError: No module named ncclient

who can tell me the reason? thanks.

**Comment by sunshineSun** [comment]
version ncclient-0.4.3

**Comment by sunshineSun** [comment]
sorry,i know. i  make a mistake.

**Comment by joshipunit** [comment]
What is the mistake here ?. Can you let me know did that ncclient import work ?
