### ISSUE TITLE
ncclient.transport.errors.AuthenticationError: AuthenticationException('Authentication failed.',)

### ISSUE THREAD

**Issue by sunshineSun** [ncclient/ncclient#80]
./nc01.py 156.156.3.131
Traceback (most recent call last):
  File "./nc01.py", line 26, in <module>
    demo(sys.argv[1], "admin","hwbs@com")
  File "./nc01.py", line 20, in demo
    with manager.connect(host=host, port=22, username=user,password=password,unknown_host_cb=default_unknown_host_cb) as m:
  File "build/bdist.linux-i686/egg/ncclient/manager.py", line 147, in connect
  File "build/bdist.linux-i686/egg/ncclient/manager.py", line 120, in connect_ssh
ncclient.transport.errors.AuthenticationError: AuthenticationException('Authentication failed.',)

code:
def default_unknown_host_cb(host,fingerprint):
    return True

def demo(host, user,password):
   # manager.logger.setLevel(logger.INFO)
    with manager.connect(host=host, port=22, username=user,password=password,unknown_host_cb=default_unknown_host_cb) as m:
        for c in m.server_capabilities:
            print c

if **name** == '**main**':
    demo(sys.argv[1], "admin","xxx@com")

who can tell me the reason? thanks

**Comment by sunshineSun** [comment]
i found      self.active  is  false      
 if (not self.active) or (not self.initial_kex_done):
                # we should never try to authenticate unless we're on a secure link
               raise SSHException('No existing session')

**Comment by binaryzer0** [comment]
Hi, can you please explain what change you've made in the code ? I'm stuck on same issue and trying to find a work around.

Here's my code:


`from ncclient import manager

with manager.connect(host='192.168.20.x', port=830, username='admin', hostkey_verify=False, device_params={'name':'csr'}) as m:
    c = m.get_config(source='running').data_xml
    with open("%s.xml" % host, 'w') as f:
        f.write(c)
`

**Comment by leopoul** [comment]
Can you provide details? Looks like you are trying to connect to a Cisco CSR using private key.
Can you enable debugging? 
```
import logging

logging.basicConfig(
    level=logging.INFO,
)
```
at the top of your file. Could you also try to connect via cli? 
```
ssh -p 830 <IP> -s netconf
```

Thanks,
Leonidas

**Comment by b2sweety** [comment]
I am trying to connect to a Juniper device with netconf enabled and getting an authentication error.

2018-03-22 09:56:35,736 ncclient.transport.ssh Authentication (password) failed.

Playbook error:

TASK [RUN TASK] *********************************************************************************************************************************
task path: /home/ycaty/config/Juniper_CREDS.yml:21
<1x.xx.xx.x1> using connection plugin netconf
<1x.xx.xx.x1> socket_path: None
fatal: [junos]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"
}

**************************************************************


Here is the log message:

2018-03-22 09:56:34,512 p=14161 u=root |  creating new control socket for host 1x.xx.xx.x1:830 as user root
2018-03-22 09:56:34,513 p=14161 u=root |  control socket path is /root/.ansible/pc/5582aa85de
2018-03-22 09:56:34,513 p=14161 u=root |  current working directory is /home/ycaty/configs
2018-03-22 09:56:34,514 p=14161 u=root |  using connection plugin netconf
2018-03-22 09:56:34,556 p=14161 u=root |  network_os is set to junos
2018-03-22 09:56:34,559 p=14161 u=root |  ssh connection done, stating ncclient
2018-03-22 09:56:34,793 ncclient.transport.ssh Connected (version 2.0, client OpenSSH_6.0)
2018-03-22 09:56:35,736 ncclient.transport.ssh Auth banner:
-=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=-

S Y S T E M _ A C E S _ W A R N I N G

-=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=-


 You have connected to a private network. This system is to only be used by authorized personnel for authorized business purposes. All activity is monitored and logged. Unauthorized access or activity is a violation of law. If you have connected to this system by mistake, disconnect now.

2018-03-22 09:56:35,736 ncclient.transport.ssh Authentication (password) failed.
2018-03-22 09:56:35,851 p=14161 u=root |  failed to create control socket for host 1x.xx.xx.x1
2018-03-22 09:56:35,852 p=14161 u=root |  Traceback (most recent call last):
  File "/bin/ansible-connection", line 316, in main
    server = Server(socket_path, pc)
  File "/bin/ansible-connection", line 112, in __init__
    self.connection._connect()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/netconf.py", line 158, in _connect
    ssh_config=ssh_config
  File "/usr/lib/python2.7/site-packages/ncclient/manager.py", line 154, in connect
    return connect_ssh(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/ncclient/manager.py", line 119, in connect_ssh
    session.connect(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/ncclient/transport/ssh.py", line 412, in connect
    self._auth(username, password, key_filenames, allow_agent, look_for_keys)
  File "/usr/lib/python2.7/site-packages/ncclient/transport/ssh.py", line 508, in _auth
    raise AuthenticationError(repr(saved_exception))
AuthenticationError: AuthenticationException('Authentication failed.',)

 pip freeze | grep pycrypto
pycrypto==2.6.1
pycryptodomex==3.5.1

pip freeze | grep ncclient
ncclient==0.5.3

ansible 2.4.0.0
 python version = 2.7.5

Am able to login succesfully using the cli:

[ycaty@localhost fortify-base]$ ssh ycaty@1x.xx.xx.x1 -p 830 -s netconf

-=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=-

S Y S T E M _ A C E S _ W A R N I N G

-=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=-


 You have connected to a private network. This system is to only be used by auth                                                                                        orized personnel for authorized business purposes. All activity is monitored and                                                                                         logged. Unauthorized access or activity is a violation of law. If you have conn                                                                                        ected to this system by mistake, disconnect now.
ycaty@1x.xx.xx.x1's password:


<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capabil                                                                                        ity>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file<                                                                                        /capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</capabil                                                                                        ity>
    <capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</                                                                                        capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</capabili                                                                                        ty>
    <capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,                                                                                        ftp,file</capability>
    <capability>http://xml.juniper.net/netconf/junos/1.0</capability>
    <capability>http://xml.juniper.net/dmi/system/1.0</capability>
  </capabilities>
  <session-id>93142</session-id>
</hello>
]]>]]>

Playbook snippet:

- hosts: Juno
  roles:
  - Juniper.junos
  gather_facts: no
  connection: local

  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_ssh_user }}"
      password: "{{ ansible_ssh_pass }}"
      port: "{{ ansible_port }}"

  tasks:
  - name: "SHOW VERSION COMMAND"
    junos_command:
      commands: "show version"
      provider: "{{ cli }}"
    register: result

Can someone help?

**Comment by cspeidel** [comment]
@sunshineSun this is pretty old. Are you still having this issue?

**Comment by cspeidel** [comment]
@sunshineSun hasn't been active on github since 2015. @b2sweety can you open your problem as a new issue instead of adding to someone else's? Thanks!

**Comment by opnine** [comment]
+1 having the same issue.

**Comment by einarnn** [comment]
@opnine, if you are still having a problem, please raise a new issue.

**Comment by stwalking** [comment]
it may be connect by the key not passward, you can change the ssh.SSHSession.connect(look_for_keys=False)

**Comment by jefferygannon** [comment]
still getting this error is there a fix?

**Comment by einarnn** [comment]
@jefferygannon can you please provide debugs for what is happening and note the version of ncclient that you are using. Would appreciate if you could open a fresh issue as this one is closed.
