### ISSUE TITLE
Trying to send a pipe command via ncclient

### ISSUE THREAD

**Issue by evilmarkmark** [ncclient/ncclient#82]
Hey guys,

I can't get the Junos command api to send a pipe. For example: 

mac_address = "00:00:00:00:00:00"
cmds = "show ethernet-switching table | match {}".format(mac_address)

and then passing it to the connection via:
result = conn.command(command=commands, format="text")

This actually gives me the whole mac address table and ignores everything after the pipe

Thanks

**Comment by hellt** [comment]
Have you investigated this any further?
It seems like pipe commands are not supported via netconf protocol.
