### ISSUE TITLE
show commands on ASR1001

### ISSUE THREAD

**Issue by Retenodus** [ncclient/ncclient#83]
Hello,

I try to use ncclient to get the output of show commands on ASR1001 :http://www.cisco.com/c/en/us/td/docs/ios-xml/ios/cns/configuration/xe-3s/cns-xe-3s-book/cns-netconf.html

In particular, the doc says : 

```
NETCONF uses the <get> function to retrieve configuration and device-state information. The NETCONF <get> format is the equivalent of a Cisco IOS show command. The <filter> parameter specifies the portion of the system configuration and device-state data to retrieve. If the <filter> parameter is empty, nothing is returned.

The following are schemas for the <get> function in CLI and CLI-block format. 
NETCONF <get> Request: CLI Format

<?xml version="1.0" encoding=\"UTF-8\"?>
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
    <get>
       <filter>
          <config-format-text-cmd>
             <text-filter-spec> | include interface </text-filter-spec>
          </config-format-text-cmd>
          <oper-data-format-text-block>
             <exec>show interfaces</exec>
             <exec>show arp</exec>
          </oper-data-format-text-block>
       </filter>
    </get>
 </rpc>]]>]]>
```

Using the manager API with the "csr" (ASR1001 have the csr firmware), I can connect.

When I use get with the following filter : 

```
<config-format-text-cmd>
</config-format-text-cmd>
<oper-data-format-text-block>
    <exec>show l2tp sessions</exec>
</oper-data-format-text-block>
```

I get the entire configuration file. When I delete the `<config-format-text-cmd>` part, I get a "protocol error".

It seems the filter is not taken at all. Are the "show" commands supported ?

Regards,
Grégoire Leroy

**Comment by t0mmetje** [comment]
I'm also trying to execute show commands. I can request the entire configuration from a Cisco ME switch when using the device_params of CSR and using the command get_config(source='running').data_xml but I can't manage to execute show commands.

I found some blog describing exec_command() but this does not work.

**Comment by cspeidel** [comment]
@Retenodus what version of ncclient are you using? Is this still an issue with the latest ncclient?

**Comment by einarnn** [comment]
@Retenodus, @tommarcoen, since there has been no further information on this thread I am assuming it is no longer an active issue. Please feel free to reopen if there is still a problem.
