### ISSUE TITLE
Py3 compatibility

### ISSUE THREAD

**Issue by michalsladek** [ncclient/ncclient#9]
Are there any plans for py3 compatibility using one of paramiko's forks?:

https://github.com/paramiko/paramiko/pull/236

Michal

**Comment by nprintz** [comment]
+1

**Comment by johnthagen** [comment]
+1

**Comment by leopoul** [comment]
Currently lives here: https://github.com/leopoul/ncclient/tree/devpy3
Next release which is going to be really soon will include it

Best,
L.

**Comment by mat128** [comment]
Hi Leopoul,

Any news on this? It's hopefully our last blocker for our migration to python 3 ;)

Thank you,
Mathieu

**Comment by andir** [comment]
Any news on the soon to come release ? :-)

**Comment by asmaps** [comment]
In the readme it says, that 0.5.0 with py3 support can be installed from pypitest, but when I look there ther is only 0.4.7 also without py3. I also can't find the code for it anywhere in the git repo. How do I install the dev version with py3?

**Comment by asmaps** [comment]
OK, I just saw, that it is already merged into master, so `pip install -e git+https://github.com/ncclient/ncclient.git#egg=ncclient` does the job
