### ISSUE TITLE
Cannot configure Nexus devices using edit_config

### ISSUE THREAD

**Issue by ajinkyafotedar** [ncclient/ncclient#91]
I've been using ncclient (0.4.3) to configure a Cisco Nexus, and trying to get edit_config to work. If I issue the same rpc from the cli, it works, but does not using a script. Specifically trying the configuration request on pg1-8 of http://www.cisco.com/c/en/us/td/docs/switches/datacenter/sw/nx-os/xml/user/guide/nxos_xml_interface.pdf  

```
from ncclient import manager

snippet = '''<?xml version="1.0"?>
<nc:rpc message-id="16" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns="http://www.cisco.com/nxos:1.0:if_manager">
    <nc:edit-config>
        <nc:target>
            <nc:running/>
        </nc:target>
        <nc:config>
            <configure>
                <__XML__MODE__exec_configure>
                    <interface>
                        <ethernet>
                            <interface>1/5</interface>
                            <__XML__MODE_if-ethernet>
                                <__XML__MODE_if-eth-base>
                                    <description>
                                        <desc_line>test Network1</desc_line>
                                    </description>
                                </__XML__MODE_if-eth-base>
                            </__XML__MODE_if-ethernet>
                        </ethernet>
                    </interface>
                </__XML__MODE__exec_configure>
            </configure>
        </nc:config>
    </nc:edit-config>
</nc:rpc>]]>]]>'''

with manager.connect(host='router', port=22, username='netconf', hostkey_verify=False, device_params={'name':'nexus'}) as m:
    m.edit_config(target='running', config=snippet)
```

Get the following error:
```
Traceback (most recent call last):
  File "testncclient.py", line 31, in <module>
    m.edit_config(target='running', config=snippet)
  File "/Library/Python/2.7/site-packages/ncclient/manager.py", line 156, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/Library/Python/2.7/site-packages/ncclient/manager.py", line 226, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/Library/Python/2.7/site-packages/ncclient/operations/edit.py", line 62, in request
    node.append(validated_element(config, ("config", qualify("config"))))
  File "/Library/Python/2.7/site-packages/ncclient/xml_.py", line 111, in validated_element
    raise XMLError("Element [%s] does not meet requirement" % ele.tag)
ncclient.xml_.XMLError: Element [{urn:ietf:params:xml:ns:netconf:base:1.0}rpc] does not meet requirement
```

Not sure what I'm missing here. Would appreciate any help. Thank you.

**Comment by chapeter** [comment]
I'm running into the same problem

**Comment by leopoul** [comment]
Latest version 0.4.7 introduced a requirement for lxml>3.3.0 which may be related to your issue. Could you check and tell me?

Thnx,
L

**Comment by harshrpatel** [comment]
What was the solution of this issue? why was it closed?

**Comment by bihary84** [comment]
I have the same problem. Is there any update regarding this?

**Comment by ahiremath-rvbd** [comment]
Facing same issue, why this issue closed

Traceback (most recent call last):
  File "edit_config.py", line 82, in <module>
    netconf_response = conn.edit_config(config=create_org, target='running')
  File "/Library/Python/2.7/site-packages/ncclient/manager.py", line 162, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/Library/Python/2.7/site-packages/ncclient/manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/Library/Python/2.7/site-packages/ncclient/operations/edit.py", line 62, in request
    node.append(validated_element(config, ("config", qualify("config"))))
  File "/Library/Python/2.7/site-packages/ncclient/xml_.py", line 134, in validated_element
    raise XMLError("Element [%s] does not meet requirement" % ele.tag)
ncclient.xml_.XMLError: Element [rpc] does not meet requirement

**Comment by levsha8218** [comment]
Does anyone have a solution for this issue? I have the same problem.
Thank you.

**Comment by einarnn** [comment]
If you would like to have this issue triaged, then more details need to be provided. The original error was most likely caused by incorrect inputs, so please provide a full example of what your problem seems to be. I suggest opening a new issue, rather than reusing this one.

**Comment by patrykjeczmien92** [comment]
I have the same problem. The XML query seems to be correct. Has anyone solved it?

**Comment by patrykjeczmien92** [comment]
I just resolved similar problem. Try this:
snippet = '''
<nc:config>
            <configure>
                <__XML__MODE__exec_configure>
                    <interface>
                        <ethernet>
                            <interface>1/5</interface>
                            <__XML__MODE_if-ethernet>
                                <__XML__MODE_if-eth-base>
                                    <description>
                                        <desc_line>test Network1</desc_line>
                                    </description>
                                </__XML__MODE_if-eth-base>
                            </__XML__MODE_if-ethernet>
                        </ethernet>
                    </interface>
                </__XML__MODE__exec_configure>
            </configure>
        </nc:config>'''

**Comment by migazo** [comment]
I got the same problem when trying to configure (rather testing ncclient functionality) a Juniper device, I got this error fixed by adding "extra" <config> in the xml file as so:
 `<config>
	<configuration>
		<interfaces>
			<interface>
				<name>ge-1/1/6</name>
				<unit>
					<name>0</name>
					<description>new configuration testing</description>
					<family>
						<inet>
							<address>
								<name>88.88.88.88/24</name>
							</address>
						</inet>
					</family>
				</unit>
			</interface>
		</interfaces>
	</configuration>
</config>`

old xml file:
`<configuration>
	<interfaces>
		<interface>
			<name>ge-1/1/6</name>
			<unit>
				<name>0</name>
				<description>new configuration testing</description>
				<family>
					<inet>
						<address>
							<name>88.88.88.88/24</name>
						</address>
					</inet>
				</family>
			</unit>
		</interface>
	</interfaces>
</configuration>`
Hopefully this helps someone

**Comment by lu-li-xin** [comment]
Has the problem been solved

**Comment by lu-li-xin** [comment]
How do I write it

**Comment by 315xiaoyao** [comment]
我也遇到这样的问题，有人解决了吗？

**Comment by lu-li-xin** [comment]
> 我也遇到过这样的问题，有人解决了吗？

没有，使用restful开发了。。。
