### ISSUE TITLE
Nccline rollback on Juniper

### ISSUE THREAD

**Issue by hroyd** [ncclient/ncclient#95]
Hi Jeremy

thanks for the efforts on the library. I can't however find a way to send a rollback command from the docs. how could I send 'rollback 2' for example to a juniper device using manager?

Thanks

**Comment by vnitinv** [comment]
you can do

```python
from jnpr.junos import Device
from jnpr.junos.utils.config import Config

dev = Device(......)
cu = Config(dev)
cu.rollback(2)
```
